// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package clientmocks

import (
	"context"
	"sync"

	"github.com/wso2/ai-agent-management-platform/agent-manager-service/clients/openchoreosvc"
	"github.com/wso2/ai-agent-management-platform/agent-manager-service/models"
	"github.com/wso2/ai-agent-management-platform/agent-manager-service/spec"
)

// OpenChoreoSvcClientMock is a mock implementation of openchoreosvc.OpenChoreoSvcClient.
//
//	func TestSomethingThatUsesOpenChoreoSvcClient(t *testing.T) {
//
//		// make and configure a mocked openchoreosvc.OpenChoreoSvcClient
//		mockedOpenChoreoSvcClient := &OpenChoreoSvcClientMock{
//			AttachComponentTraitFunc: func(ctx context.Context, orgName string, projName string, agentName string) error {
//				panic("mock out the AttachComponentTrait method")
//			},
//			CreateAgentComponentFunc: func(ctx context.Context, orgName string, projName string, req *spec.CreateAgentRequest) error {
//				panic("mock out the CreateAgentComponent method")
//			},
//			CreateProjectFunc: func(ctx context.Context, orgName string, projectName string, deploymentPipelineRef string, projectDisplayName string, projectDescription string) error {
//				panic("mock out the CreateProject method")
//			},
//			DeleteAgentComponentFunc: func(ctx context.Context, orgName string, projName string, agentName string) error {
//				panic("mock out the DeleteAgentComponent method")
//			},
//			DeleteProjectFunc: func(ctx context.Context, orgName string, projectName string) error {
//				panic("mock out the DeleteProject method")
//			},
//			DeployAgentComponentFunc: func(ctx context.Context, orgName string, projName string, componentName string, req *spec.DeployAgentRequest) error {
//				panic("mock out the DeployAgentComponent method")
//			},
//			GetAgentComponentFunc: func(ctx context.Context, orgName string, projName string, agentName string) (*openchoreosvc.AgentComponent, error) {
//				panic("mock out the GetAgentComponent method")
//			},
//			GetAgentConfigurationsFunc: func(ctx context.Context, orgName string, projectName string, agentName string, environment string) ([]models.EnvVars, error) {
//				panic("mock out the GetAgentConfigurations method")
//			},
//			GetAgentDeploymentsFunc: func(ctx context.Context, orgName string, pipelineName string, projName string, componentName string) ([]*models.DeploymentResponse, error) {
//				panic("mock out the GetAgentDeployments method")
//			},
//			GetAgentEndpointsFunc: func(ctx context.Context, orgName string, projName string, agentName string, environment string) (map[string]models.EndpointsResponse, error) {
//				panic("mock out the GetAgentEndpoints method")
//			},
//			GetComponentWorkflowFunc: func(ctx context.Context, orgName string, projName string, componentName string, buildName string) (*models.BuildDetailsResponse, error) {
//				panic("mock out the GetComponentWorkflow method")
//			},
//			GetDataplanesForOrganizationFunc: func(ctx context.Context, orgName string) ([]*models.DataPlaneResponse, error) {
//				panic("mock out the GetDataplanesForOrganization method")
//			},
//			GetDeploymentPipelineFunc: func(ctx context.Context, orgName string, deploymentPipelineName string) (*models.DeploymentPipelineResponse, error) {
//				panic("mock out the GetDeploymentPipeline method")
//			},
//			GetDeploymentPipelinesForOrganizationFunc: func(ctx context.Context, orgName string) ([]*models.DeploymentPipelineResponse, error) {
//				panic("mock out the GetDeploymentPipelinesForOrganization method")
//			},
//			GetEnvironmentFunc: func(ctx context.Context, orgName string, environmentName string) (*models.EnvironmentResponse, error) {
//				panic("mock out the GetEnvironment method")
//			},
//			GetOrganizationFunc: func(ctx context.Context, orgName string) (*models.OrganizationResponse, error) {
//				panic("mock out the GetOrganization method")
//			},
//			GetProjectFunc: func(ctx context.Context, projectName string, orgName string) (*models.ProjectResponse, error) {
//				panic("mock out the GetProject method")
//			},
//			IsAgentComponentExistsFunc: func(ctx context.Context, orgName string, projName string, agentName string) (bool, error) {
//				panic("mock out the IsAgentComponentExists method")
//			},
//			ListAgentComponentsFunc: func(ctx context.Context, orgName string, projName string) ([]*openchoreosvc.AgentComponent, error) {
//				panic("mock out the ListAgentComponents method")
//			},
//			ListComponentWorkflowsFunc: func(ctx context.Context, orgName string, projName string, componentName string) ([]*models.BuildResponse, error) {
//				panic("mock out the ListComponentWorkflows method")
//			},
//			ListOrgEnvironmentsFunc: func(ctx context.Context, orgName string) ([]*models.EnvironmentResponse, error) {
//				panic("mock out the ListOrgEnvironments method")
//			},
//			ListProjectsFunc: func(ctx context.Context, orgName string) ([]*models.ProjectResponse, error) {
//				panic("mock out the ListProjects method")
//			},
//			TriggerBuildFunc: func(ctx context.Context, orgName string, projName string, agentName string, commitId string) (*models.BuildResponse, error) {
//				panic("mock out the TriggerBuild method")
//			},
//		}
//
//		// use mockedOpenChoreoSvcClient in code that requires openchoreosvc.OpenChoreoSvcClient
//		// and then make assertions.
//
//	}
type OpenChoreoSvcClientMock struct {
	// AttachComponentTraitFunc mocks the AttachComponentTrait method.
	AttachComponentTraitFunc func(ctx context.Context, orgName string, projName string, agentName string) error

	// CreateAgentComponentFunc mocks the CreateAgentComponent method.
	CreateAgentComponentFunc func(ctx context.Context, orgName string, projName string, req *spec.CreateAgentRequest) error

	// CreateProjectFunc mocks the CreateProject method.
	CreateProjectFunc func(ctx context.Context, orgName string, projectName string, deploymentPipelineRef string, projectDisplayName string, projectDescription string) error

	// DeleteAgentComponentFunc mocks the DeleteAgentComponent method.
	DeleteAgentComponentFunc func(ctx context.Context, orgName string, projName string, agentName string) error

	// DeleteProjectFunc mocks the DeleteProject method.
	DeleteProjectFunc func(ctx context.Context, orgName string, projectName string) error

	// DeployAgentComponentFunc mocks the DeployAgentComponent method.
	DeployAgentComponentFunc func(ctx context.Context, orgName string, projName string, componentName string, req *spec.DeployAgentRequest) error

	// GetAgentComponentFunc mocks the GetAgentComponent method.
	GetAgentComponentFunc func(ctx context.Context, orgName string, projName string, agentName string) (*openchoreosvc.AgentComponent, error)

	// GetAgentConfigurationsFunc mocks the GetAgentConfigurations method.
	GetAgentConfigurationsFunc func(ctx context.Context, orgName string, projectName string, agentName string, environment string) ([]models.EnvVars, error)

	// GetAgentDeploymentsFunc mocks the GetAgentDeployments method.
	GetAgentDeploymentsFunc func(ctx context.Context, orgName string, pipelineName string, projName string, componentName string) ([]*models.DeploymentResponse, error)

	// GetAgentEndpointsFunc mocks the GetAgentEndpoints method.
	GetAgentEndpointsFunc func(ctx context.Context, orgName string, projName string, agentName string, environment string) (map[string]models.EndpointsResponse, error)

	// GetComponentWorkflowFunc mocks the GetComponentWorkflow method.
	GetComponentWorkflowFunc func(ctx context.Context, orgName string, projName string, componentName string, buildName string) (*models.BuildDetailsResponse, error)

	// GetDataplanesForOrganizationFunc mocks the GetDataplanesForOrganization method.
	GetDataplanesForOrganizationFunc func(ctx context.Context, orgName string) ([]*models.DataPlaneResponse, error)

	// GetDeploymentPipelineFunc mocks the GetDeploymentPipeline method.
	GetDeploymentPipelineFunc func(ctx context.Context, orgName string, deploymentPipelineName string) (*models.DeploymentPipelineResponse, error)

	// GetDeploymentPipelinesForOrganizationFunc mocks the GetDeploymentPipelinesForOrganization method.
	GetDeploymentPipelinesForOrganizationFunc func(ctx context.Context, orgName string) ([]*models.DeploymentPipelineResponse, error)

	// GetEnvironmentFunc mocks the GetEnvironment method.
	GetEnvironmentFunc func(ctx context.Context, orgName string, environmentName string) (*models.EnvironmentResponse, error)

	// GetOrganizationFunc mocks the GetOrganization method.
	GetOrganizationFunc func(ctx context.Context, orgName string) (*models.OrganizationResponse, error)

	// GetProjectFunc mocks the GetProject method.
	GetProjectFunc func(ctx context.Context, projectName string, orgName string) (*models.ProjectResponse, error)

	// IsAgentComponentExistsFunc mocks the IsAgentComponentExists method.
	IsAgentComponentExistsFunc func(ctx context.Context, orgName string, projName string, agentName string) (bool, error)

	// ListAgentComponentsFunc mocks the ListAgentComponents method.
	ListAgentComponentsFunc func(ctx context.Context, orgName string, projName string) ([]*openchoreosvc.AgentComponent, error)

	// ListComponentWorkflowsFunc mocks the ListComponentWorkflows method.
	ListComponentWorkflowsFunc func(ctx context.Context, orgName string, projName string, componentName string) ([]*models.BuildResponse, error)

	// ListOrgEnvironmentsFunc mocks the ListOrgEnvironments method.
	ListOrgEnvironmentsFunc func(ctx context.Context, orgName string) ([]*models.EnvironmentResponse, error)

	// ListProjectsFunc mocks the ListProjects method.
	ListProjectsFunc func(ctx context.Context, orgName string) ([]*models.ProjectResponse, error)

	// TriggerBuildFunc mocks the TriggerBuild method.
	TriggerBuildFunc func(ctx context.Context, orgName string, projName string, agentName string, commitId string) (*models.BuildResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// AttachComponentTrait holds details about calls to the AttachComponentTrait method.
		AttachComponentTrait []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjName is the projName argument value.
			ProjName string
			// AgentName is the agentName argument value.
			AgentName string
		}
		// CreateAgentComponent holds details about calls to the CreateAgentComponent method.
		CreateAgentComponent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjName is the projName argument value.
			ProjName string
			// Req is the req argument value.
			Req *spec.CreateAgentRequest
		}
		// CreateProject holds details about calls to the CreateProject method.
		CreateProject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// DeploymentPipelineRef is the deploymentPipelineRef argument value.
			DeploymentPipelineRef string
			// ProjectDisplayName is the projectDisplayName argument value.
			ProjectDisplayName string
			// ProjectDescription is the projectDescription argument value.
			ProjectDescription string
		}
		// DeleteAgentComponent holds details about calls to the DeleteAgentComponent method.
		DeleteAgentComponent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjName is the projName argument value.
			ProjName string
			// AgentName is the agentName argument value.
			AgentName string
		}
		// DeleteProject holds details about calls to the DeleteProject method.
		DeleteProject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
		}
		// DeployAgentComponent holds details about calls to the DeployAgentComponent method.
		DeployAgentComponent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjName is the projName argument value.
			ProjName string
			// ComponentName is the componentName argument value.
			ComponentName string
			// Req is the req argument value.
			Req *spec.DeployAgentRequest
		}
		// GetAgentComponent holds details about calls to the GetAgentComponent method.
		GetAgentComponent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjName is the projName argument value.
			ProjName string
			// AgentName is the agentName argument value.
			AgentName string
		}
		// GetAgentConfigurations holds details about calls to the GetAgentConfigurations method.
		GetAgentConfigurations []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// AgentName is the agentName argument value.
			AgentName string
			// Environment is the environment argument value.
			Environment string
		}
		// GetAgentDeployments holds details about calls to the GetAgentDeployments method.
		GetAgentDeployments []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// PipelineName is the pipelineName argument value.
			PipelineName string
			// ProjName is the projName argument value.
			ProjName string
			// ComponentName is the componentName argument value.
			ComponentName string
		}
		// GetAgentEndpoints holds details about calls to the GetAgentEndpoints method.
		GetAgentEndpoints []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjName is the projName argument value.
			ProjName string
			// AgentName is the agentName argument value.
			AgentName string
			// Environment is the environment argument value.
			Environment string
		}
		// GetComponentWorkflow holds details about calls to the GetComponentWorkflow method.
		GetComponentWorkflow []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjName is the projName argument value.
			ProjName string
			// ComponentName is the componentName argument value.
			ComponentName string
			// BuildName is the buildName argument value.
			BuildName string
		}
		// GetDataplanesForOrganization holds details about calls to the GetDataplanesForOrganization method.
		GetDataplanesForOrganization []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
		}
		// GetDeploymentPipeline holds details about calls to the GetDeploymentPipeline method.
		GetDeploymentPipeline []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// DeploymentPipelineName is the deploymentPipelineName argument value.
			DeploymentPipelineName string
		}
		// GetDeploymentPipelinesForOrganization holds details about calls to the GetDeploymentPipelinesForOrganization method.
		GetDeploymentPipelinesForOrganization []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
		}
		// GetEnvironment holds details about calls to the GetEnvironment method.
		GetEnvironment []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// EnvironmentName is the environmentName argument value.
			EnvironmentName string
		}
		// GetOrganization holds details about calls to the GetOrganization method.
		GetOrganization []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
		}
		// GetProject holds details about calls to the GetProject method.
		GetProject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectName is the projectName argument value.
			ProjectName string
			// OrgName is the orgName argument value.
			OrgName string
		}
		// IsAgentComponentExists holds details about calls to the IsAgentComponentExists method.
		IsAgentComponentExists []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjName is the projName argument value.
			ProjName string
			// AgentName is the agentName argument value.
			AgentName string
		}
		// ListAgentComponents holds details about calls to the ListAgentComponents method.
		ListAgentComponents []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjName is the projName argument value.
			ProjName string
		}
		// ListComponentWorkflows holds details about calls to the ListComponentWorkflows method.
		ListComponentWorkflows []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjName is the projName argument value.
			ProjName string
			// ComponentName is the componentName argument value.
			ComponentName string
		}
		// ListOrgEnvironments holds details about calls to the ListOrgEnvironments method.
		ListOrgEnvironments []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
		}
		// ListProjects holds details about calls to the ListProjects method.
		ListProjects []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
		}
		// TriggerBuild holds details about calls to the TriggerBuild method.
		TriggerBuild []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjName is the projName argument value.
			ProjName string
			// AgentName is the agentName argument value.
			AgentName string
			// CommitId is the commitId argument value.
			CommitId string
		}
	}
	lockAttachComponentTrait                  sync.RWMutex
	lockCreateAgentComponent                  sync.RWMutex
	lockCreateProject                         sync.RWMutex
	lockDeleteAgentComponent                  sync.RWMutex
	lockDeleteProject                         sync.RWMutex
	lockDeployAgentComponent                  sync.RWMutex
	lockGetAgentComponent                     sync.RWMutex
	lockGetAgentConfigurations                sync.RWMutex
	lockGetAgentDeployments                   sync.RWMutex
	lockGetAgentEndpoints                     sync.RWMutex
	lockGetComponentWorkflow                  sync.RWMutex
	lockGetDataplanesForOrganization          sync.RWMutex
	lockGetDeploymentPipeline                 sync.RWMutex
	lockGetDeploymentPipelinesForOrganization sync.RWMutex
	lockGetEnvironment                        sync.RWMutex
	lockGetOrganization                       sync.RWMutex
	lockGetProject                            sync.RWMutex
	lockIsAgentComponentExists                sync.RWMutex
	lockListAgentComponents                   sync.RWMutex
	lockListComponentWorkflows                sync.RWMutex
	lockListOrgEnvironments                   sync.RWMutex
	lockListProjects                          sync.RWMutex
	lockTriggerBuild                          sync.RWMutex
}

// AttachComponentTrait calls AttachComponentTraitFunc.
func (mock *OpenChoreoSvcClientMock) AttachComponentTrait(ctx context.Context, orgName string, projName string, agentName string) error {
	if mock.AttachComponentTraitFunc == nil {
		panic("OpenChoreoSvcClientMock.AttachComponentTraitFunc: method is nil but OpenChoreoSvcClient.AttachComponentTrait was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		OrgName   string
		ProjName  string
		AgentName string
	}{
		Ctx:       ctx,
		OrgName:   orgName,
		ProjName:  projName,
		AgentName: agentName,
	}
	mock.lockAttachComponentTrait.Lock()
	mock.calls.AttachComponentTrait = append(mock.calls.AttachComponentTrait, callInfo)
	mock.lockAttachComponentTrait.Unlock()
	return mock.AttachComponentTraitFunc(ctx, orgName, projName, agentName)
}

// AttachComponentTraitCalls gets all the calls that were made to AttachComponentTrait.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.AttachComponentTraitCalls())
func (mock *OpenChoreoSvcClientMock) AttachComponentTraitCalls() []struct {
	Ctx       context.Context
	OrgName   string
	ProjName  string
	AgentName string
} {
	var calls []struct {
		Ctx       context.Context
		OrgName   string
		ProjName  string
		AgentName string
	}
	mock.lockAttachComponentTrait.RLock()
	calls = mock.calls.AttachComponentTrait
	mock.lockAttachComponentTrait.RUnlock()
	return calls
}

// CreateAgentComponent calls CreateAgentComponentFunc.
func (mock *OpenChoreoSvcClientMock) CreateAgentComponent(ctx context.Context, orgName string, projName string, req *spec.CreateAgentRequest) error {
	if mock.CreateAgentComponentFunc == nil {
		panic("OpenChoreoSvcClientMock.CreateAgentComponentFunc: method is nil but OpenChoreoSvcClient.CreateAgentComponent was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		OrgName  string
		ProjName string
		Req      *spec.CreateAgentRequest
	}{
		Ctx:      ctx,
		OrgName:  orgName,
		ProjName: projName,
		Req:      req,
	}
	mock.lockCreateAgentComponent.Lock()
	mock.calls.CreateAgentComponent = append(mock.calls.CreateAgentComponent, callInfo)
	mock.lockCreateAgentComponent.Unlock()
	return mock.CreateAgentComponentFunc(ctx, orgName, projName, req)
}

// CreateAgentComponentCalls gets all the calls that were made to CreateAgentComponent.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.CreateAgentComponentCalls())
func (mock *OpenChoreoSvcClientMock) CreateAgentComponentCalls() []struct {
	Ctx      context.Context
	OrgName  string
	ProjName string
	Req      *spec.CreateAgentRequest
} {
	var calls []struct {
		Ctx      context.Context
		OrgName  string
		ProjName string
		Req      *spec.CreateAgentRequest
	}
	mock.lockCreateAgentComponent.RLock()
	calls = mock.calls.CreateAgentComponent
	mock.lockCreateAgentComponent.RUnlock()
	return calls
}

// CreateProject calls CreateProjectFunc.
func (mock *OpenChoreoSvcClientMock) CreateProject(ctx context.Context, orgName string, projectName string, deploymentPipelineRef string, projectDisplayName string, projectDescription string) error {
	if mock.CreateProjectFunc == nil {
		panic("OpenChoreoSvcClientMock.CreateProjectFunc: method is nil but OpenChoreoSvcClient.CreateProject was just called")
	}
	callInfo := struct {
		Ctx                   context.Context
		OrgName               string
		ProjectName           string
		DeploymentPipelineRef string
		ProjectDisplayName    string
		ProjectDescription    string
	}{
		Ctx:                   ctx,
		OrgName:               orgName,
		ProjectName:           projectName,
		DeploymentPipelineRef: deploymentPipelineRef,
		ProjectDisplayName:    projectDisplayName,
		ProjectDescription:    projectDescription,
	}
	mock.lockCreateProject.Lock()
	mock.calls.CreateProject = append(mock.calls.CreateProject, callInfo)
	mock.lockCreateProject.Unlock()
	return mock.CreateProjectFunc(ctx, orgName, projectName, deploymentPipelineRef, projectDisplayName, projectDescription)
}

// CreateProjectCalls gets all the calls that were made to CreateProject.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.CreateProjectCalls())
func (mock *OpenChoreoSvcClientMock) CreateProjectCalls() []struct {
	Ctx                   context.Context
	OrgName               string
	ProjectName           string
	DeploymentPipelineRef string
	ProjectDisplayName    string
	ProjectDescription    string
} {
	var calls []struct {
		Ctx                   context.Context
		OrgName               string
		ProjectName           string
		DeploymentPipelineRef string
		ProjectDisplayName    string
		ProjectDescription    string
	}
	mock.lockCreateProject.RLock()
	calls = mock.calls.CreateProject
	mock.lockCreateProject.RUnlock()
	return calls
}

// DeleteAgentComponent calls DeleteAgentComponentFunc.
func (mock *OpenChoreoSvcClientMock) DeleteAgentComponent(ctx context.Context, orgName string, projName string, agentName string) error {
	if mock.DeleteAgentComponentFunc == nil {
		panic("OpenChoreoSvcClientMock.DeleteAgentComponentFunc: method is nil but OpenChoreoSvcClient.DeleteAgentComponent was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		OrgName   string
		ProjName  string
		AgentName string
	}{
		Ctx:       ctx,
		OrgName:   orgName,
		ProjName:  projName,
		AgentName: agentName,
	}
	mock.lockDeleteAgentComponent.Lock()
	mock.calls.DeleteAgentComponent = append(mock.calls.DeleteAgentComponent, callInfo)
	mock.lockDeleteAgentComponent.Unlock()
	return mock.DeleteAgentComponentFunc(ctx, orgName, projName, agentName)
}

// DeleteAgentComponentCalls gets all the calls that were made to DeleteAgentComponent.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.DeleteAgentComponentCalls())
func (mock *OpenChoreoSvcClientMock) DeleteAgentComponentCalls() []struct {
	Ctx       context.Context
	OrgName   string
	ProjName  string
	AgentName string
} {
	var calls []struct {
		Ctx       context.Context
		OrgName   string
		ProjName  string
		AgentName string
	}
	mock.lockDeleteAgentComponent.RLock()
	calls = mock.calls.DeleteAgentComponent
	mock.lockDeleteAgentComponent.RUnlock()
	return calls
}

// DeleteProject calls DeleteProjectFunc.
func (mock *OpenChoreoSvcClientMock) DeleteProject(ctx context.Context, orgName string, projectName string) error {
	if mock.DeleteProjectFunc == nil {
		panic("OpenChoreoSvcClientMock.DeleteProjectFunc: method is nil but OpenChoreoSvcClient.DeleteProject was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
	}{
		Ctx:         ctx,
		OrgName:     orgName,
		ProjectName: projectName,
	}
	mock.lockDeleteProject.Lock()
	mock.calls.DeleteProject = append(mock.calls.DeleteProject, callInfo)
	mock.lockDeleteProject.Unlock()
	return mock.DeleteProjectFunc(ctx, orgName, projectName)
}

// DeleteProjectCalls gets all the calls that were made to DeleteProject.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.DeleteProjectCalls())
func (mock *OpenChoreoSvcClientMock) DeleteProjectCalls() []struct {
	Ctx         context.Context
	OrgName     string
	ProjectName string
} {
	var calls []struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
	}
	mock.lockDeleteProject.RLock()
	calls = mock.calls.DeleteProject
	mock.lockDeleteProject.RUnlock()
	return calls
}

// DeployAgentComponent calls DeployAgentComponentFunc.
func (mock *OpenChoreoSvcClientMock) DeployAgentComponent(ctx context.Context, orgName string, projName string, componentName string, req *spec.DeployAgentRequest) error {
	if mock.DeployAgentComponentFunc == nil {
		panic("OpenChoreoSvcClientMock.DeployAgentComponentFunc: method is nil but OpenChoreoSvcClient.DeployAgentComponent was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		ProjName      string
		ComponentName string
		Req           *spec.DeployAgentRequest
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		ProjName:      projName,
		ComponentName: componentName,
		Req:           req,
	}
	mock.lockDeployAgentComponent.Lock()
	mock.calls.DeployAgentComponent = append(mock.calls.DeployAgentComponent, callInfo)
	mock.lockDeployAgentComponent.Unlock()
	return mock.DeployAgentComponentFunc(ctx, orgName, projName, componentName, req)
}

// DeployAgentComponentCalls gets all the calls that were made to DeployAgentComponent.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.DeployAgentComponentCalls())
func (mock *OpenChoreoSvcClientMock) DeployAgentComponentCalls() []struct {
	Ctx           context.Context
	OrgName       string
	ProjName      string
	ComponentName string
	Req           *spec.DeployAgentRequest
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		ProjName      string
		ComponentName string
		Req           *spec.DeployAgentRequest
	}
	mock.lockDeployAgentComponent.RLock()
	calls = mock.calls.DeployAgentComponent
	mock.lockDeployAgentComponent.RUnlock()
	return calls
}

// GetAgentComponent calls GetAgentComponentFunc.
func (mock *OpenChoreoSvcClientMock) GetAgentComponent(ctx context.Context, orgName string, projName string, agentName string) (*openchoreosvc.AgentComponent, error) {
	if mock.GetAgentComponentFunc == nil {
		panic("OpenChoreoSvcClientMock.GetAgentComponentFunc: method is nil but OpenChoreoSvcClient.GetAgentComponent was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		OrgName   string
		ProjName  string
		AgentName string
	}{
		Ctx:       ctx,
		OrgName:   orgName,
		ProjName:  projName,
		AgentName: agentName,
	}
	mock.lockGetAgentComponent.Lock()
	mock.calls.GetAgentComponent = append(mock.calls.GetAgentComponent, callInfo)
	mock.lockGetAgentComponent.Unlock()
	return mock.GetAgentComponentFunc(ctx, orgName, projName, agentName)
}

// GetAgentComponentCalls gets all the calls that were made to GetAgentComponent.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.GetAgentComponentCalls())
func (mock *OpenChoreoSvcClientMock) GetAgentComponentCalls() []struct {
	Ctx       context.Context
	OrgName   string
	ProjName  string
	AgentName string
} {
	var calls []struct {
		Ctx       context.Context
		OrgName   string
		ProjName  string
		AgentName string
	}
	mock.lockGetAgentComponent.RLock()
	calls = mock.calls.GetAgentComponent
	mock.lockGetAgentComponent.RUnlock()
	return calls
}

// GetAgentConfigurations calls GetAgentConfigurationsFunc.
func (mock *OpenChoreoSvcClientMock) GetAgentConfigurations(ctx context.Context, orgName string, projectName string, agentName string, environment string) ([]models.EnvVars, error) {
	if mock.GetAgentConfigurationsFunc == nil {
		panic("OpenChoreoSvcClientMock.GetAgentConfigurationsFunc: method is nil but OpenChoreoSvcClient.GetAgentConfigurations was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		AgentName   string
		Environment string
	}{
		Ctx:         ctx,
		OrgName:     orgName,
		ProjectName: projectName,
		AgentName:   agentName,
		Environment: environment,
	}
	mock.lockGetAgentConfigurations.Lock()
	mock.calls.GetAgentConfigurations = append(mock.calls.GetAgentConfigurations, callInfo)
	mock.lockGetAgentConfigurations.Unlock()
	return mock.GetAgentConfigurationsFunc(ctx, orgName, projectName, agentName, environment)
}

// GetAgentConfigurationsCalls gets all the calls that were made to GetAgentConfigurations.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.GetAgentConfigurationsCalls())
func (mock *OpenChoreoSvcClientMock) GetAgentConfigurationsCalls() []struct {
	Ctx         context.Context
	OrgName     string
	ProjectName string
	AgentName   string
	Environment string
} {
	var calls []struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		AgentName   string
		Environment string
	}
	mock.lockGetAgentConfigurations.RLock()
	calls = mock.calls.GetAgentConfigurations
	mock.lockGetAgentConfigurations.RUnlock()
	return calls
}

// GetAgentDeployments calls GetAgentDeploymentsFunc.
func (mock *OpenChoreoSvcClientMock) GetAgentDeployments(ctx context.Context, orgName string, pipelineName string, projName string, componentName string) ([]*models.DeploymentResponse, error) {
	if mock.GetAgentDeploymentsFunc == nil {
		panic("OpenChoreoSvcClientMock.GetAgentDeploymentsFunc: method is nil but OpenChoreoSvcClient.GetAgentDeployments was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		PipelineName  string
		ProjName      string
		ComponentName string
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		PipelineName:  pipelineName,
		ProjName:      projName,
		ComponentName: componentName,
	}
	mock.lockGetAgentDeployments.Lock()
	mock.calls.GetAgentDeployments = append(mock.calls.GetAgentDeployments, callInfo)
	mock.lockGetAgentDeployments.Unlock()
	return mock.GetAgentDeploymentsFunc(ctx, orgName, pipelineName, projName, componentName)
}

// GetAgentDeploymentsCalls gets all the calls that were made to GetAgentDeployments.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.GetAgentDeploymentsCalls())
func (mock *OpenChoreoSvcClientMock) GetAgentDeploymentsCalls() []struct {
	Ctx           context.Context
	OrgName       string
	PipelineName  string
	ProjName      string
	ComponentName string
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		PipelineName  string
		ProjName      string
		ComponentName string
	}
	mock.lockGetAgentDeployments.RLock()
	calls = mock.calls.GetAgentDeployments
	mock.lockGetAgentDeployments.RUnlock()
	return calls
}

// GetAgentEndpoints calls GetAgentEndpointsFunc.
func (mock *OpenChoreoSvcClientMock) GetAgentEndpoints(ctx context.Context, orgName string, projName string, agentName string, environment string) (map[string]models.EndpointsResponse, error) {
	if mock.GetAgentEndpointsFunc == nil {
		panic("OpenChoreoSvcClientMock.GetAgentEndpointsFunc: method is nil but OpenChoreoSvcClient.GetAgentEndpoints was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		OrgName     string
		ProjName    string
		AgentName   string
		Environment string
	}{
		Ctx:         ctx,
		OrgName:     orgName,
		ProjName:    projName,
		AgentName:   agentName,
		Environment: environment,
	}
	mock.lockGetAgentEndpoints.Lock()
	mock.calls.GetAgentEndpoints = append(mock.calls.GetAgentEndpoints, callInfo)
	mock.lockGetAgentEndpoints.Unlock()
	return mock.GetAgentEndpointsFunc(ctx, orgName, projName, agentName, environment)
}

// GetAgentEndpointsCalls gets all the calls that were made to GetAgentEndpoints.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.GetAgentEndpointsCalls())
func (mock *OpenChoreoSvcClientMock) GetAgentEndpointsCalls() []struct {
	Ctx         context.Context
	OrgName     string
	ProjName    string
	AgentName   string
	Environment string
} {
	var calls []struct {
		Ctx         context.Context
		OrgName     string
		ProjName    string
		AgentName   string
		Environment string
	}
	mock.lockGetAgentEndpoints.RLock()
	calls = mock.calls.GetAgentEndpoints
	mock.lockGetAgentEndpoints.RUnlock()
	return calls
}

// GetComponentWorkflow calls GetComponentWorkflowFunc.
func (mock *OpenChoreoSvcClientMock) GetComponentWorkflow(ctx context.Context, orgName string, projName string, componentName string, buildName string) (*models.BuildDetailsResponse, error) {
	if mock.GetComponentWorkflowFunc == nil {
		panic("OpenChoreoSvcClientMock.GetComponentWorkflowFunc: method is nil but OpenChoreoSvcClient.GetComponentWorkflow was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		ProjName      string
		ComponentName string
		BuildName     string
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		ProjName:      projName,
		ComponentName: componentName,
		BuildName:     buildName,
	}
	mock.lockGetComponentWorkflow.Lock()
	mock.calls.GetComponentWorkflow = append(mock.calls.GetComponentWorkflow, callInfo)
	mock.lockGetComponentWorkflow.Unlock()
	return mock.GetComponentWorkflowFunc(ctx, orgName, projName, componentName, buildName)
}

// GetComponentWorkflowCalls gets all the calls that were made to GetComponentWorkflow.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.GetComponentWorkflowCalls())
func (mock *OpenChoreoSvcClientMock) GetComponentWorkflowCalls() []struct {
	Ctx           context.Context
	OrgName       string
	ProjName      string
	ComponentName string
	BuildName     string
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		ProjName      string
		ComponentName string
		BuildName     string
	}
	mock.lockGetComponentWorkflow.RLock()
	calls = mock.calls.GetComponentWorkflow
	mock.lockGetComponentWorkflow.RUnlock()
	return calls
}

// GetDataplanesForOrganization calls GetDataplanesForOrganizationFunc.
func (mock *OpenChoreoSvcClientMock) GetDataplanesForOrganization(ctx context.Context, orgName string) ([]*models.DataPlaneResponse, error) {
	if mock.GetDataplanesForOrganizationFunc == nil {
		panic("OpenChoreoSvcClientMock.GetDataplanesForOrganizationFunc: method is nil but OpenChoreoSvcClient.GetDataplanesForOrganization was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OrgName string
	}{
		Ctx:     ctx,
		OrgName: orgName,
	}
	mock.lockGetDataplanesForOrganization.Lock()
	mock.calls.GetDataplanesForOrganization = append(mock.calls.GetDataplanesForOrganization, callInfo)
	mock.lockGetDataplanesForOrganization.Unlock()
	return mock.GetDataplanesForOrganizationFunc(ctx, orgName)
}

// GetDataplanesForOrganizationCalls gets all the calls that were made to GetDataplanesForOrganization.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.GetDataplanesForOrganizationCalls())
func (mock *OpenChoreoSvcClientMock) GetDataplanesForOrganizationCalls() []struct {
	Ctx     context.Context
	OrgName string
} {
	var calls []struct {
		Ctx     context.Context
		OrgName string
	}
	mock.lockGetDataplanesForOrganization.RLock()
	calls = mock.calls.GetDataplanesForOrganization
	mock.lockGetDataplanesForOrganization.RUnlock()
	return calls
}

// GetDeploymentPipeline calls GetDeploymentPipelineFunc.
func (mock *OpenChoreoSvcClientMock) GetDeploymentPipeline(ctx context.Context, orgName string, deploymentPipelineName string) (*models.DeploymentPipelineResponse, error) {
	if mock.GetDeploymentPipelineFunc == nil {
		panic("OpenChoreoSvcClientMock.GetDeploymentPipelineFunc: method is nil but OpenChoreoSvcClient.GetDeploymentPipeline was just called")
	}
	callInfo := struct {
		Ctx                    context.Context
		OrgName                string
		DeploymentPipelineName string
	}{
		Ctx:                    ctx,
		OrgName:                orgName,
		DeploymentPipelineName: deploymentPipelineName,
	}
	mock.lockGetDeploymentPipeline.Lock()
	mock.calls.GetDeploymentPipeline = append(mock.calls.GetDeploymentPipeline, callInfo)
	mock.lockGetDeploymentPipeline.Unlock()
	return mock.GetDeploymentPipelineFunc(ctx, orgName, deploymentPipelineName)
}

// GetDeploymentPipelineCalls gets all the calls that were made to GetDeploymentPipeline.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.GetDeploymentPipelineCalls())
func (mock *OpenChoreoSvcClientMock) GetDeploymentPipelineCalls() []struct {
	Ctx                    context.Context
	OrgName                string
	DeploymentPipelineName string
} {
	var calls []struct {
		Ctx                    context.Context
		OrgName                string
		DeploymentPipelineName string
	}
	mock.lockGetDeploymentPipeline.RLock()
	calls = mock.calls.GetDeploymentPipeline
	mock.lockGetDeploymentPipeline.RUnlock()
	return calls
}

// GetDeploymentPipelinesForOrganization calls GetDeploymentPipelinesForOrganizationFunc.
func (mock *OpenChoreoSvcClientMock) GetDeploymentPipelinesForOrganization(ctx context.Context, orgName string) ([]*models.DeploymentPipelineResponse, error) {
	if mock.GetDeploymentPipelinesForOrganizationFunc == nil {
		panic("OpenChoreoSvcClientMock.GetDeploymentPipelinesForOrganizationFunc: method is nil but OpenChoreoSvcClient.GetDeploymentPipelinesForOrganization was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OrgName string
	}{
		Ctx:     ctx,
		OrgName: orgName,
	}
	mock.lockGetDeploymentPipelinesForOrganization.Lock()
	mock.calls.GetDeploymentPipelinesForOrganization = append(mock.calls.GetDeploymentPipelinesForOrganization, callInfo)
	mock.lockGetDeploymentPipelinesForOrganization.Unlock()
	return mock.GetDeploymentPipelinesForOrganizationFunc(ctx, orgName)
}

// GetDeploymentPipelinesForOrganizationCalls gets all the calls that were made to GetDeploymentPipelinesForOrganization.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.GetDeploymentPipelinesForOrganizationCalls())
func (mock *OpenChoreoSvcClientMock) GetDeploymentPipelinesForOrganizationCalls() []struct {
	Ctx     context.Context
	OrgName string
} {
	var calls []struct {
		Ctx     context.Context
		OrgName string
	}
	mock.lockGetDeploymentPipelinesForOrganization.RLock()
	calls = mock.calls.GetDeploymentPipelinesForOrganization
	mock.lockGetDeploymentPipelinesForOrganization.RUnlock()
	return calls
}

// GetEnvironment calls GetEnvironmentFunc.
func (mock *OpenChoreoSvcClientMock) GetEnvironment(ctx context.Context, orgName string, environmentName string) (*models.EnvironmentResponse, error) {
	if mock.GetEnvironmentFunc == nil {
		panic("OpenChoreoSvcClientMock.GetEnvironmentFunc: method is nil but OpenChoreoSvcClient.GetEnvironment was just called")
	}
	callInfo := struct {
		Ctx             context.Context
		OrgName         string
		EnvironmentName string
	}{
		Ctx:             ctx,
		OrgName:         orgName,
		EnvironmentName: environmentName,
	}
	mock.lockGetEnvironment.Lock()
	mock.calls.GetEnvironment = append(mock.calls.GetEnvironment, callInfo)
	mock.lockGetEnvironment.Unlock()
	return mock.GetEnvironmentFunc(ctx, orgName, environmentName)
}

// GetEnvironmentCalls gets all the calls that were made to GetEnvironment.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.GetEnvironmentCalls())
func (mock *OpenChoreoSvcClientMock) GetEnvironmentCalls() []struct {
	Ctx             context.Context
	OrgName         string
	EnvironmentName string
} {
	var calls []struct {
		Ctx             context.Context
		OrgName         string
		EnvironmentName string
	}
	mock.lockGetEnvironment.RLock()
	calls = mock.calls.GetEnvironment
	mock.lockGetEnvironment.RUnlock()
	return calls
}

// GetOrganization calls GetOrganizationFunc.
func (mock *OpenChoreoSvcClientMock) GetOrganization(ctx context.Context, orgName string) (*models.OrganizationResponse, error) {
	if mock.GetOrganizationFunc == nil {
		panic("OpenChoreoSvcClientMock.GetOrganizationFunc: method is nil but OpenChoreoSvcClient.GetOrganization was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OrgName string
	}{
		Ctx:     ctx,
		OrgName: orgName,
	}
	mock.lockGetOrganization.Lock()
	mock.calls.GetOrganization = append(mock.calls.GetOrganization, callInfo)
	mock.lockGetOrganization.Unlock()
	return mock.GetOrganizationFunc(ctx, orgName)
}

// GetOrganizationCalls gets all the calls that were made to GetOrganization.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.GetOrganizationCalls())
func (mock *OpenChoreoSvcClientMock) GetOrganizationCalls() []struct {
	Ctx     context.Context
	OrgName string
} {
	var calls []struct {
		Ctx     context.Context
		OrgName string
	}
	mock.lockGetOrganization.RLock()
	calls = mock.calls.GetOrganization
	mock.lockGetOrganization.RUnlock()
	return calls
}

// GetProject calls GetProjectFunc.
func (mock *OpenChoreoSvcClientMock) GetProject(ctx context.Context, projectName string, orgName string) (*models.ProjectResponse, error) {
	if mock.GetProjectFunc == nil {
		panic("OpenChoreoSvcClientMock.GetProjectFunc: method is nil but OpenChoreoSvcClient.GetProject was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		ProjectName string
		OrgName     string
	}{
		Ctx:         ctx,
		ProjectName: projectName,
		OrgName:     orgName,
	}
	mock.lockGetProject.Lock()
	mock.calls.GetProject = append(mock.calls.GetProject, callInfo)
	mock.lockGetProject.Unlock()
	return mock.GetProjectFunc(ctx, projectName, orgName)
}

// GetProjectCalls gets all the calls that were made to GetProject.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.GetProjectCalls())
func (mock *OpenChoreoSvcClientMock) GetProjectCalls() []struct {
	Ctx         context.Context
	ProjectName string
	OrgName     string
} {
	var calls []struct {
		Ctx         context.Context
		ProjectName string
		OrgName     string
	}
	mock.lockGetProject.RLock()
	calls = mock.calls.GetProject
	mock.lockGetProject.RUnlock()
	return calls
}

// IsAgentComponentExists calls IsAgentComponentExistsFunc.
func (mock *OpenChoreoSvcClientMock) IsAgentComponentExists(ctx context.Context, orgName string, projName string, agentName string) (bool, error) {
	if mock.IsAgentComponentExistsFunc == nil {
		panic("OpenChoreoSvcClientMock.IsAgentComponentExistsFunc: method is nil but OpenChoreoSvcClient.IsAgentComponentExists was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		OrgName   string
		ProjName  string
		AgentName string
	}{
		Ctx:       ctx,
		OrgName:   orgName,
		ProjName:  projName,
		AgentName: agentName,
	}
	mock.lockIsAgentComponentExists.Lock()
	mock.calls.IsAgentComponentExists = append(mock.calls.IsAgentComponentExists, callInfo)
	mock.lockIsAgentComponentExists.Unlock()
	return mock.IsAgentComponentExistsFunc(ctx, orgName, projName, agentName)
}

// IsAgentComponentExistsCalls gets all the calls that were made to IsAgentComponentExists.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.IsAgentComponentExistsCalls())
func (mock *OpenChoreoSvcClientMock) IsAgentComponentExistsCalls() []struct {
	Ctx       context.Context
	OrgName   string
	ProjName  string
	AgentName string
} {
	var calls []struct {
		Ctx       context.Context
		OrgName   string
		ProjName  string
		AgentName string
	}
	mock.lockIsAgentComponentExists.RLock()
	calls = mock.calls.IsAgentComponentExists
	mock.lockIsAgentComponentExists.RUnlock()
	return calls
}

// ListAgentComponents calls ListAgentComponentsFunc.
func (mock *OpenChoreoSvcClientMock) ListAgentComponents(ctx context.Context, orgName string, projName string) ([]*openchoreosvc.AgentComponent, error) {
	if mock.ListAgentComponentsFunc == nil {
		panic("OpenChoreoSvcClientMock.ListAgentComponentsFunc: method is nil but OpenChoreoSvcClient.ListAgentComponents was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		OrgName  string
		ProjName string
	}{
		Ctx:      ctx,
		OrgName:  orgName,
		ProjName: projName,
	}
	mock.lockListAgentComponents.Lock()
	mock.calls.ListAgentComponents = append(mock.calls.ListAgentComponents, callInfo)
	mock.lockListAgentComponents.Unlock()
	return mock.ListAgentComponentsFunc(ctx, orgName, projName)
}

// ListAgentComponentsCalls gets all the calls that were made to ListAgentComponents.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.ListAgentComponentsCalls())
func (mock *OpenChoreoSvcClientMock) ListAgentComponentsCalls() []struct {
	Ctx      context.Context
	OrgName  string
	ProjName string
} {
	var calls []struct {
		Ctx      context.Context
		OrgName  string
		ProjName string
	}
	mock.lockListAgentComponents.RLock()
	calls = mock.calls.ListAgentComponents
	mock.lockListAgentComponents.RUnlock()
	return calls
}

// ListComponentWorkflows calls ListComponentWorkflowsFunc.
func (mock *OpenChoreoSvcClientMock) ListComponentWorkflows(ctx context.Context, orgName string, projName string, componentName string) ([]*models.BuildResponse, error) {
	if mock.ListComponentWorkflowsFunc == nil {
		panic("OpenChoreoSvcClientMock.ListComponentWorkflowsFunc: method is nil but OpenChoreoSvcClient.ListComponentWorkflows was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		ProjName      string
		ComponentName string
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		ProjName:      projName,
		ComponentName: componentName,
	}
	mock.lockListComponentWorkflows.Lock()
	mock.calls.ListComponentWorkflows = append(mock.calls.ListComponentWorkflows, callInfo)
	mock.lockListComponentWorkflows.Unlock()
	return mock.ListComponentWorkflowsFunc(ctx, orgName, projName, componentName)
}

// ListComponentWorkflowsCalls gets all the calls that were made to ListComponentWorkflows.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.ListComponentWorkflowsCalls())
func (mock *OpenChoreoSvcClientMock) ListComponentWorkflowsCalls() []struct {
	Ctx           context.Context
	OrgName       string
	ProjName      string
	ComponentName string
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		ProjName      string
		ComponentName string
	}
	mock.lockListComponentWorkflows.RLock()
	calls = mock.calls.ListComponentWorkflows
	mock.lockListComponentWorkflows.RUnlock()
	return calls
}

// ListOrgEnvironments calls ListOrgEnvironmentsFunc.
func (mock *OpenChoreoSvcClientMock) ListOrgEnvironments(ctx context.Context, orgName string) ([]*models.EnvironmentResponse, error) {
	if mock.ListOrgEnvironmentsFunc == nil {
		panic("OpenChoreoSvcClientMock.ListOrgEnvironmentsFunc: method is nil but OpenChoreoSvcClient.ListOrgEnvironments was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OrgName string
	}{
		Ctx:     ctx,
		OrgName: orgName,
	}
	mock.lockListOrgEnvironments.Lock()
	mock.calls.ListOrgEnvironments = append(mock.calls.ListOrgEnvironments, callInfo)
	mock.lockListOrgEnvironments.Unlock()
	return mock.ListOrgEnvironmentsFunc(ctx, orgName)
}

// ListOrgEnvironmentsCalls gets all the calls that were made to ListOrgEnvironments.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.ListOrgEnvironmentsCalls())
func (mock *OpenChoreoSvcClientMock) ListOrgEnvironmentsCalls() []struct {
	Ctx     context.Context
	OrgName string
} {
	var calls []struct {
		Ctx     context.Context
		OrgName string
	}
	mock.lockListOrgEnvironments.RLock()
	calls = mock.calls.ListOrgEnvironments
	mock.lockListOrgEnvironments.RUnlock()
	return calls
}

// ListProjects calls ListProjectsFunc.
func (mock *OpenChoreoSvcClientMock) ListProjects(ctx context.Context, orgName string) ([]*models.ProjectResponse, error) {
	if mock.ListProjectsFunc == nil {
		panic("OpenChoreoSvcClientMock.ListProjectsFunc: method is nil but OpenChoreoSvcClient.ListProjects was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OrgName string
	}{
		Ctx:     ctx,
		OrgName: orgName,
	}
	mock.lockListProjects.Lock()
	mock.calls.ListProjects = append(mock.calls.ListProjects, callInfo)
	mock.lockListProjects.Unlock()
	return mock.ListProjectsFunc(ctx, orgName)
}

// ListProjectsCalls gets all the calls that were made to ListProjects.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.ListProjectsCalls())
func (mock *OpenChoreoSvcClientMock) ListProjectsCalls() []struct {
	Ctx     context.Context
	OrgName string
} {
	var calls []struct {
		Ctx     context.Context
		OrgName string
	}
	mock.lockListProjects.RLock()
	calls = mock.calls.ListProjects
	mock.lockListProjects.RUnlock()
	return calls
}

// TriggerBuild calls TriggerBuildFunc.
func (mock *OpenChoreoSvcClientMock) TriggerBuild(ctx context.Context, orgName string, projName string, agentName string, commitId string) (*models.BuildResponse, error) {
	if mock.TriggerBuildFunc == nil {
		panic("OpenChoreoSvcClientMock.TriggerBuildFunc: method is nil but OpenChoreoSvcClient.TriggerBuild was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		OrgName   string
		ProjName  string
		AgentName string
		CommitId  string
	}{
		Ctx:       ctx,
		OrgName:   orgName,
		ProjName:  projName,
		AgentName: agentName,
		CommitId:  commitId,
	}
	mock.lockTriggerBuild.Lock()
	mock.calls.TriggerBuild = append(mock.calls.TriggerBuild, callInfo)
	mock.lockTriggerBuild.Unlock()
	return mock.TriggerBuildFunc(ctx, orgName, projName, agentName, commitId)
}

// TriggerBuildCalls gets all the calls that were made to TriggerBuild.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.TriggerBuildCalls())
func (mock *OpenChoreoSvcClientMock) TriggerBuildCalls() []struct {
	Ctx       context.Context
	OrgName   string
	ProjName  string
	AgentName string
	CommitId  string
} {
	var calls []struct {
		Ctx       context.Context
		OrgName   string
		ProjName  string
		AgentName string
		CommitId  string
	}
	mock.lockTriggerBuild.RLock()
	calls = mock.calls.TriggerBuild
	mock.lockTriggerBuild.RUnlock()
	return calls
}
