// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package clientmocks

import (
	"context"
	"sync"

	"github.com/wso2-enterprise/agent-management-platform/agent-manager-service/clients/openchoreosvc"
	"github.com/wso2-enterprise/agent-management-platform/agent-manager-service/models"
	"github.com/wso2-enterprise/agent-management-platform/agent-manager-service/spec"
)

// OpenChoreoSvcClientMock is a mock implementation of openchoreosvc.OpenChoreoSvcClient.
//
//	func TestSomethingThatUsesOpenChoreoSvcClient(t *testing.T) {
//
//		// make and configure a mocked openchoreosvc.OpenChoreoSvcClient
//		mockedOpenChoreoSvcClient := &OpenChoreoSvcClientMock{
//			CleanupOrganizationResourcesFunc: func(ctx context.Context, orgName string) error {
//				panic("mock out the CleanupOrganizationResources method")
//			},
//			CreateAPIClassDefaultWithCORSFunc: func(ctx context.Context, orgName string, apiClassName string) error {
//				panic("mock out the CreateAPIClassDefaultWithCORS method")
//			},
//			CreateAgentComponentFunc: func(ctx context.Context, orgName string, projName string, req *spec.CreateAgentRequest) error {
//				panic("mock out the CreateAgentComponent method")
//			},
//			CreateBuildPlaneForOrganizationFunc: func(ctx context.Context, orgName string, buildPlaneName string) error {
//				panic("mock out the CreateBuildPlaneForOrganization method")
//			},
//			CreateDataPlaneForOrganizationFunc: func(ctx context.Context, orgName string, dataPlaneName string) error {
//				panic("mock out the CreateDataPlaneForOrganization method")
//			},
//			CreateDeploymentPipelineFunc: func(ctx context.Context, orgName string, pipelineName string, promotionPaths []models.PromotionPath) error {
//				panic("mock out the CreateDeploymentPipeline method")
//			},
//			CreateEnvironmentsFunc: func(ctx context.Context, orgName string, environmentName string, envDisplayName string, dataplaneName string, isProduction bool, dnsPrefix string) error {
//				panic("mock out the CreateEnvironments method")
//			},
//			CreateNamespaceForOrganizationFunc: func(ctx context.Context, orgName string) error {
//				panic("mock out the CreateNamespaceForOrganization method")
//			},
//			CreateObservabilityEnabledServiceClassForPythonFunc: func(ctx context.Context, orgName string, serviceClassName string) error {
//				panic("mock out the CreateObservabilityEnabledServiceClassForPython method")
//			},
//			CreateOrganizationFunc: func(ctx context.Context, namespaceName string, orgName string, orgDisplayName string) error {
//				panic("mock out the CreateOrganization method")
//			},
//			CreateProjectFunc: func(ctx context.Context, orgName string, projectName string, deploymentPipelineRef string, projectDisplayName string) error {
//				panic("mock out the CreateProject method")
//			},
//			DeleteAgentComponentFunc: func(ctx context.Context, orgName string, projName string, agentName string) error {
//				panic("mock out the DeleteAgentComponent method")
//			},
//			DeleteProjectFunc: func(ctx context.Context, orgName string, projectName string) error {
//				panic("mock out the DeleteProject method")
//			},
//			DeployAgentComponentFunc: func(ctx context.Context, orgName string, projName string, componentName string, language string, req *spec.DeployAgentRequest) error {
//				panic("mock out the DeployAgentComponent method")
//			},
//			DeployBuiltImageFunc: func(ctx context.Context, orgName string, projName string, componentName string, imageId string) error {
//				panic("mock out the DeployBuiltImage method")
//			},
//			GetAgentBuildFunc: func(ctx context.Context, orgName string, projName string, componentName string, buildName string) (*models.BuildDetailsResponse, error) {
//				panic("mock out the GetAgentBuild method")
//			},
//			GetAgentComponentFunc: func(ctx context.Context, orgName string, projName string, agentName string) (*openchoreosvc.AgentComponent, error) {
//				panic("mock out the GetAgentComponent method")
//			},
//			GetAgentConfigurationsFunc: func(ctx context.Context, orgName string, projectName string, agentName string, environment string) ([]models.EnvVars, error) {
//				panic("mock out the GetAgentConfigurations method")
//			},
//			GetAgentDeploymentsFunc: func(ctx context.Context, orgName string, pipelineName string, projName string, componentName string) ([]*models.DeploymentResponse, error) {
//				panic("mock out the GetAgentDeployments method")
//			},
//			GetAgentEndpointsFunc: func(ctx context.Context, orgName string, projName string, agentName string, environment string) (map[string]models.EndpointsResponse, error) {
//				panic("mock out the GetAgentEndpoints method")
//			},
//			GetDeploymentPipelineFunc: func(ctx context.Context, orgName string, deploymentPipelineName string) (*models.DeploymentPipelineResponse, error) {
//				panic("mock out the GetDeploymentPipeline method")
//			},
//			GetDeploymentPipelinesForOrganizationFunc: func(ctx context.Context, orgName string) ([]*models.DeploymentPipelineResponse, error) {
//				panic("mock out the GetDeploymentPipelinesForOrganization method")
//			},
//			GetEnvironmentFunc: func(ctx context.Context, orgName string, environmentName string) (*models.EnvironmentResponse, error) {
//				panic("mock out the GetEnvironment method")
//			},
//			GetOrgEnvironmentsFunc: func(ctx context.Context, orgName string) ([]*models.EnvironmentResponse, error) {
//				panic("mock out the GetOrgEnvironments method")
//			},
//			GetOrganizationFunc: func(ctx context.Context, orgName string) (*models.OrganizationResponse, error) {
//				panic("mock out the GetOrganization method")
//			},
//			GetProjectFunc: func(ctx context.Context, projectName string, orgName string) (*models.ProjectResponse, error) {
//				panic("mock out the GetProject method")
//			},
//			IsAgentComponentExistsFunc: func(ctx context.Context, orgName string, projName string, agentName string) (bool, error) {
//				panic("mock out the IsAgentComponentExists method")
//			},
//			ListAgentBuildsFunc: func(ctx context.Context, orgName string, projName string, componentName string) ([]*models.BuildResponse, error) {
//				panic("mock out the ListAgentBuilds method")
//			},
//			ListAgentComponentsFunc: func(ctx context.Context, orgName string, projName string) ([]*openchoreosvc.AgentComponent, error) {
//				panic("mock out the ListAgentComponents method")
//			},
//			ListOrganizationsFunc: func(ctx context.Context) ([]*models.OrganizationResponse, error) {
//				panic("mock out the ListOrganizations method")
//			},
//			ListProjectsFunc: func(ctx context.Context, orgName string) ([]*models.ProjectResponse, error) {
//				panic("mock out the ListProjects method")
//			},
//			SetupDeploymentFunc: func(ctx context.Context, orgName string, projName string, req *spec.CreateAgentRequest, envVars []spec.EnvironmentVariable) error {
//				panic("mock out the SetupDeployment method")
//			},
//			TriggerBuildFunc: func(ctx context.Context, orgName string, projName string, agentName string, commitId string) (*models.BuildResponse, error) {
//				panic("mock out the TriggerBuild method")
//			},
//		}
//
//		// use mockedOpenChoreoSvcClient in code that requires openchoreosvc.OpenChoreoSvcClient
//		// and then make assertions.
//
//	}
type OpenChoreoSvcClientMock struct {
	// CleanupOrganizationResourcesFunc mocks the CleanupOrganizationResources method.
	CleanupOrganizationResourcesFunc func(ctx context.Context, orgName string) error

	// CreateAPIClassDefaultWithCORSFunc mocks the CreateAPIClassDefaultWithCORS method.
	CreateAPIClassDefaultWithCORSFunc func(ctx context.Context, orgName string, apiClassName string) error

	// CreateAgentComponentFunc mocks the CreateAgentComponent method.
	CreateAgentComponentFunc func(ctx context.Context, orgName string, projName string, req *spec.CreateAgentRequest) error

	// CreateBuildPlaneForOrganizationFunc mocks the CreateBuildPlaneForOrganization method.
	CreateBuildPlaneForOrganizationFunc func(ctx context.Context, orgName string, buildPlaneName string) error

	// CreateDataPlaneForOrganizationFunc mocks the CreateDataPlaneForOrganization method.
	CreateDataPlaneForOrganizationFunc func(ctx context.Context, orgName string, dataPlaneName string) error

	// CreateDeploymentPipelineFunc mocks the CreateDeploymentPipeline method.
	CreateDeploymentPipelineFunc func(ctx context.Context, orgName string, pipelineName string, promotionPaths []models.PromotionPath) error

	// CreateEnvironmentsFunc mocks the CreateEnvironments method.
	CreateEnvironmentsFunc func(ctx context.Context, orgName string, environmentName string, envDisplayName string, dataplaneName string, isProduction bool, dnsPrefix string) error

	// CreateNamespaceForOrganizationFunc mocks the CreateNamespaceForOrganization method.
	CreateNamespaceForOrganizationFunc func(ctx context.Context, orgName string) error

	// CreateObservabilityEnabledServiceClassForPythonFunc mocks the CreateObservabilityEnabledServiceClassForPython method.
	CreateObservabilityEnabledServiceClassForPythonFunc func(ctx context.Context, orgName string, serviceClassName string) error

	// CreateOrganizationFunc mocks the CreateOrganization method.
	CreateOrganizationFunc func(ctx context.Context, namespaceName string, orgName string, orgDisplayName string) error

	// CreateProjectFunc mocks the CreateProject method.
	CreateProjectFunc func(ctx context.Context, orgName string, projectName string, deploymentPipelineRef string, projectDisplayName string) error

	// DeleteAgentComponentFunc mocks the DeleteAgentComponent method.
	DeleteAgentComponentFunc func(ctx context.Context, orgName string, projName string, agentName string) error

	// DeleteProjectFunc mocks the DeleteProject method.
	DeleteProjectFunc func(ctx context.Context, orgName string, projectName string) error

	// DeployAgentComponentFunc mocks the DeployAgentComponent method.
	DeployAgentComponentFunc func(ctx context.Context, orgName string, projName string, componentName string, language string, req *spec.DeployAgentRequest) error

	// DeployBuiltImageFunc mocks the DeployBuiltImage method.
	DeployBuiltImageFunc func(ctx context.Context, orgName string, projName string, componentName string, imageId string) error

	// GetAgentBuildFunc mocks the GetAgentBuild method.
	GetAgentBuildFunc func(ctx context.Context, orgName string, projName string, componentName string, buildName string) (*models.BuildDetailsResponse, error)

	// GetAgentComponentFunc mocks the GetAgentComponent method.
	GetAgentComponentFunc func(ctx context.Context, orgName string, projName string, agentName string) (*openchoreosvc.AgentComponent, error)

	// GetAgentConfigurationsFunc mocks the GetAgentConfigurations method.
	GetAgentConfigurationsFunc func(ctx context.Context, orgName string, projectName string, agentName string, environment string) ([]models.EnvVars, error)

	// GetAgentDeploymentsFunc mocks the GetAgentDeployments method.
	GetAgentDeploymentsFunc func(ctx context.Context, orgName string, pipelineName string, projName string, componentName string) ([]*models.DeploymentResponse, error)

	// GetAgentEndpointsFunc mocks the GetAgentEndpoints method.
	GetAgentEndpointsFunc func(ctx context.Context, orgName string, projName string, agentName string, environment string) (map[string]models.EndpointsResponse, error)

	// GetDeploymentPipelineFunc mocks the GetDeploymentPipeline method.
	GetDeploymentPipelineFunc func(ctx context.Context, orgName string, deploymentPipelineName string) (*models.DeploymentPipelineResponse, error)

	// GetDeploymentPipelinesForOrganizationFunc mocks the GetDeploymentPipelinesForOrganization method.
	GetDeploymentPipelinesForOrganizationFunc func(ctx context.Context, orgName string) ([]*models.DeploymentPipelineResponse, error)

	// GetEnvironmentFunc mocks the GetEnvironment method.
	GetEnvironmentFunc func(ctx context.Context, orgName string, environmentName string) (*models.EnvironmentResponse, error)

	// GetOrgEnvironmentsFunc mocks the GetOrgEnvironments method.
	GetOrgEnvironmentsFunc func(ctx context.Context, orgName string) ([]*models.EnvironmentResponse, error)

	// GetOrganizationFunc mocks the GetOrganization method.
	GetOrganizationFunc func(ctx context.Context, orgName string) (*models.OrganizationResponse, error)

	// GetProjectFunc mocks the GetProject method.
	GetProjectFunc func(ctx context.Context, projectName string, orgName string) (*models.ProjectResponse, error)

	// IsAgentComponentExistsFunc mocks the IsAgentComponentExists method.
	IsAgentComponentExistsFunc func(ctx context.Context, orgName string, projName string, agentName string) (bool, error)

	// ListAgentBuildsFunc mocks the ListAgentBuilds method.
	ListAgentBuildsFunc func(ctx context.Context, orgName string, projName string, componentName string) ([]*models.BuildResponse, error)

	// ListAgentComponentsFunc mocks the ListAgentComponents method.
	ListAgentComponentsFunc func(ctx context.Context, orgName string, projName string) ([]*openchoreosvc.AgentComponent, error)

	// ListOrganizationsFunc mocks the ListOrganizations method.
	ListOrganizationsFunc func(ctx context.Context) ([]*models.OrganizationResponse, error)

	// ListProjectsFunc mocks the ListProjects method.
	ListProjectsFunc func(ctx context.Context, orgName string) ([]*models.ProjectResponse, error)

	// SetupDeploymentFunc mocks the SetupDeployment method.
	SetupDeploymentFunc func(ctx context.Context, orgName string, projName string, req *spec.CreateAgentRequest, envVars []spec.EnvironmentVariable) error

	// TriggerBuildFunc mocks the TriggerBuild method.
	TriggerBuildFunc func(ctx context.Context, orgName string, projName string, agentName string, commitId string) (*models.BuildResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// CleanupOrganizationResources holds details about calls to the CleanupOrganizationResources method.
		CleanupOrganizationResources []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
		}
		// CreateAPIClassDefaultWithCORS holds details about calls to the CreateAPIClassDefaultWithCORS method.
		CreateAPIClassDefaultWithCORS []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ApiClassName is the apiClassName argument value.
			ApiClassName string
		}
		// CreateAgentComponent holds details about calls to the CreateAgentComponent method.
		CreateAgentComponent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjName is the projName argument value.
			ProjName string
			// Req is the req argument value.
			Req *spec.CreateAgentRequest
		}
		// CreateBuildPlaneForOrganization holds details about calls to the CreateBuildPlaneForOrganization method.
		CreateBuildPlaneForOrganization []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// BuildPlaneName is the buildPlaneName argument value.
			BuildPlaneName string
		}
		// CreateDataPlaneForOrganization holds details about calls to the CreateDataPlaneForOrganization method.
		CreateDataPlaneForOrganization []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// DataPlaneName is the dataPlaneName argument value.
			DataPlaneName string
		}
		// CreateDeploymentPipeline holds details about calls to the CreateDeploymentPipeline method.
		CreateDeploymentPipeline []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// PipelineName is the pipelineName argument value.
			PipelineName string
			// PromotionPaths is the promotionPaths argument value.
			PromotionPaths []models.PromotionPath
		}
		// CreateEnvironments holds details about calls to the CreateEnvironments method.
		CreateEnvironments []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// EnvironmentName is the environmentName argument value.
			EnvironmentName string
			// EnvDisplayName is the envDisplayName argument value.
			EnvDisplayName string
			// DataplaneName is the dataplaneName argument value.
			DataplaneName string
			// IsProduction is the isProduction argument value.
			IsProduction bool
			// DnsPrefix is the dnsPrefix argument value.
			DnsPrefix string
		}
		// CreateNamespaceForOrganization holds details about calls to the CreateNamespaceForOrganization method.
		CreateNamespaceForOrganization []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
		}
		// CreateObservabilityEnabledServiceClassForPython holds details about calls to the CreateObservabilityEnabledServiceClassForPython method.
		CreateObservabilityEnabledServiceClassForPython []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ServiceClassName is the serviceClassName argument value.
			ServiceClassName string
		}
		// CreateOrganization holds details about calls to the CreateOrganization method.
		CreateOrganization []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// NamespaceName is the namespaceName argument value.
			NamespaceName string
			// OrgName is the orgName argument value.
			OrgName string
			// OrgDisplayName is the orgDisplayName argument value.
			OrgDisplayName string
		}
		// CreateProject holds details about calls to the CreateProject method.
		CreateProject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// DeploymentPipelineRef is the deploymentPipelineRef argument value.
			DeploymentPipelineRef string
			// ProjectDisplayName is the projectDisplayName argument value.
			ProjectDisplayName string
		}
		// DeleteAgentComponent holds details about calls to the DeleteAgentComponent method.
		DeleteAgentComponent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjName is the projName argument value.
			ProjName string
			// AgentName is the agentName argument value.
			AgentName string
		}
		// DeleteProject holds details about calls to the DeleteProject method.
		DeleteProject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
		}
		// DeployAgentComponent holds details about calls to the DeployAgentComponent method.
		DeployAgentComponent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjName is the projName argument value.
			ProjName string
			// ComponentName is the componentName argument value.
			ComponentName string
			// Language is the language argument value.
			Language string
			// Req is the req argument value.
			Req *spec.DeployAgentRequest
		}
		// DeployBuiltImage holds details about calls to the DeployBuiltImage method.
		DeployBuiltImage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjName is the projName argument value.
			ProjName string
			// ComponentName is the componentName argument value.
			ComponentName string
			// ImageId is the imageId argument value.
			ImageId string
		}
		// GetAgentBuild holds details about calls to the GetAgentBuild method.
		GetAgentBuild []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjName is the projName argument value.
			ProjName string
			// ComponentName is the componentName argument value.
			ComponentName string
			// BuildName is the buildName argument value.
			BuildName string
		}
		// GetAgentComponent holds details about calls to the GetAgentComponent method.
		GetAgentComponent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjName is the projName argument value.
			ProjName string
			// AgentName is the agentName argument value.
			AgentName string
		}
		// GetAgentConfigurations holds details about calls to the GetAgentConfigurations method.
		GetAgentConfigurations []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// AgentName is the agentName argument value.
			AgentName string
			// Environment is the environment argument value.
			Environment string
		}
		// GetAgentDeployments holds details about calls to the GetAgentDeployments method.
		GetAgentDeployments []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// PipelineName is the pipelineName argument value.
			PipelineName string
			// ProjName is the projName argument value.
			ProjName string
			// ComponentName is the componentName argument value.
			ComponentName string
		}
		// GetAgentEndpoints holds details about calls to the GetAgentEndpoints method.
		GetAgentEndpoints []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjName is the projName argument value.
			ProjName string
			// AgentName is the agentName argument value.
			AgentName string
			// Environment is the environment argument value.
			Environment string
		}
		// GetDeploymentPipeline holds details about calls to the GetDeploymentPipeline method.
		GetDeploymentPipeline []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// DeploymentPipelineName is the deploymentPipelineName argument value.
			DeploymentPipelineName string
		}
		// GetDeploymentPipelinesForOrganization holds details about calls to the GetDeploymentPipelinesForOrganization method.
		GetDeploymentPipelinesForOrganization []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
		}
		// GetEnvironment holds details about calls to the GetEnvironment method.
		GetEnvironment []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// EnvironmentName is the environmentName argument value.
			EnvironmentName string
		}
		// GetOrgEnvironments holds details about calls to the GetOrgEnvironments method.
		GetOrgEnvironments []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
		}
		// GetOrganization holds details about calls to the GetOrganization method.
		GetOrganization []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
		}
		// GetProject holds details about calls to the GetProject method.
		GetProject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectName is the projectName argument value.
			ProjectName string
			// OrgName is the orgName argument value.
			OrgName string
		}
		// IsAgentComponentExists holds details about calls to the IsAgentComponentExists method.
		IsAgentComponentExists []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjName is the projName argument value.
			ProjName string
			// AgentName is the agentName argument value.
			AgentName string
		}
		// ListAgentBuilds holds details about calls to the ListAgentBuilds method.
		ListAgentBuilds []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjName is the projName argument value.
			ProjName string
			// ComponentName is the componentName argument value.
			ComponentName string
		}
		// ListAgentComponents holds details about calls to the ListAgentComponents method.
		ListAgentComponents []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjName is the projName argument value.
			ProjName string
		}
		// ListOrganizations holds details about calls to the ListOrganizations method.
		ListOrganizations []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ListProjects holds details about calls to the ListProjects method.
		ListProjects []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
		}
		// SetupDeployment holds details about calls to the SetupDeployment method.
		SetupDeployment []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjName is the projName argument value.
			ProjName string
			// Req is the req argument value.
			Req *spec.CreateAgentRequest
			// EnvVars is the envVars argument value.
			EnvVars []spec.EnvironmentVariable
		}
		// TriggerBuild holds details about calls to the TriggerBuild method.
		TriggerBuild []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjName is the projName argument value.
			ProjName string
			// AgentName is the agentName argument value.
			AgentName string
			// CommitId is the commitId argument value.
			CommitId string
		}
	}
	lockCleanupOrganizationResources                    sync.RWMutex
	lockCreateAPIClassDefaultWithCORS                   sync.RWMutex
	lockCreateAgentComponent                            sync.RWMutex
	lockCreateBuildPlaneForOrganization                 sync.RWMutex
	lockCreateDataPlaneForOrganization                  sync.RWMutex
	lockCreateDeploymentPipeline                        sync.RWMutex
	lockCreateEnvironments                              sync.RWMutex
	lockCreateNamespaceForOrganization                  sync.RWMutex
	lockCreateObservabilityEnabledServiceClassForPython sync.RWMutex
	lockCreateOrganization                              sync.RWMutex
	lockCreateProject                                   sync.RWMutex
	lockDeleteAgentComponent                            sync.RWMutex
	lockDeleteProject                                   sync.RWMutex
	lockDeployAgentComponent                            sync.RWMutex
	lockDeployBuiltImage                                sync.RWMutex
	lockGetAgentBuild                                   sync.RWMutex
	lockGetAgentComponent                               sync.RWMutex
	lockGetAgentConfigurations                          sync.RWMutex
	lockGetAgentDeployments                             sync.RWMutex
	lockGetAgentEndpoints                               sync.RWMutex
	lockGetDeploymentPipeline                           sync.RWMutex
	lockGetDeploymentPipelinesForOrganization           sync.RWMutex
	lockGetEnvironment                                  sync.RWMutex
	lockGetOrgEnvironments                              sync.RWMutex
	lockGetOrganization                                 sync.RWMutex
	lockGetProject                                      sync.RWMutex
	lockIsAgentComponentExists                          sync.RWMutex
	lockListAgentBuilds                                 sync.RWMutex
	lockListAgentComponents                             sync.RWMutex
	lockListOrganizations                               sync.RWMutex
	lockListProjects                                    sync.RWMutex
	lockSetupDeployment                                 sync.RWMutex
	lockTriggerBuild                                    sync.RWMutex
}

// CleanupOrganizationResources calls CleanupOrganizationResourcesFunc.
func (mock *OpenChoreoSvcClientMock) CleanupOrganizationResources(ctx context.Context, orgName string) error {
	if mock.CleanupOrganizationResourcesFunc == nil {
		panic("OpenChoreoSvcClientMock.CleanupOrganizationResourcesFunc: method is nil but OpenChoreoSvcClient.CleanupOrganizationResources was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OrgName string
	}{
		Ctx:     ctx,
		OrgName: orgName,
	}
	mock.lockCleanupOrganizationResources.Lock()
	mock.calls.CleanupOrganizationResources = append(mock.calls.CleanupOrganizationResources, callInfo)
	mock.lockCleanupOrganizationResources.Unlock()
	return mock.CleanupOrganizationResourcesFunc(ctx, orgName)
}

// CleanupOrganizationResourcesCalls gets all the calls that were made to CleanupOrganizationResources.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.CleanupOrganizationResourcesCalls())
func (mock *OpenChoreoSvcClientMock) CleanupOrganizationResourcesCalls() []struct {
	Ctx     context.Context
	OrgName string
} {
	var calls []struct {
		Ctx     context.Context
		OrgName string
	}
	mock.lockCleanupOrganizationResources.RLock()
	calls = mock.calls.CleanupOrganizationResources
	mock.lockCleanupOrganizationResources.RUnlock()
	return calls
}

// CreateAPIClassDefaultWithCORS calls CreateAPIClassDefaultWithCORSFunc.
func (mock *OpenChoreoSvcClientMock) CreateAPIClassDefaultWithCORS(ctx context.Context, orgName string, apiClassName string) error {
	if mock.CreateAPIClassDefaultWithCORSFunc == nil {
		panic("OpenChoreoSvcClientMock.CreateAPIClassDefaultWithCORSFunc: method is nil but OpenChoreoSvcClient.CreateAPIClassDefaultWithCORS was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		OrgName      string
		ApiClassName string
	}{
		Ctx:          ctx,
		OrgName:      orgName,
		ApiClassName: apiClassName,
	}
	mock.lockCreateAPIClassDefaultWithCORS.Lock()
	mock.calls.CreateAPIClassDefaultWithCORS = append(mock.calls.CreateAPIClassDefaultWithCORS, callInfo)
	mock.lockCreateAPIClassDefaultWithCORS.Unlock()
	return mock.CreateAPIClassDefaultWithCORSFunc(ctx, orgName, apiClassName)
}

// CreateAPIClassDefaultWithCORSCalls gets all the calls that were made to CreateAPIClassDefaultWithCORS.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.CreateAPIClassDefaultWithCORSCalls())
func (mock *OpenChoreoSvcClientMock) CreateAPIClassDefaultWithCORSCalls() []struct {
	Ctx          context.Context
	OrgName      string
	ApiClassName string
} {
	var calls []struct {
		Ctx          context.Context
		OrgName      string
		ApiClassName string
	}
	mock.lockCreateAPIClassDefaultWithCORS.RLock()
	calls = mock.calls.CreateAPIClassDefaultWithCORS
	mock.lockCreateAPIClassDefaultWithCORS.RUnlock()
	return calls
}

// CreateAgentComponent calls CreateAgentComponentFunc.
func (mock *OpenChoreoSvcClientMock) CreateAgentComponent(ctx context.Context, orgName string, projName string, req *spec.CreateAgentRequest) error {
	if mock.CreateAgentComponentFunc == nil {
		panic("OpenChoreoSvcClientMock.CreateAgentComponentFunc: method is nil but OpenChoreoSvcClient.CreateAgentComponent was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		OrgName  string
		ProjName string
		Req      *spec.CreateAgentRequest
	}{
		Ctx:      ctx,
		OrgName:  orgName,
		ProjName: projName,
		Req:      req,
	}
	mock.lockCreateAgentComponent.Lock()
	mock.calls.CreateAgentComponent = append(mock.calls.CreateAgentComponent, callInfo)
	mock.lockCreateAgentComponent.Unlock()
	return mock.CreateAgentComponentFunc(ctx, orgName, projName, req)
}

// CreateAgentComponentCalls gets all the calls that were made to CreateAgentComponent.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.CreateAgentComponentCalls())
func (mock *OpenChoreoSvcClientMock) CreateAgentComponentCalls() []struct {
	Ctx      context.Context
	OrgName  string
	ProjName string
	Req      *spec.CreateAgentRequest
} {
	var calls []struct {
		Ctx      context.Context
		OrgName  string
		ProjName string
		Req      *spec.CreateAgentRequest
	}
	mock.lockCreateAgentComponent.RLock()
	calls = mock.calls.CreateAgentComponent
	mock.lockCreateAgentComponent.RUnlock()
	return calls
}

// CreateBuildPlaneForOrganization calls CreateBuildPlaneForOrganizationFunc.
func (mock *OpenChoreoSvcClientMock) CreateBuildPlaneForOrganization(ctx context.Context, orgName string, buildPlaneName string) error {
	if mock.CreateBuildPlaneForOrganizationFunc == nil {
		panic("OpenChoreoSvcClientMock.CreateBuildPlaneForOrganizationFunc: method is nil but OpenChoreoSvcClient.CreateBuildPlaneForOrganization was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		OrgName        string
		BuildPlaneName string
	}{
		Ctx:            ctx,
		OrgName:        orgName,
		BuildPlaneName: buildPlaneName,
	}
	mock.lockCreateBuildPlaneForOrganization.Lock()
	mock.calls.CreateBuildPlaneForOrganization = append(mock.calls.CreateBuildPlaneForOrganization, callInfo)
	mock.lockCreateBuildPlaneForOrganization.Unlock()
	return mock.CreateBuildPlaneForOrganizationFunc(ctx, orgName, buildPlaneName)
}

// CreateBuildPlaneForOrganizationCalls gets all the calls that were made to CreateBuildPlaneForOrganization.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.CreateBuildPlaneForOrganizationCalls())
func (mock *OpenChoreoSvcClientMock) CreateBuildPlaneForOrganizationCalls() []struct {
	Ctx            context.Context
	OrgName        string
	BuildPlaneName string
} {
	var calls []struct {
		Ctx            context.Context
		OrgName        string
		BuildPlaneName string
	}
	mock.lockCreateBuildPlaneForOrganization.RLock()
	calls = mock.calls.CreateBuildPlaneForOrganization
	mock.lockCreateBuildPlaneForOrganization.RUnlock()
	return calls
}

// CreateDataPlaneForOrganization calls CreateDataPlaneForOrganizationFunc.
func (mock *OpenChoreoSvcClientMock) CreateDataPlaneForOrganization(ctx context.Context, orgName string, dataPlaneName string) error {
	if mock.CreateDataPlaneForOrganizationFunc == nil {
		panic("OpenChoreoSvcClientMock.CreateDataPlaneForOrganizationFunc: method is nil but OpenChoreoSvcClient.CreateDataPlaneForOrganization was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		DataPlaneName string
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		DataPlaneName: dataPlaneName,
	}
	mock.lockCreateDataPlaneForOrganization.Lock()
	mock.calls.CreateDataPlaneForOrganization = append(mock.calls.CreateDataPlaneForOrganization, callInfo)
	mock.lockCreateDataPlaneForOrganization.Unlock()
	return mock.CreateDataPlaneForOrganizationFunc(ctx, orgName, dataPlaneName)
}

// CreateDataPlaneForOrganizationCalls gets all the calls that were made to CreateDataPlaneForOrganization.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.CreateDataPlaneForOrganizationCalls())
func (mock *OpenChoreoSvcClientMock) CreateDataPlaneForOrganizationCalls() []struct {
	Ctx           context.Context
	OrgName       string
	DataPlaneName string
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		DataPlaneName string
	}
	mock.lockCreateDataPlaneForOrganization.RLock()
	calls = mock.calls.CreateDataPlaneForOrganization
	mock.lockCreateDataPlaneForOrganization.RUnlock()
	return calls
}

// CreateDeploymentPipeline calls CreateDeploymentPipelineFunc.
func (mock *OpenChoreoSvcClientMock) CreateDeploymentPipeline(ctx context.Context, orgName string, pipelineName string, promotionPaths []models.PromotionPath) error {
	if mock.CreateDeploymentPipelineFunc == nil {
		panic("OpenChoreoSvcClientMock.CreateDeploymentPipelineFunc: method is nil but OpenChoreoSvcClient.CreateDeploymentPipeline was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		OrgName        string
		PipelineName   string
		PromotionPaths []models.PromotionPath
	}{
		Ctx:            ctx,
		OrgName:        orgName,
		PipelineName:   pipelineName,
		PromotionPaths: promotionPaths,
	}
	mock.lockCreateDeploymentPipeline.Lock()
	mock.calls.CreateDeploymentPipeline = append(mock.calls.CreateDeploymentPipeline, callInfo)
	mock.lockCreateDeploymentPipeline.Unlock()
	return mock.CreateDeploymentPipelineFunc(ctx, orgName, pipelineName, promotionPaths)
}

// CreateDeploymentPipelineCalls gets all the calls that were made to CreateDeploymentPipeline.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.CreateDeploymentPipelineCalls())
func (mock *OpenChoreoSvcClientMock) CreateDeploymentPipelineCalls() []struct {
	Ctx            context.Context
	OrgName        string
	PipelineName   string
	PromotionPaths []models.PromotionPath
} {
	var calls []struct {
		Ctx            context.Context
		OrgName        string
		PipelineName   string
		PromotionPaths []models.PromotionPath
	}
	mock.lockCreateDeploymentPipeline.RLock()
	calls = mock.calls.CreateDeploymentPipeline
	mock.lockCreateDeploymentPipeline.RUnlock()
	return calls
}

// CreateEnvironments calls CreateEnvironmentsFunc.
func (mock *OpenChoreoSvcClientMock) CreateEnvironments(ctx context.Context, orgName string, environmentName string, envDisplayName string, dataplaneName string, isProduction bool, dnsPrefix string) error {
	if mock.CreateEnvironmentsFunc == nil {
		panic("OpenChoreoSvcClientMock.CreateEnvironmentsFunc: method is nil but OpenChoreoSvcClient.CreateEnvironments was just called")
	}
	callInfo := struct {
		Ctx             context.Context
		OrgName         string
		EnvironmentName string
		EnvDisplayName  string
		DataplaneName   string
		IsProduction    bool
		DnsPrefix       string
	}{
		Ctx:             ctx,
		OrgName:         orgName,
		EnvironmentName: environmentName,
		EnvDisplayName:  envDisplayName,
		DataplaneName:   dataplaneName,
		IsProduction:    isProduction,
		DnsPrefix:       dnsPrefix,
	}
	mock.lockCreateEnvironments.Lock()
	mock.calls.CreateEnvironments = append(mock.calls.CreateEnvironments, callInfo)
	mock.lockCreateEnvironments.Unlock()
	return mock.CreateEnvironmentsFunc(ctx, orgName, environmentName, envDisplayName, dataplaneName, isProduction, dnsPrefix)
}

// CreateEnvironmentsCalls gets all the calls that were made to CreateEnvironments.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.CreateEnvironmentsCalls())
func (mock *OpenChoreoSvcClientMock) CreateEnvironmentsCalls() []struct {
	Ctx             context.Context
	OrgName         string
	EnvironmentName string
	EnvDisplayName  string
	DataplaneName   string
	IsProduction    bool
	DnsPrefix       string
} {
	var calls []struct {
		Ctx             context.Context
		OrgName         string
		EnvironmentName string
		EnvDisplayName  string
		DataplaneName   string
		IsProduction    bool
		DnsPrefix       string
	}
	mock.lockCreateEnvironments.RLock()
	calls = mock.calls.CreateEnvironments
	mock.lockCreateEnvironments.RUnlock()
	return calls
}

// CreateNamespaceForOrganization calls CreateNamespaceForOrganizationFunc.
func (mock *OpenChoreoSvcClientMock) CreateNamespaceForOrganization(ctx context.Context, orgName string) error {
	if mock.CreateNamespaceForOrganizationFunc == nil {
		panic("OpenChoreoSvcClientMock.CreateNamespaceForOrganizationFunc: method is nil but OpenChoreoSvcClient.CreateNamespaceForOrganization was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OrgName string
	}{
		Ctx:     ctx,
		OrgName: orgName,
	}
	mock.lockCreateNamespaceForOrganization.Lock()
	mock.calls.CreateNamespaceForOrganization = append(mock.calls.CreateNamespaceForOrganization, callInfo)
	mock.lockCreateNamespaceForOrganization.Unlock()
	return mock.CreateNamespaceForOrganizationFunc(ctx, orgName)
}

// CreateNamespaceForOrganizationCalls gets all the calls that were made to CreateNamespaceForOrganization.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.CreateNamespaceForOrganizationCalls())
func (mock *OpenChoreoSvcClientMock) CreateNamespaceForOrganizationCalls() []struct {
	Ctx     context.Context
	OrgName string
} {
	var calls []struct {
		Ctx     context.Context
		OrgName string
	}
	mock.lockCreateNamespaceForOrganization.RLock()
	calls = mock.calls.CreateNamespaceForOrganization
	mock.lockCreateNamespaceForOrganization.RUnlock()
	return calls
}

// CreateObservabilityEnabledServiceClassForPython calls CreateObservabilityEnabledServiceClassForPythonFunc.
func (mock *OpenChoreoSvcClientMock) CreateObservabilityEnabledServiceClassForPython(ctx context.Context, orgName string, serviceClassName string) error {
	if mock.CreateObservabilityEnabledServiceClassForPythonFunc == nil {
		panic("OpenChoreoSvcClientMock.CreateObservabilityEnabledServiceClassForPythonFunc: method is nil but OpenChoreoSvcClient.CreateObservabilityEnabledServiceClassForPython was just called")
	}
	callInfo := struct {
		Ctx              context.Context
		OrgName          string
		ServiceClassName string
	}{
		Ctx:              ctx,
		OrgName:          orgName,
		ServiceClassName: serviceClassName,
	}
	mock.lockCreateObservabilityEnabledServiceClassForPython.Lock()
	mock.calls.CreateObservabilityEnabledServiceClassForPython = append(mock.calls.CreateObservabilityEnabledServiceClassForPython, callInfo)
	mock.lockCreateObservabilityEnabledServiceClassForPython.Unlock()
	return mock.CreateObservabilityEnabledServiceClassForPythonFunc(ctx, orgName, serviceClassName)
}

// CreateObservabilityEnabledServiceClassForPythonCalls gets all the calls that were made to CreateObservabilityEnabledServiceClassForPython.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.CreateObservabilityEnabledServiceClassForPythonCalls())
func (mock *OpenChoreoSvcClientMock) CreateObservabilityEnabledServiceClassForPythonCalls() []struct {
	Ctx              context.Context
	OrgName          string
	ServiceClassName string
} {
	var calls []struct {
		Ctx              context.Context
		OrgName          string
		ServiceClassName string
	}
	mock.lockCreateObservabilityEnabledServiceClassForPython.RLock()
	calls = mock.calls.CreateObservabilityEnabledServiceClassForPython
	mock.lockCreateObservabilityEnabledServiceClassForPython.RUnlock()
	return calls
}

// CreateOrganization calls CreateOrganizationFunc.
func (mock *OpenChoreoSvcClientMock) CreateOrganization(ctx context.Context, namespaceName string, orgName string, orgDisplayName string) error {
	if mock.CreateOrganizationFunc == nil {
		panic("OpenChoreoSvcClientMock.CreateOrganizationFunc: method is nil but OpenChoreoSvcClient.CreateOrganization was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		NamespaceName  string
		OrgName        string
		OrgDisplayName string
	}{
		Ctx:            ctx,
		NamespaceName:  namespaceName,
		OrgName:        orgName,
		OrgDisplayName: orgDisplayName,
	}
	mock.lockCreateOrganization.Lock()
	mock.calls.CreateOrganization = append(mock.calls.CreateOrganization, callInfo)
	mock.lockCreateOrganization.Unlock()
	return mock.CreateOrganizationFunc(ctx, namespaceName, orgName, orgDisplayName)
}

// CreateOrganizationCalls gets all the calls that were made to CreateOrganization.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.CreateOrganizationCalls())
func (mock *OpenChoreoSvcClientMock) CreateOrganizationCalls() []struct {
	Ctx            context.Context
	NamespaceName  string
	OrgName        string
	OrgDisplayName string
} {
	var calls []struct {
		Ctx            context.Context
		NamespaceName  string
		OrgName        string
		OrgDisplayName string
	}
	mock.lockCreateOrganization.RLock()
	calls = mock.calls.CreateOrganization
	mock.lockCreateOrganization.RUnlock()
	return calls
}

// CreateProject calls CreateProjectFunc.
func (mock *OpenChoreoSvcClientMock) CreateProject(ctx context.Context, orgName string, projectName string, deploymentPipelineRef string, projectDisplayName string) error {
	if mock.CreateProjectFunc == nil {
		panic("OpenChoreoSvcClientMock.CreateProjectFunc: method is nil but OpenChoreoSvcClient.CreateProject was just called")
	}
	callInfo := struct {
		Ctx                   context.Context
		OrgName               string
		ProjectName           string
		DeploymentPipelineRef string
		ProjectDisplayName    string
	}{
		Ctx:                   ctx,
		OrgName:               orgName,
		ProjectName:           projectName,
		DeploymentPipelineRef: deploymentPipelineRef,
		ProjectDisplayName:    projectDisplayName,
	}
	mock.lockCreateProject.Lock()
	mock.calls.CreateProject = append(mock.calls.CreateProject, callInfo)
	mock.lockCreateProject.Unlock()
	return mock.CreateProjectFunc(ctx, orgName, projectName, deploymentPipelineRef, projectDisplayName)
}

// CreateProjectCalls gets all the calls that were made to CreateProject.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.CreateProjectCalls())
func (mock *OpenChoreoSvcClientMock) CreateProjectCalls() []struct {
	Ctx                   context.Context
	OrgName               string
	ProjectName           string
	DeploymentPipelineRef string
	ProjectDisplayName    string
} {
	var calls []struct {
		Ctx                   context.Context
		OrgName               string
		ProjectName           string
		DeploymentPipelineRef string
		ProjectDisplayName    string
	}
	mock.lockCreateProject.RLock()
	calls = mock.calls.CreateProject
	mock.lockCreateProject.RUnlock()
	return calls
}

// DeleteAgentComponent calls DeleteAgentComponentFunc.
func (mock *OpenChoreoSvcClientMock) DeleteAgentComponent(ctx context.Context, orgName string, projName string, agentName string) error {
	if mock.DeleteAgentComponentFunc == nil {
		panic("OpenChoreoSvcClientMock.DeleteAgentComponentFunc: method is nil but OpenChoreoSvcClient.DeleteAgentComponent was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		OrgName   string
		ProjName  string
		AgentName string
	}{
		Ctx:       ctx,
		OrgName:   orgName,
		ProjName:  projName,
		AgentName: agentName,
	}
	mock.lockDeleteAgentComponent.Lock()
	mock.calls.DeleteAgentComponent = append(mock.calls.DeleteAgentComponent, callInfo)
	mock.lockDeleteAgentComponent.Unlock()
	return mock.DeleteAgentComponentFunc(ctx, orgName, projName, agentName)
}

// DeleteAgentComponentCalls gets all the calls that were made to DeleteAgentComponent.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.DeleteAgentComponentCalls())
func (mock *OpenChoreoSvcClientMock) DeleteAgentComponentCalls() []struct {
	Ctx       context.Context
	OrgName   string
	ProjName  string
	AgentName string
} {
	var calls []struct {
		Ctx       context.Context
		OrgName   string
		ProjName  string
		AgentName string
	}
	mock.lockDeleteAgentComponent.RLock()
	calls = mock.calls.DeleteAgentComponent
	mock.lockDeleteAgentComponent.RUnlock()
	return calls
}

// DeleteProject calls DeleteProjectFunc.
func (mock *OpenChoreoSvcClientMock) DeleteProject(ctx context.Context, orgName string, projectName string) error {
	if mock.DeleteProjectFunc == nil {
		panic("OpenChoreoSvcClientMock.DeleteProjectFunc: method is nil but OpenChoreoSvcClient.DeleteProject was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
	}{
		Ctx:         ctx,
		OrgName:     orgName,
		ProjectName: projectName,
	}
	mock.lockDeleteProject.Lock()
	mock.calls.DeleteProject = append(mock.calls.DeleteProject, callInfo)
	mock.lockDeleteProject.Unlock()
	return mock.DeleteProjectFunc(ctx, orgName, projectName)
}

// DeleteProjectCalls gets all the calls that were made to DeleteProject.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.DeleteProjectCalls())
func (mock *OpenChoreoSvcClientMock) DeleteProjectCalls() []struct {
	Ctx         context.Context
	OrgName     string
	ProjectName string
} {
	var calls []struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
	}
	mock.lockDeleteProject.RLock()
	calls = mock.calls.DeleteProject
	mock.lockDeleteProject.RUnlock()
	return calls
}

// DeployAgentComponent calls DeployAgentComponentFunc.
func (mock *OpenChoreoSvcClientMock) DeployAgentComponent(ctx context.Context, orgName string, projName string, componentName string, language string, req *spec.DeployAgentRequest) error {
	if mock.DeployAgentComponentFunc == nil {
		panic("OpenChoreoSvcClientMock.DeployAgentComponentFunc: method is nil but OpenChoreoSvcClient.DeployAgentComponent was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		ProjName      string
		ComponentName string
		Language      string
		Req           *spec.DeployAgentRequest
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		ProjName:      projName,
		ComponentName: componentName,
		Language:      language,
		Req:           req,
	}
	mock.lockDeployAgentComponent.Lock()
	mock.calls.DeployAgentComponent = append(mock.calls.DeployAgentComponent, callInfo)
	mock.lockDeployAgentComponent.Unlock()
	return mock.DeployAgentComponentFunc(ctx, orgName, projName, componentName, language, req)
}

// DeployAgentComponentCalls gets all the calls that were made to DeployAgentComponent.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.DeployAgentComponentCalls())
func (mock *OpenChoreoSvcClientMock) DeployAgentComponentCalls() []struct {
	Ctx           context.Context
	OrgName       string
	ProjName      string
	ComponentName string
	Language      string
	Req           *spec.DeployAgentRequest
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		ProjName      string
		ComponentName string
		Language      string
		Req           *spec.DeployAgentRequest
	}
	mock.lockDeployAgentComponent.RLock()
	calls = mock.calls.DeployAgentComponent
	mock.lockDeployAgentComponent.RUnlock()
	return calls
}

// DeployBuiltImage calls DeployBuiltImageFunc.
func (mock *OpenChoreoSvcClientMock) DeployBuiltImage(ctx context.Context, orgName string, projName string, componentName string, imageId string) error {
	if mock.DeployBuiltImageFunc == nil {
		panic("OpenChoreoSvcClientMock.DeployBuiltImageFunc: method is nil but OpenChoreoSvcClient.DeployBuiltImage was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		ProjName      string
		ComponentName string
		ImageId       string
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		ProjName:      projName,
		ComponentName: componentName,
		ImageId:       imageId,
	}
	mock.lockDeployBuiltImage.Lock()
	mock.calls.DeployBuiltImage = append(mock.calls.DeployBuiltImage, callInfo)
	mock.lockDeployBuiltImage.Unlock()
	return mock.DeployBuiltImageFunc(ctx, orgName, projName, componentName, imageId)
}

// DeployBuiltImageCalls gets all the calls that were made to DeployBuiltImage.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.DeployBuiltImageCalls())
func (mock *OpenChoreoSvcClientMock) DeployBuiltImageCalls() []struct {
	Ctx           context.Context
	OrgName       string
	ProjName      string
	ComponentName string
	ImageId       string
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		ProjName      string
		ComponentName string
		ImageId       string
	}
	mock.lockDeployBuiltImage.RLock()
	calls = mock.calls.DeployBuiltImage
	mock.lockDeployBuiltImage.RUnlock()
	return calls
}

// GetAgentBuild calls GetAgentBuildFunc.
func (mock *OpenChoreoSvcClientMock) GetAgentBuild(ctx context.Context, orgName string, projName string, componentName string, buildName string) (*models.BuildDetailsResponse, error) {
	if mock.GetAgentBuildFunc == nil {
		panic("OpenChoreoSvcClientMock.GetAgentBuildFunc: method is nil but OpenChoreoSvcClient.GetAgentBuild was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		ProjName      string
		ComponentName string
		BuildName     string
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		ProjName:      projName,
		ComponentName: componentName,
		BuildName:     buildName,
	}
	mock.lockGetAgentBuild.Lock()
	mock.calls.GetAgentBuild = append(mock.calls.GetAgentBuild, callInfo)
	mock.lockGetAgentBuild.Unlock()
	return mock.GetAgentBuildFunc(ctx, orgName, projName, componentName, buildName)
}

// GetAgentBuildCalls gets all the calls that were made to GetAgentBuild.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.GetAgentBuildCalls())
func (mock *OpenChoreoSvcClientMock) GetAgentBuildCalls() []struct {
	Ctx           context.Context
	OrgName       string
	ProjName      string
	ComponentName string
	BuildName     string
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		ProjName      string
		ComponentName string
		BuildName     string
	}
	mock.lockGetAgentBuild.RLock()
	calls = mock.calls.GetAgentBuild
	mock.lockGetAgentBuild.RUnlock()
	return calls
}

// GetAgentComponent calls GetAgentComponentFunc.
func (mock *OpenChoreoSvcClientMock) GetAgentComponent(ctx context.Context, orgName string, projName string, agentName string) (*openchoreosvc.AgentComponent, error) {
	if mock.GetAgentComponentFunc == nil {
		panic("OpenChoreoSvcClientMock.GetAgentComponentFunc: method is nil but OpenChoreoSvcClient.GetAgentComponent was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		OrgName   string
		ProjName  string
		AgentName string
	}{
		Ctx:       ctx,
		OrgName:   orgName,
		ProjName:  projName,
		AgentName: agentName,
	}
	mock.lockGetAgentComponent.Lock()
	mock.calls.GetAgentComponent = append(mock.calls.GetAgentComponent, callInfo)
	mock.lockGetAgentComponent.Unlock()
	return mock.GetAgentComponentFunc(ctx, orgName, projName, agentName)
}

// GetAgentComponentCalls gets all the calls that were made to GetAgentComponent.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.GetAgentComponentCalls())
func (mock *OpenChoreoSvcClientMock) GetAgentComponentCalls() []struct {
	Ctx       context.Context
	OrgName   string
	ProjName  string
	AgentName string
} {
	var calls []struct {
		Ctx       context.Context
		OrgName   string
		ProjName  string
		AgentName string
	}
	mock.lockGetAgentComponent.RLock()
	calls = mock.calls.GetAgentComponent
	mock.lockGetAgentComponent.RUnlock()
	return calls
}

// GetAgentConfigurations calls GetAgentConfigurationsFunc.
func (mock *OpenChoreoSvcClientMock) GetAgentConfigurations(ctx context.Context, orgName string, projectName string, agentName string, environment string) ([]models.EnvVars, error) {
	if mock.GetAgentConfigurationsFunc == nil {
		panic("OpenChoreoSvcClientMock.GetAgentConfigurationsFunc: method is nil but OpenChoreoSvcClient.GetAgentConfigurations was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		AgentName   string
		Environment string
	}{
		Ctx:         ctx,
		OrgName:     orgName,
		ProjectName: projectName,
		AgentName:   agentName,
		Environment: environment,
	}
	mock.lockGetAgentConfigurations.Lock()
	mock.calls.GetAgentConfigurations = append(mock.calls.GetAgentConfigurations, callInfo)
	mock.lockGetAgentConfigurations.Unlock()
	return mock.GetAgentConfigurationsFunc(ctx, orgName, projectName, agentName, environment)
}

// GetAgentConfigurationsCalls gets all the calls that were made to GetAgentConfigurations.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.GetAgentConfigurationsCalls())
func (mock *OpenChoreoSvcClientMock) GetAgentConfigurationsCalls() []struct {
	Ctx         context.Context
	OrgName     string
	ProjectName string
	AgentName   string
	Environment string
} {
	var calls []struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		AgentName   string
		Environment string
	}
	mock.lockGetAgentConfigurations.RLock()
	calls = mock.calls.GetAgentConfigurations
	mock.lockGetAgentConfigurations.RUnlock()
	return calls
}

// GetAgentDeployments calls GetAgentDeploymentsFunc.
func (mock *OpenChoreoSvcClientMock) GetAgentDeployments(ctx context.Context, orgName string, pipelineName string, projName string, componentName string) ([]*models.DeploymentResponse, error) {
	if mock.GetAgentDeploymentsFunc == nil {
		panic("OpenChoreoSvcClientMock.GetAgentDeploymentsFunc: method is nil but OpenChoreoSvcClient.GetAgentDeployments was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		PipelineName  string
		ProjName      string
		ComponentName string
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		PipelineName:  pipelineName,
		ProjName:      projName,
		ComponentName: componentName,
	}
	mock.lockGetAgentDeployments.Lock()
	mock.calls.GetAgentDeployments = append(mock.calls.GetAgentDeployments, callInfo)
	mock.lockGetAgentDeployments.Unlock()
	return mock.GetAgentDeploymentsFunc(ctx, orgName, pipelineName, projName, componentName)
}

// GetAgentDeploymentsCalls gets all the calls that were made to GetAgentDeployments.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.GetAgentDeploymentsCalls())
func (mock *OpenChoreoSvcClientMock) GetAgentDeploymentsCalls() []struct {
	Ctx           context.Context
	OrgName       string
	PipelineName  string
	ProjName      string
	ComponentName string
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		PipelineName  string
		ProjName      string
		ComponentName string
	}
	mock.lockGetAgentDeployments.RLock()
	calls = mock.calls.GetAgentDeployments
	mock.lockGetAgentDeployments.RUnlock()
	return calls
}

// GetAgentEndpoints calls GetAgentEndpointsFunc.
func (mock *OpenChoreoSvcClientMock) GetAgentEndpoints(ctx context.Context, orgName string, projName string, agentName string, environment string) (map[string]models.EndpointsResponse, error) {
	if mock.GetAgentEndpointsFunc == nil {
		panic("OpenChoreoSvcClientMock.GetAgentEndpointsFunc: method is nil but OpenChoreoSvcClient.GetAgentEndpoints was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		OrgName     string
		ProjName    string
		AgentName   string
		Environment string
	}{
		Ctx:         ctx,
		OrgName:     orgName,
		ProjName:    projName,
		AgentName:   agentName,
		Environment: environment,
	}
	mock.lockGetAgentEndpoints.Lock()
	mock.calls.GetAgentEndpoints = append(mock.calls.GetAgentEndpoints, callInfo)
	mock.lockGetAgentEndpoints.Unlock()
	return mock.GetAgentEndpointsFunc(ctx, orgName, projName, agentName, environment)
}

// GetAgentEndpointsCalls gets all the calls that were made to GetAgentEndpoints.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.GetAgentEndpointsCalls())
func (mock *OpenChoreoSvcClientMock) GetAgentEndpointsCalls() []struct {
	Ctx         context.Context
	OrgName     string
	ProjName    string
	AgentName   string
	Environment string
} {
	var calls []struct {
		Ctx         context.Context
		OrgName     string
		ProjName    string
		AgentName   string
		Environment string
	}
	mock.lockGetAgentEndpoints.RLock()
	calls = mock.calls.GetAgentEndpoints
	mock.lockGetAgentEndpoints.RUnlock()
	return calls
}

// GetDeploymentPipeline calls GetDeploymentPipelineFunc.
func (mock *OpenChoreoSvcClientMock) GetDeploymentPipeline(ctx context.Context, orgName string, deploymentPipelineName string) (*models.DeploymentPipelineResponse, error) {
	if mock.GetDeploymentPipelineFunc == nil {
		panic("OpenChoreoSvcClientMock.GetDeploymentPipelineFunc: method is nil but OpenChoreoSvcClient.GetDeploymentPipeline was just called")
	}
	callInfo := struct {
		Ctx                    context.Context
		OrgName                string
		DeploymentPipelineName string
	}{
		Ctx:                    ctx,
		OrgName:                orgName,
		DeploymentPipelineName: deploymentPipelineName,
	}
	mock.lockGetDeploymentPipeline.Lock()
	mock.calls.GetDeploymentPipeline = append(mock.calls.GetDeploymentPipeline, callInfo)
	mock.lockGetDeploymentPipeline.Unlock()
	return mock.GetDeploymentPipelineFunc(ctx, orgName, deploymentPipelineName)
}

// GetDeploymentPipelineCalls gets all the calls that were made to GetDeploymentPipeline.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.GetDeploymentPipelineCalls())
func (mock *OpenChoreoSvcClientMock) GetDeploymentPipelineCalls() []struct {
	Ctx                    context.Context
	OrgName                string
	DeploymentPipelineName string
} {
	var calls []struct {
		Ctx                    context.Context
		OrgName                string
		DeploymentPipelineName string
	}
	mock.lockGetDeploymentPipeline.RLock()
	calls = mock.calls.GetDeploymentPipeline
	mock.lockGetDeploymentPipeline.RUnlock()
	return calls
}

// GetDeploymentPipelinesForOrganization calls GetDeploymentPipelinesForOrganizationFunc.
func (mock *OpenChoreoSvcClientMock) GetDeploymentPipelinesForOrganization(ctx context.Context, orgName string) ([]*models.DeploymentPipelineResponse, error) {
	if mock.GetDeploymentPipelinesForOrganizationFunc == nil {
		panic("OpenChoreoSvcClientMock.GetDeploymentPipelinesForOrganizationFunc: method is nil but OpenChoreoSvcClient.GetDeploymentPipelinesForOrganization was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OrgName string
	}{
		Ctx:     ctx,
		OrgName: orgName,
	}
	mock.lockGetDeploymentPipelinesForOrganization.Lock()
	mock.calls.GetDeploymentPipelinesForOrganization = append(mock.calls.GetDeploymentPipelinesForOrganization, callInfo)
	mock.lockGetDeploymentPipelinesForOrganization.Unlock()
	return mock.GetDeploymentPipelinesForOrganizationFunc(ctx, orgName)
}

// GetDeploymentPipelinesForOrganizationCalls gets all the calls that were made to GetDeploymentPipelinesForOrganization.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.GetDeploymentPipelinesForOrganizationCalls())
func (mock *OpenChoreoSvcClientMock) GetDeploymentPipelinesForOrganizationCalls() []struct {
	Ctx     context.Context
	OrgName string
} {
	var calls []struct {
		Ctx     context.Context
		OrgName string
	}
	mock.lockGetDeploymentPipelinesForOrganization.RLock()
	calls = mock.calls.GetDeploymentPipelinesForOrganization
	mock.lockGetDeploymentPipelinesForOrganization.RUnlock()
	return calls
}

// GetEnvironment calls GetEnvironmentFunc.
func (mock *OpenChoreoSvcClientMock) GetEnvironment(ctx context.Context, orgName string, environmentName string) (*models.EnvironmentResponse, error) {
	if mock.GetEnvironmentFunc == nil {
		panic("OpenChoreoSvcClientMock.GetEnvironmentFunc: method is nil but OpenChoreoSvcClient.GetEnvironment was just called")
	}
	callInfo := struct {
		Ctx             context.Context
		OrgName         string
		EnvironmentName string
	}{
		Ctx:             ctx,
		OrgName:         orgName,
		EnvironmentName: environmentName,
	}
	mock.lockGetEnvironment.Lock()
	mock.calls.GetEnvironment = append(mock.calls.GetEnvironment, callInfo)
	mock.lockGetEnvironment.Unlock()
	return mock.GetEnvironmentFunc(ctx, orgName, environmentName)
}

// GetEnvironmentCalls gets all the calls that were made to GetEnvironment.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.GetEnvironmentCalls())
func (mock *OpenChoreoSvcClientMock) GetEnvironmentCalls() []struct {
	Ctx             context.Context
	OrgName         string
	EnvironmentName string
} {
	var calls []struct {
		Ctx             context.Context
		OrgName         string
		EnvironmentName string
	}
	mock.lockGetEnvironment.RLock()
	calls = mock.calls.GetEnvironment
	mock.lockGetEnvironment.RUnlock()
	return calls
}

// GetOrgEnvironments calls GetOrgEnvironmentsFunc.
func (mock *OpenChoreoSvcClientMock) GetOrgEnvironments(ctx context.Context, orgName string) ([]*models.EnvironmentResponse, error) {
	if mock.GetOrgEnvironmentsFunc == nil {
		panic("OpenChoreoSvcClientMock.GetOrgEnvironmentsFunc: method is nil but OpenChoreoSvcClient.GetOrgEnvironments was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OrgName string
	}{
		Ctx:     ctx,
		OrgName: orgName,
	}
	mock.lockGetOrgEnvironments.Lock()
	mock.calls.GetOrgEnvironments = append(mock.calls.GetOrgEnvironments, callInfo)
	mock.lockGetOrgEnvironments.Unlock()
	return mock.GetOrgEnvironmentsFunc(ctx, orgName)
}

// GetOrgEnvironmentsCalls gets all the calls that were made to GetOrgEnvironments.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.GetOrgEnvironmentsCalls())
func (mock *OpenChoreoSvcClientMock) GetOrgEnvironmentsCalls() []struct {
	Ctx     context.Context
	OrgName string
} {
	var calls []struct {
		Ctx     context.Context
		OrgName string
	}
	mock.lockGetOrgEnvironments.RLock()
	calls = mock.calls.GetOrgEnvironments
	mock.lockGetOrgEnvironments.RUnlock()
	return calls
}

// GetOrganization calls GetOrganizationFunc.
func (mock *OpenChoreoSvcClientMock) GetOrganization(ctx context.Context, orgName string) (*models.OrganizationResponse, error) {
	if mock.GetOrganizationFunc == nil {
		panic("OpenChoreoSvcClientMock.GetOrganizationFunc: method is nil but OpenChoreoSvcClient.GetOrganization was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OrgName string
	}{
		Ctx:     ctx,
		OrgName: orgName,
	}
	mock.lockGetOrganization.Lock()
	mock.calls.GetOrganization = append(mock.calls.GetOrganization, callInfo)
	mock.lockGetOrganization.Unlock()
	return mock.GetOrganizationFunc(ctx, orgName)
}

// GetOrganizationCalls gets all the calls that were made to GetOrganization.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.GetOrganizationCalls())
func (mock *OpenChoreoSvcClientMock) GetOrganizationCalls() []struct {
	Ctx     context.Context
	OrgName string
} {
	var calls []struct {
		Ctx     context.Context
		OrgName string
	}
	mock.lockGetOrganization.RLock()
	calls = mock.calls.GetOrganization
	mock.lockGetOrganization.RUnlock()
	return calls
}

// GetProject calls GetProjectFunc.
func (mock *OpenChoreoSvcClientMock) GetProject(ctx context.Context, projectName string, orgName string) (*models.ProjectResponse, error) {
	if mock.GetProjectFunc == nil {
		panic("OpenChoreoSvcClientMock.GetProjectFunc: method is nil but OpenChoreoSvcClient.GetProject was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		ProjectName string
		OrgName     string
	}{
		Ctx:         ctx,
		ProjectName: projectName,
		OrgName:     orgName,
	}
	mock.lockGetProject.Lock()
	mock.calls.GetProject = append(mock.calls.GetProject, callInfo)
	mock.lockGetProject.Unlock()
	return mock.GetProjectFunc(ctx, projectName, orgName)
}

// GetProjectCalls gets all the calls that were made to GetProject.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.GetProjectCalls())
func (mock *OpenChoreoSvcClientMock) GetProjectCalls() []struct {
	Ctx         context.Context
	ProjectName string
	OrgName     string
} {
	var calls []struct {
		Ctx         context.Context
		ProjectName string
		OrgName     string
	}
	mock.lockGetProject.RLock()
	calls = mock.calls.GetProject
	mock.lockGetProject.RUnlock()
	return calls
}

// IsAgentComponentExists calls IsAgentComponentExistsFunc.
func (mock *OpenChoreoSvcClientMock) IsAgentComponentExists(ctx context.Context, orgName string, projName string, agentName string) (bool, error) {
	if mock.IsAgentComponentExistsFunc == nil {
		panic("OpenChoreoSvcClientMock.IsAgentComponentExistsFunc: method is nil but OpenChoreoSvcClient.IsAgentComponentExists was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		OrgName   string
		ProjName  string
		AgentName string
	}{
		Ctx:       ctx,
		OrgName:   orgName,
		ProjName:  projName,
		AgentName: agentName,
	}
	mock.lockIsAgentComponentExists.Lock()
	mock.calls.IsAgentComponentExists = append(mock.calls.IsAgentComponentExists, callInfo)
	mock.lockIsAgentComponentExists.Unlock()
	return mock.IsAgentComponentExistsFunc(ctx, orgName, projName, agentName)
}

// IsAgentComponentExistsCalls gets all the calls that were made to IsAgentComponentExists.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.IsAgentComponentExistsCalls())
func (mock *OpenChoreoSvcClientMock) IsAgentComponentExistsCalls() []struct {
	Ctx       context.Context
	OrgName   string
	ProjName  string
	AgentName string
} {
	var calls []struct {
		Ctx       context.Context
		OrgName   string
		ProjName  string
		AgentName string
	}
	mock.lockIsAgentComponentExists.RLock()
	calls = mock.calls.IsAgentComponentExists
	mock.lockIsAgentComponentExists.RUnlock()
	return calls
}

// ListAgentBuilds calls ListAgentBuildsFunc.
func (mock *OpenChoreoSvcClientMock) ListAgentBuilds(ctx context.Context, orgName string, projName string, componentName string) ([]*models.BuildResponse, error) {
	if mock.ListAgentBuildsFunc == nil {
		panic("OpenChoreoSvcClientMock.ListAgentBuildsFunc: method is nil but OpenChoreoSvcClient.ListAgentBuilds was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		ProjName      string
		ComponentName string
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		ProjName:      projName,
		ComponentName: componentName,
	}
	mock.lockListAgentBuilds.Lock()
	mock.calls.ListAgentBuilds = append(mock.calls.ListAgentBuilds, callInfo)
	mock.lockListAgentBuilds.Unlock()
	return mock.ListAgentBuildsFunc(ctx, orgName, projName, componentName)
}

// ListAgentBuildsCalls gets all the calls that were made to ListAgentBuilds.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.ListAgentBuildsCalls())
func (mock *OpenChoreoSvcClientMock) ListAgentBuildsCalls() []struct {
	Ctx           context.Context
	OrgName       string
	ProjName      string
	ComponentName string
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		ProjName      string
		ComponentName string
	}
	mock.lockListAgentBuilds.RLock()
	calls = mock.calls.ListAgentBuilds
	mock.lockListAgentBuilds.RUnlock()
	return calls
}

// ListAgentComponents calls ListAgentComponentsFunc.
func (mock *OpenChoreoSvcClientMock) ListAgentComponents(ctx context.Context, orgName string, projName string) ([]*openchoreosvc.AgentComponent, error) {
	if mock.ListAgentComponentsFunc == nil {
		panic("OpenChoreoSvcClientMock.ListAgentComponentsFunc: method is nil but OpenChoreoSvcClient.ListAgentComponents was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		OrgName  string
		ProjName string
	}{
		Ctx:      ctx,
		OrgName:  orgName,
		ProjName: projName,
	}
	mock.lockListAgentComponents.Lock()
	mock.calls.ListAgentComponents = append(mock.calls.ListAgentComponents, callInfo)
	mock.lockListAgentComponents.Unlock()
	return mock.ListAgentComponentsFunc(ctx, orgName, projName)
}

// ListAgentComponentsCalls gets all the calls that were made to ListAgentComponents.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.ListAgentComponentsCalls())
func (mock *OpenChoreoSvcClientMock) ListAgentComponentsCalls() []struct {
	Ctx      context.Context
	OrgName  string
	ProjName string
} {
	var calls []struct {
		Ctx      context.Context
		OrgName  string
		ProjName string
	}
	mock.lockListAgentComponents.RLock()
	calls = mock.calls.ListAgentComponents
	mock.lockListAgentComponents.RUnlock()
	return calls
}

// ListOrganizations calls ListOrganizationsFunc.
func (mock *OpenChoreoSvcClientMock) ListOrganizations(ctx context.Context) ([]*models.OrganizationResponse, error) {
	if mock.ListOrganizationsFunc == nil {
		panic("OpenChoreoSvcClientMock.ListOrganizationsFunc: method is nil but OpenChoreoSvcClient.ListOrganizations was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListOrganizations.Lock()
	mock.calls.ListOrganizations = append(mock.calls.ListOrganizations, callInfo)
	mock.lockListOrganizations.Unlock()
	return mock.ListOrganizationsFunc(ctx)
}

// ListOrganizationsCalls gets all the calls that were made to ListOrganizations.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.ListOrganizationsCalls())
func (mock *OpenChoreoSvcClientMock) ListOrganizationsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListOrganizations.RLock()
	calls = mock.calls.ListOrganizations
	mock.lockListOrganizations.RUnlock()
	return calls
}

// ListProjects calls ListProjectsFunc.
func (mock *OpenChoreoSvcClientMock) ListProjects(ctx context.Context, orgName string) ([]*models.ProjectResponse, error) {
	if mock.ListProjectsFunc == nil {
		panic("OpenChoreoSvcClientMock.ListProjectsFunc: method is nil but OpenChoreoSvcClient.ListProjects was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OrgName string
	}{
		Ctx:     ctx,
		OrgName: orgName,
	}
	mock.lockListProjects.Lock()
	mock.calls.ListProjects = append(mock.calls.ListProjects, callInfo)
	mock.lockListProjects.Unlock()
	return mock.ListProjectsFunc(ctx, orgName)
}

// ListProjectsCalls gets all the calls that were made to ListProjects.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.ListProjectsCalls())
func (mock *OpenChoreoSvcClientMock) ListProjectsCalls() []struct {
	Ctx     context.Context
	OrgName string
} {
	var calls []struct {
		Ctx     context.Context
		OrgName string
	}
	mock.lockListProjects.RLock()
	calls = mock.calls.ListProjects
	mock.lockListProjects.RUnlock()
	return calls
}

// SetupDeployment calls SetupDeploymentFunc.
func (mock *OpenChoreoSvcClientMock) SetupDeployment(ctx context.Context, orgName string, projName string, req *spec.CreateAgentRequest, envVars []spec.EnvironmentVariable) error {
	if mock.SetupDeploymentFunc == nil {
		panic("OpenChoreoSvcClientMock.SetupDeploymentFunc: method is nil but OpenChoreoSvcClient.SetupDeployment was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		OrgName  string
		ProjName string
		Req      *spec.CreateAgentRequest
		EnvVars  []spec.EnvironmentVariable
	}{
		Ctx:      ctx,
		OrgName:  orgName,
		ProjName: projName,
		Req:      req,
		EnvVars:  envVars,
	}
	mock.lockSetupDeployment.Lock()
	mock.calls.SetupDeployment = append(mock.calls.SetupDeployment, callInfo)
	mock.lockSetupDeployment.Unlock()
	return mock.SetupDeploymentFunc(ctx, orgName, projName, req, envVars)
}

// SetupDeploymentCalls gets all the calls that were made to SetupDeployment.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.SetupDeploymentCalls())
func (mock *OpenChoreoSvcClientMock) SetupDeploymentCalls() []struct {
	Ctx      context.Context
	OrgName  string
	ProjName string
	Req      *spec.CreateAgentRequest
	EnvVars  []spec.EnvironmentVariable
} {
	var calls []struct {
		Ctx      context.Context
		OrgName  string
		ProjName string
		Req      *spec.CreateAgentRequest
		EnvVars  []spec.EnvironmentVariable
	}
	mock.lockSetupDeployment.RLock()
	calls = mock.calls.SetupDeployment
	mock.lockSetupDeployment.RUnlock()
	return calls
}

// TriggerBuild calls TriggerBuildFunc.
func (mock *OpenChoreoSvcClientMock) TriggerBuild(ctx context.Context, orgName string, projName string, agentName string, commitId string) (*models.BuildResponse, error) {
	if mock.TriggerBuildFunc == nil {
		panic("OpenChoreoSvcClientMock.TriggerBuildFunc: method is nil but OpenChoreoSvcClient.TriggerBuild was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		OrgName   string
		ProjName  string
		AgentName string
		CommitId  string
	}{
		Ctx:       ctx,
		OrgName:   orgName,
		ProjName:  projName,
		AgentName: agentName,
		CommitId:  commitId,
	}
	mock.lockTriggerBuild.Lock()
	mock.calls.TriggerBuild = append(mock.calls.TriggerBuild, callInfo)
	mock.lockTriggerBuild.Unlock()
	return mock.TriggerBuildFunc(ctx, orgName, projName, agentName, commitId)
}

// TriggerBuildCalls gets all the calls that were made to TriggerBuild.
// Check the length with:
//
//	len(mockedOpenChoreoSvcClient.TriggerBuildCalls())
func (mock *OpenChoreoSvcClientMock) TriggerBuildCalls() []struct {
	Ctx       context.Context
	OrgName   string
	ProjName  string
	AgentName string
	CommitId  string
} {
	var calls []struct {
		Ctx       context.Context
		OrgName   string
		ProjName  string
		AgentName string
		CommitId  string
	}
	mock.lockTriggerBuild.RLock()
	calls = mock.calls.TriggerBuild
	mock.lockTriggerBuild.RUnlock()
	return calls
}
