/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the InputInterface type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InputInterface{}

// InputInterface Endpoint configurations
type InputInterface struct {
	// Type of input interface (e.g., default, custom)
	Type              string        `json:"type"`
	CustomOpenAPISpec *EndpointSpec `json:"customOpenAPISpec,omitempty"`
}

// NewInputInterface instantiates a new InputInterface object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInputInterface(type_ string) *InputInterface {
	this := InputInterface{}
	this.Type = type_
	return &this
}

// NewInputInterfaceWithDefaults instantiates a new InputInterface object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInputInterfaceWithDefaults() *InputInterface {
	this := InputInterface{}
	return &this
}

// GetType returns the Type field value
func (o *InputInterface) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *InputInterface) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *InputInterface) SetType(v string) {
	o.Type = v
}

// GetCustomOpenAPISpec returns the CustomOpenAPISpec field value if set, zero value otherwise.
func (o *InputInterface) GetCustomOpenAPISpec() EndpointSpec {
	if o == nil || IsNil(o.CustomOpenAPISpec) {
		var ret EndpointSpec
		return ret
	}
	return *o.CustomOpenAPISpec
}

// GetCustomOpenAPISpecOk returns a tuple with the CustomOpenAPISpec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputInterface) GetCustomOpenAPISpecOk() (*EndpointSpec, bool) {
	if o == nil || IsNil(o.CustomOpenAPISpec) {
		return nil, false
	}
	return o.CustomOpenAPISpec, true
}

// HasCustomOpenAPISpec returns a boolean if a field has been set.
func (o *InputInterface) HasCustomOpenAPISpec() bool {
	if o != nil && !IsNil(o.CustomOpenAPISpec) {
		return true
	}

	return false
}

// SetCustomOpenAPISpec gets a reference to the given EndpointSpec and assigns it to the CustomOpenAPISpec field.
func (o *InputInterface) SetCustomOpenAPISpec(v EndpointSpec) {
	o.CustomOpenAPISpec = &v
}

func (o InputInterface) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InputInterface) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.CustomOpenAPISpec) {
		toSerialize["customOpenAPISpec"] = o.CustomOpenAPISpec
	}
	return toSerialize, nil
}

type NullableInputInterface struct {
	value *InputInterface
	isSet bool
}

func (v NullableInputInterface) Get() *InputInterface {
	return v.value
}

func (v *NullableInputInterface) Set(val *InputInterface) {
	v.value = val
	v.isSet = true
}

func (v NullableInputInterface) IsSet() bool {
	return v.isSet
}

func (v *NullableInputInterface) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputInterface(val *InputInterface) *NullableInputInterface {
	return &NullableInputInterface{value: val, isSet: true}
}

func (v NullableInputInterface) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputInterface) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
