/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the RepositoryConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RepositoryConfig{}

// RepositoryConfig Git repository configuration
type RepositoryConfig struct {
	// URL of the git repository
	Url string `json:"url"`
	// Branch to use
	Branch string `json:"branch"`
	// Path within the repository where the source code resides
	AppPath string `json:"appPath"`
}

// NewRepositoryConfig instantiates a new RepositoryConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRepositoryConfig(url string, branch string, appPath string) *RepositoryConfig {
	this := RepositoryConfig{}
	this.Url = url
	this.Branch = branch
	this.AppPath = appPath
	return &this
}

// NewRepositoryConfigWithDefaults instantiates a new RepositoryConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRepositoryConfigWithDefaults() *RepositoryConfig {
	this := RepositoryConfig{}
	return &this
}

// GetUrl returns the Url field value
func (o *RepositoryConfig) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *RepositoryConfig) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *RepositoryConfig) SetUrl(v string) {
	o.Url = v
}

// GetBranch returns the Branch field value
func (o *RepositoryConfig) GetBranch() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Branch
}

// GetBranchOk returns a tuple with the Branch field value
// and a boolean to check if the value has been set.
func (o *RepositoryConfig) GetBranchOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Branch, true
}

// SetBranch sets field value
func (o *RepositoryConfig) SetBranch(v string) {
	o.Branch = v
}

// GetAppPath returns the AppPath field value
func (o *RepositoryConfig) GetAppPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AppPath
}

// GetAppPathOk returns a tuple with the AppPath field value
// and a boolean to check if the value has been set.
func (o *RepositoryConfig) GetAppPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppPath, true
}

// SetAppPath sets field value
func (o *RepositoryConfig) SetAppPath(v string) {
	o.AppPath = v
}

func (o RepositoryConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RepositoryConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	toSerialize["branch"] = o.Branch
	toSerialize["appPath"] = o.AppPath
	return toSerialize, nil
}

type NullableRepositoryConfig struct {
	value *RepositoryConfig
	isSet bool
}

func (v NullableRepositoryConfig) Get() *RepositoryConfig {
	return v.value
}

func (v *NullableRepositoryConfig) Set(val *RepositoryConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableRepositoryConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableRepositoryConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRepositoryConfig(val *RepositoryConfig) *NullableRepositoryConfig {
	return &NullableRepositoryConfig{value: val, isSet: true}
}

func (v NullableRepositoryConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRepositoryConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
