/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
	"time"
)

// checks if the BuildResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BuildResponse{}

// BuildResponse struct for BuildResponse
type BuildResponse struct {
	BuildId     *string    `json:"buildId,omitempty"`
	BuildName   string     `json:"buildName"`
	ProjectName string     `json:"projectName"`
	AgentName   string     `json:"agentName"`
	CommitId    string     `json:"commitId"`
	StartedAt   time.Time  `json:"startedAt"`
	EndedAt     *time.Time `json:"endedAt,omitempty"`
	ImageId     *string    `json:"imageId,omitempty"`
	Status      *string    `json:"status,omitempty"`
	Branch      string     `json:"branch"`
}

// NewBuildResponse instantiates a new BuildResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBuildResponse(buildName string, projectName string, agentName string, commitId string, startedAt time.Time, branch string) *BuildResponse {
	this := BuildResponse{}
	this.BuildName = buildName
	this.ProjectName = projectName
	this.AgentName = agentName
	this.CommitId = commitId
	this.StartedAt = startedAt
	this.Branch = branch
	return &this
}

// NewBuildResponseWithDefaults instantiates a new BuildResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBuildResponseWithDefaults() *BuildResponse {
	this := BuildResponse{}
	return &this
}

// GetBuildId returns the BuildId field value if set, zero value otherwise.
func (o *BuildResponse) GetBuildId() string {
	if o == nil || IsNil(o.BuildId) {
		var ret string
		return ret
	}
	return *o.BuildId
}

// GetBuildIdOk returns a tuple with the BuildId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildResponse) GetBuildIdOk() (*string, bool) {
	if o == nil || IsNil(o.BuildId) {
		return nil, false
	}
	return o.BuildId, true
}

// HasBuildId returns a boolean if a field has been set.
func (o *BuildResponse) HasBuildId() bool {
	if o != nil && !IsNil(o.BuildId) {
		return true
	}

	return false
}

// SetBuildId gets a reference to the given string and assigns it to the BuildId field.
func (o *BuildResponse) SetBuildId(v string) {
	o.BuildId = &v
}

// GetBuildName returns the BuildName field value
func (o *BuildResponse) GetBuildName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BuildName
}

// GetBuildNameOk returns a tuple with the BuildName field value
// and a boolean to check if the value has been set.
func (o *BuildResponse) GetBuildNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BuildName, true
}

// SetBuildName sets field value
func (o *BuildResponse) SetBuildName(v string) {
	o.BuildName = v
}

// GetProjectName returns the ProjectName field value
func (o *BuildResponse) GetProjectName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectName
}

// GetProjectNameOk returns a tuple with the ProjectName field value
// and a boolean to check if the value has been set.
func (o *BuildResponse) GetProjectNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectName, true
}

// SetProjectName sets field value
func (o *BuildResponse) SetProjectName(v string) {
	o.ProjectName = v
}

// GetAgentName returns the AgentName field value
func (o *BuildResponse) GetAgentName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AgentName
}

// GetAgentNameOk returns a tuple with the AgentName field value
// and a boolean to check if the value has been set.
func (o *BuildResponse) GetAgentNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentName, true
}

// SetAgentName sets field value
func (o *BuildResponse) SetAgentName(v string) {
	o.AgentName = v
}

// GetCommitId returns the CommitId field value
func (o *BuildResponse) GetCommitId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CommitId
}

// GetCommitIdOk returns a tuple with the CommitId field value
// and a boolean to check if the value has been set.
func (o *BuildResponse) GetCommitIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CommitId, true
}

// SetCommitId sets field value
func (o *BuildResponse) SetCommitId(v string) {
	o.CommitId = v
}

// GetStartedAt returns the StartedAt field value
func (o *BuildResponse) GetStartedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StartedAt
}

// GetStartedAtOk returns a tuple with the StartedAt field value
// and a boolean to check if the value has been set.
func (o *BuildResponse) GetStartedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartedAt, true
}

// SetStartedAt sets field value
func (o *BuildResponse) SetStartedAt(v time.Time) {
	o.StartedAt = v
}

// GetEndedAt returns the EndedAt field value if set, zero value otherwise.
func (o *BuildResponse) GetEndedAt() time.Time {
	if o == nil || IsNil(o.EndedAt) {
		var ret time.Time
		return ret
	}
	return *o.EndedAt
}

// GetEndedAtOk returns a tuple with the EndedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildResponse) GetEndedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EndedAt) {
		return nil, false
	}
	return o.EndedAt, true
}

// HasEndedAt returns a boolean if a field has been set.
func (o *BuildResponse) HasEndedAt() bool {
	if o != nil && !IsNil(o.EndedAt) {
		return true
	}

	return false
}

// SetEndedAt gets a reference to the given time.Time and assigns it to the EndedAt field.
func (o *BuildResponse) SetEndedAt(v time.Time) {
	o.EndedAt = &v
}

// GetImageId returns the ImageId field value if set, zero value otherwise.
func (o *BuildResponse) GetImageId() string {
	if o == nil || IsNil(o.ImageId) {
		var ret string
		return ret
	}
	return *o.ImageId
}

// GetImageIdOk returns a tuple with the ImageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildResponse) GetImageIdOk() (*string, bool) {
	if o == nil || IsNil(o.ImageId) {
		return nil, false
	}
	return o.ImageId, true
}

// HasImageId returns a boolean if a field has been set.
func (o *BuildResponse) HasImageId() bool {
	if o != nil && !IsNil(o.ImageId) {
		return true
	}

	return false
}

// SetImageId gets a reference to the given string and assigns it to the ImageId field.
func (o *BuildResponse) SetImageId(v string) {
	o.ImageId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *BuildResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *BuildResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *BuildResponse) SetStatus(v string) {
	o.Status = &v
}

// GetBranch returns the Branch field value
func (o *BuildResponse) GetBranch() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Branch
}

// GetBranchOk returns a tuple with the Branch field value
// and a boolean to check if the value has been set.
func (o *BuildResponse) GetBranchOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Branch, true
}

// SetBranch sets field value
func (o *BuildResponse) SetBranch(v string) {
	o.Branch = v
}

func (o BuildResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BuildResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BuildId) {
		toSerialize["buildId"] = o.BuildId
	}
	toSerialize["buildName"] = o.BuildName
	toSerialize["projectName"] = o.ProjectName
	toSerialize["agentName"] = o.AgentName
	toSerialize["commitId"] = o.CommitId
	toSerialize["startedAt"] = o.StartedAt
	if !IsNil(o.EndedAt) {
		toSerialize["endedAt"] = o.EndedAt
	}
	if !IsNil(o.ImageId) {
		toSerialize["imageId"] = o.ImageId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	toSerialize["branch"] = o.Branch
	return toSerialize, nil
}

type NullableBuildResponse struct {
	value *BuildResponse
	isSet bool
}

func (v NullableBuildResponse) Get() *BuildResponse {
	return v.value
}

func (v *NullableBuildResponse) Set(val *BuildResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBuildResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBuildResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBuildResponse(val *BuildResponse) *NullableBuildResponse {
	return &NullableBuildResponse{value: val, isSet: true}
}

func (v NullableBuildResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBuildResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
