/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the DeploymentDetailsResponsePromotionTargetEnvironment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeploymentDetailsResponsePromotionTargetEnvironment{}

// DeploymentDetailsResponsePromotionTargetEnvironment Promotion target environment details
type DeploymentDetailsResponsePromotionTargetEnvironment struct {
	// name of the promotion target environment
	Name string `json:"name"`
	// Human-readable display name of the promotion target environment
	DisplayName string `json:"displayName"`
}

// NewDeploymentDetailsResponsePromotionTargetEnvironment instantiates a new DeploymentDetailsResponsePromotionTargetEnvironment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeploymentDetailsResponsePromotionTargetEnvironment(name string, displayName string) *DeploymentDetailsResponsePromotionTargetEnvironment {
	this := DeploymentDetailsResponsePromotionTargetEnvironment{}
	this.Name = name
	this.DisplayName = displayName
	return &this
}

// NewDeploymentDetailsResponsePromotionTargetEnvironmentWithDefaults instantiates a new DeploymentDetailsResponsePromotionTargetEnvironment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeploymentDetailsResponsePromotionTargetEnvironmentWithDefaults() *DeploymentDetailsResponsePromotionTargetEnvironment {
	this := DeploymentDetailsResponsePromotionTargetEnvironment{}
	return &this
}

// GetName returns the Name field value
func (o *DeploymentDetailsResponsePromotionTargetEnvironment) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DeploymentDetailsResponsePromotionTargetEnvironment) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DeploymentDetailsResponsePromotionTargetEnvironment) SetName(v string) {
	o.Name = v
}

// GetDisplayName returns the DisplayName field value
func (o *DeploymentDetailsResponsePromotionTargetEnvironment) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *DeploymentDetailsResponsePromotionTargetEnvironment) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *DeploymentDetailsResponsePromotionTargetEnvironment) SetDisplayName(v string) {
	o.DisplayName = v
}

func (o DeploymentDetailsResponsePromotionTargetEnvironment) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeploymentDetailsResponsePromotionTargetEnvironment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["displayName"] = o.DisplayName
	return toSerialize, nil
}

type NullableDeploymentDetailsResponsePromotionTargetEnvironment struct {
	value *DeploymentDetailsResponsePromotionTargetEnvironment
	isSet bool
}

func (v NullableDeploymentDetailsResponsePromotionTargetEnvironment) Get() *DeploymentDetailsResponsePromotionTargetEnvironment {
	return v.value
}

func (v *NullableDeploymentDetailsResponsePromotionTargetEnvironment) Set(val *DeploymentDetailsResponsePromotionTargetEnvironment) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentDetailsResponsePromotionTargetEnvironment) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentDetailsResponsePromotionTargetEnvironment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentDetailsResponsePromotionTargetEnvironment(val *DeploymentDetailsResponsePromotionTargetEnvironment) *NullableDeploymentDetailsResponsePromotionTargetEnvironment {
	return &NullableDeploymentDetailsResponsePromotionTargetEnvironment{value: val, isSet: true}
}

func (v NullableDeploymentDetailsResponsePromotionTargetEnvironment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentDetailsResponsePromotionTargetEnvironment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
