/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the InputInterfaceSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InputInterfaceSchema{}

// InputInterfaceSchema struct for InputInterfaceSchema
type InputInterfaceSchema struct {
	// Path to OpenAPI schema file
	Path string `json:"path"`
}

// NewInputInterfaceSchema instantiates a new InputInterfaceSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInputInterfaceSchema(path string) *InputInterfaceSchema {
	this := InputInterfaceSchema{}
	this.Path = path
	return &this
}

// NewInputInterfaceSchemaWithDefaults instantiates a new InputInterfaceSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInputInterfaceSchemaWithDefaults() *InputInterfaceSchema {
	this := InputInterfaceSchema{}
	return &this
}

// GetPath returns the Path field value
func (o *InputInterfaceSchema) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *InputInterfaceSchema) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *InputInterfaceSchema) SetPath(v string) {
	o.Path = v
}

func (o InputInterfaceSchema) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InputInterfaceSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["path"] = o.Path
	return toSerialize, nil
}

type NullableInputInterfaceSchema struct {
	value *InputInterfaceSchema
	isSet bool
}

func (v NullableInputInterfaceSchema) Get() *InputInterfaceSchema {
	return v.value
}

func (v *NullableInputInterfaceSchema) Set(val *InputInterfaceSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableInputInterfaceSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableInputInterfaceSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputInterfaceSchema(val *InputInterfaceSchema) *NullableInputInterfaceSchema {
	return &NullableInputInterfaceSchema{value: val, isSet: true}
}

func (v NullableInputInterfaceSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputInterfaceSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
