/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
	"time"
)

// checks if the BuildDetailsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BuildDetailsResponse{}

// BuildDetailsResponse struct for BuildDetailsResponse
type BuildDetailsResponse struct {
	BuildId     *string    `json:"buildId,omitempty"`
	BuildName   string     `json:"buildName"`
	ProjectName string     `json:"projectName"`
	AgentName   string     `json:"agentName"`
	CommitId    string     `json:"commitId"`
	StartedAt   time.Time  `json:"startedAt"`
	EndedAt     *time.Time `json:"endedAt,omitempty"`
	ImageId     *string    `json:"imageId,omitempty"`
	Status      *string    `json:"status,omitempty"`
	Branch      string     `json:"branch"`
	// Build completion percentage (0-100)
	Percent *float32 `json:"percent,omitempty"`
	// Array of build steps with their status
	Steps []BuildStep `json:"steps,omitempty"`
	// Build duration in seconds
	DurationSeconds *int32 `json:"durationSeconds,omitempty"`
}

// NewBuildDetailsResponse instantiates a new BuildDetailsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBuildDetailsResponse(buildName string, projectName string, agentName string, commitId string, startedAt time.Time, branch string) *BuildDetailsResponse {
	this := BuildDetailsResponse{}
	this.BuildName = buildName
	this.ProjectName = projectName
	this.AgentName = agentName
	this.CommitId = commitId
	this.StartedAt = startedAt
	this.Branch = branch
	return &this
}

// NewBuildDetailsResponseWithDefaults instantiates a new BuildDetailsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBuildDetailsResponseWithDefaults() *BuildDetailsResponse {
	this := BuildDetailsResponse{}
	return &this
}

// GetBuildId returns the BuildId field value if set, zero value otherwise.
func (o *BuildDetailsResponse) GetBuildId() string {
	if o == nil || IsNil(o.BuildId) {
		var ret string
		return ret
	}
	return *o.BuildId
}

// GetBuildIdOk returns a tuple with the BuildId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildDetailsResponse) GetBuildIdOk() (*string, bool) {
	if o == nil || IsNil(o.BuildId) {
		return nil, false
	}
	return o.BuildId, true
}

// HasBuildId returns a boolean if a field has been set.
func (o *BuildDetailsResponse) HasBuildId() bool {
	if o != nil && !IsNil(o.BuildId) {
		return true
	}

	return false
}

// SetBuildId gets a reference to the given string and assigns it to the BuildId field.
func (o *BuildDetailsResponse) SetBuildId(v string) {
	o.BuildId = &v
}

// GetBuildName returns the BuildName field value
func (o *BuildDetailsResponse) GetBuildName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BuildName
}

// GetBuildNameOk returns a tuple with the BuildName field value
// and a boolean to check if the value has been set.
func (o *BuildDetailsResponse) GetBuildNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BuildName, true
}

// SetBuildName sets field value
func (o *BuildDetailsResponse) SetBuildName(v string) {
	o.BuildName = v
}

// GetProjectName returns the ProjectName field value
func (o *BuildDetailsResponse) GetProjectName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectName
}

// GetProjectNameOk returns a tuple with the ProjectName field value
// and a boolean to check if the value has been set.
func (o *BuildDetailsResponse) GetProjectNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectName, true
}

// SetProjectName sets field value
func (o *BuildDetailsResponse) SetProjectName(v string) {
	o.ProjectName = v
}

// GetAgentName returns the AgentName field value
func (o *BuildDetailsResponse) GetAgentName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AgentName
}

// GetAgentNameOk returns a tuple with the AgentName field value
// and a boolean to check if the value has been set.
func (o *BuildDetailsResponse) GetAgentNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentName, true
}

// SetAgentName sets field value
func (o *BuildDetailsResponse) SetAgentName(v string) {
	o.AgentName = v
}

// GetCommitId returns the CommitId field value
func (o *BuildDetailsResponse) GetCommitId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CommitId
}

// GetCommitIdOk returns a tuple with the CommitId field value
// and a boolean to check if the value has been set.
func (o *BuildDetailsResponse) GetCommitIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CommitId, true
}

// SetCommitId sets field value
func (o *BuildDetailsResponse) SetCommitId(v string) {
	o.CommitId = v
}

// GetStartedAt returns the StartedAt field value
func (o *BuildDetailsResponse) GetStartedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StartedAt
}

// GetStartedAtOk returns a tuple with the StartedAt field value
// and a boolean to check if the value has been set.
func (o *BuildDetailsResponse) GetStartedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartedAt, true
}

// SetStartedAt sets field value
func (o *BuildDetailsResponse) SetStartedAt(v time.Time) {
	o.StartedAt = v
}

// GetEndedAt returns the EndedAt field value if set, zero value otherwise.
func (o *BuildDetailsResponse) GetEndedAt() time.Time {
	if o == nil || IsNil(o.EndedAt) {
		var ret time.Time
		return ret
	}
	return *o.EndedAt
}

// GetEndedAtOk returns a tuple with the EndedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildDetailsResponse) GetEndedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EndedAt) {
		return nil, false
	}
	return o.EndedAt, true
}

// HasEndedAt returns a boolean if a field has been set.
func (o *BuildDetailsResponse) HasEndedAt() bool {
	if o != nil && !IsNil(o.EndedAt) {
		return true
	}

	return false
}

// SetEndedAt gets a reference to the given time.Time and assigns it to the EndedAt field.
func (o *BuildDetailsResponse) SetEndedAt(v time.Time) {
	o.EndedAt = &v
}

// GetImageId returns the ImageId field value if set, zero value otherwise.
func (o *BuildDetailsResponse) GetImageId() string {
	if o == nil || IsNil(o.ImageId) {
		var ret string
		return ret
	}
	return *o.ImageId
}

// GetImageIdOk returns a tuple with the ImageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildDetailsResponse) GetImageIdOk() (*string, bool) {
	if o == nil || IsNil(o.ImageId) {
		return nil, false
	}
	return o.ImageId, true
}

// HasImageId returns a boolean if a field has been set.
func (o *BuildDetailsResponse) HasImageId() bool {
	if o != nil && !IsNil(o.ImageId) {
		return true
	}

	return false
}

// SetImageId gets a reference to the given string and assigns it to the ImageId field.
func (o *BuildDetailsResponse) SetImageId(v string) {
	o.ImageId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *BuildDetailsResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildDetailsResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *BuildDetailsResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *BuildDetailsResponse) SetStatus(v string) {
	o.Status = &v
}

// GetBranch returns the Branch field value
func (o *BuildDetailsResponse) GetBranch() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Branch
}

// GetBranchOk returns a tuple with the Branch field value
// and a boolean to check if the value has been set.
func (o *BuildDetailsResponse) GetBranchOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Branch, true
}

// SetBranch sets field value
func (o *BuildDetailsResponse) SetBranch(v string) {
	o.Branch = v
}

// GetPercent returns the Percent field value if set, zero value otherwise.
func (o *BuildDetailsResponse) GetPercent() float32 {
	if o == nil || IsNil(o.Percent) {
		var ret float32
		return ret
	}
	return *o.Percent
}

// GetPercentOk returns a tuple with the Percent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildDetailsResponse) GetPercentOk() (*float32, bool) {
	if o == nil || IsNil(o.Percent) {
		return nil, false
	}
	return o.Percent, true
}

// HasPercent returns a boolean if a field has been set.
func (o *BuildDetailsResponse) HasPercent() bool {
	if o != nil && !IsNil(o.Percent) {
		return true
	}

	return false
}

// SetPercent gets a reference to the given float32 and assigns it to the Percent field.
func (o *BuildDetailsResponse) SetPercent(v float32) {
	o.Percent = &v
}

// GetSteps returns the Steps field value if set, zero value otherwise.
func (o *BuildDetailsResponse) GetSteps() []BuildStep {
	if o == nil || IsNil(o.Steps) {
		var ret []BuildStep
		return ret
	}
	return o.Steps
}

// GetStepsOk returns a tuple with the Steps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildDetailsResponse) GetStepsOk() ([]BuildStep, bool) {
	if o == nil || IsNil(o.Steps) {
		return nil, false
	}
	return o.Steps, true
}

// HasSteps returns a boolean if a field has been set.
func (o *BuildDetailsResponse) HasSteps() bool {
	if o != nil && !IsNil(o.Steps) {
		return true
	}

	return false
}

// SetSteps gets a reference to the given []BuildStep and assigns it to the Steps field.
func (o *BuildDetailsResponse) SetSteps(v []BuildStep) {
	o.Steps = v
}

// GetDurationSeconds returns the DurationSeconds field value if set, zero value otherwise.
func (o *BuildDetailsResponse) GetDurationSeconds() int32 {
	if o == nil || IsNil(o.DurationSeconds) {
		var ret int32
		return ret
	}
	return *o.DurationSeconds
}

// GetDurationSecondsOk returns a tuple with the DurationSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildDetailsResponse) GetDurationSecondsOk() (*int32, bool) {
	if o == nil || IsNil(o.DurationSeconds) {
		return nil, false
	}
	return o.DurationSeconds, true
}

// HasDurationSeconds returns a boolean if a field has been set.
func (o *BuildDetailsResponse) HasDurationSeconds() bool {
	if o != nil && !IsNil(o.DurationSeconds) {
		return true
	}

	return false
}

// SetDurationSeconds gets a reference to the given int32 and assigns it to the DurationSeconds field.
func (o *BuildDetailsResponse) SetDurationSeconds(v int32) {
	o.DurationSeconds = &v
}

func (o BuildDetailsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BuildDetailsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BuildId) {
		toSerialize["buildId"] = o.BuildId
	}
	toSerialize["buildName"] = o.BuildName
	toSerialize["projectName"] = o.ProjectName
	toSerialize["agentName"] = o.AgentName
	toSerialize["commitId"] = o.CommitId
	toSerialize["startedAt"] = o.StartedAt
	if !IsNil(o.EndedAt) {
		toSerialize["endedAt"] = o.EndedAt
	}
	if !IsNil(o.ImageId) {
		toSerialize["imageId"] = o.ImageId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	toSerialize["branch"] = o.Branch
	if !IsNil(o.Percent) {
		toSerialize["percent"] = o.Percent
	}
	if !IsNil(o.Steps) {
		toSerialize["steps"] = o.Steps
	}
	if !IsNil(o.DurationSeconds) {
		toSerialize["durationSeconds"] = o.DurationSeconds
	}
	return toSerialize, nil
}

type NullableBuildDetailsResponse struct {
	value *BuildDetailsResponse
	isSet bool
}

func (v NullableBuildDetailsResponse) Get() *BuildDetailsResponse {
	return v.value
}

func (v *NullableBuildDetailsResponse) Set(val *BuildDetailsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBuildDetailsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBuildDetailsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBuildDetailsResponse(val *BuildDetailsResponse) *NullableBuildDetailsResponse {
	return &NullableBuildDetailsResponse{value: val, isSet: true}
}

func (v NullableBuildDetailsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBuildDetailsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
