/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the ResourceNameResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceNameResponse{}

// ResourceNameResponse struct for ResourceNameResponse
type ResourceNameResponse struct {
	// The resource name
	Name string `json:"name"`
	// The display name of the resource
	DisplayName string `json:"displayName"`
	// Type of resource (e.g., agent, project)
	ResourceType string `json:"resourceType"`
}

// NewResourceNameResponse instantiates a new ResourceNameResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceNameResponse(name string, displayName string, resourceType string) *ResourceNameResponse {
	this := ResourceNameResponse{}
	this.Name = name
	this.DisplayName = displayName
	this.ResourceType = resourceType
	return &this
}

// NewResourceNameResponseWithDefaults instantiates a new ResourceNameResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceNameResponseWithDefaults() *ResourceNameResponse {
	this := ResourceNameResponse{}
	return &this
}

// GetName returns the Name field value
func (o *ResourceNameResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ResourceNameResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ResourceNameResponse) SetName(v string) {
	o.Name = v
}

// GetDisplayName returns the DisplayName field value
func (o *ResourceNameResponse) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *ResourceNameResponse) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *ResourceNameResponse) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetResourceType returns the ResourceType field value
func (o *ResourceNameResponse) GetResourceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceType
}

// GetResourceTypeOk returns a tuple with the ResourceType field value
// and a boolean to check if the value has been set.
func (o *ResourceNameResponse) GetResourceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceType, true
}

// SetResourceType sets field value
func (o *ResourceNameResponse) SetResourceType(v string) {
	o.ResourceType = v
}

func (o ResourceNameResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourceNameResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["displayName"] = o.DisplayName
	toSerialize["resourceType"] = o.ResourceType
	return toSerialize, nil
}

type NullableResourceNameResponse struct {
	value *ResourceNameResponse
	isSet bool
}

func (v NullableResourceNameResponse) Get() *ResourceNameResponse {
	return v.value
}

func (v *NullableResourceNameResponse) Set(val *ResourceNameResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceNameResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceNameResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceNameResponse(val *ResourceNameResponse) *NullableResourceNameResponse {
	return &NullableResourceNameResponse{value: val, isSet: true}
}

func (v NullableResourceNameResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceNameResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
