/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the DeploymentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeploymentResponse{}

// DeploymentResponse struct for DeploymentResponse
type DeploymentResponse struct {
	AgentName   string `json:"agentName"`
	ProjectName string `json:"projectName"`
	ImageId     string `json:"imageId"`
	Environment string `json:"environment"`
}

// NewDeploymentResponse instantiates a new DeploymentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeploymentResponse(agentName string, projectName string, imageId string, environment string) *DeploymentResponse {
	this := DeploymentResponse{}
	this.AgentName = agentName
	this.ProjectName = projectName
	this.ImageId = imageId
	this.Environment = environment
	return &this
}

// NewDeploymentResponseWithDefaults instantiates a new DeploymentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeploymentResponseWithDefaults() *DeploymentResponse {
	this := DeploymentResponse{}
	return &this
}

// GetAgentName returns the AgentName field value
func (o *DeploymentResponse) GetAgentName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AgentName
}

// GetAgentNameOk returns a tuple with the AgentName field value
// and a boolean to check if the value has been set.
func (o *DeploymentResponse) GetAgentNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentName, true
}

// SetAgentName sets field value
func (o *DeploymentResponse) SetAgentName(v string) {
	o.AgentName = v
}

// GetProjectName returns the ProjectName field value
func (o *DeploymentResponse) GetProjectName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectName
}

// GetProjectNameOk returns a tuple with the ProjectName field value
// and a boolean to check if the value has been set.
func (o *DeploymentResponse) GetProjectNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectName, true
}

// SetProjectName sets field value
func (o *DeploymentResponse) SetProjectName(v string) {
	o.ProjectName = v
}

// GetImageId returns the ImageId field value
func (o *DeploymentResponse) GetImageId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ImageId
}

// GetImageIdOk returns a tuple with the ImageId field value
// and a boolean to check if the value has been set.
func (o *DeploymentResponse) GetImageIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImageId, true
}

// SetImageId sets field value
func (o *DeploymentResponse) SetImageId(v string) {
	o.ImageId = v
}

// GetEnvironment returns the Environment field value
func (o *DeploymentResponse) GetEnvironment() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value
// and a boolean to check if the value has been set.
func (o *DeploymentResponse) GetEnvironmentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Environment, true
}

// SetEnvironment sets field value
func (o *DeploymentResponse) SetEnvironment(v string) {
	o.Environment = v
}

func (o DeploymentResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeploymentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["agentName"] = o.AgentName
	toSerialize["projectName"] = o.ProjectName
	toSerialize["imageId"] = o.ImageId
	toSerialize["environment"] = o.Environment
	return toSerialize, nil
}

type NullableDeploymentResponse struct {
	value *DeploymentResponse
	isSet bool
}

func (v NullableDeploymentResponse) Get() *DeploymentResponse {
	return v.value
}

func (v *NullableDeploymentResponse) Set(val *DeploymentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentResponse(val *DeploymentResponse) *NullableDeploymentResponse {
	return &NullableDeploymentResponse{value: val, isSet: true}
}

func (v NullableDeploymentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
