/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the AgentType type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentType{}

// AgentType struct for AgentType
type AgentType struct {
	// Type of the agent
	Type string `json:"type"`
	// Sub-type of the agent
	SubType *string `json:"subType,omitempty"`
}

// NewAgentType instantiates a new AgentType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentType(type_ string) *AgentType {
	this := AgentType{}
	this.Type = type_
	return &this
}

// NewAgentTypeWithDefaults instantiates a new AgentType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentTypeWithDefaults() *AgentType {
	this := AgentType{}
	return &this
}

// GetType returns the Type field value
func (o *AgentType) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AgentType) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AgentType) SetType(v string) {
	o.Type = v
}

// GetSubType returns the SubType field value if set, zero value otherwise.
func (o *AgentType) GetSubType() string {
	if o == nil || IsNil(o.SubType) {
		var ret string
		return ret
	}
	return *o.SubType
}

// GetSubTypeOk returns a tuple with the SubType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentType) GetSubTypeOk() (*string, bool) {
	if o == nil || IsNil(o.SubType) {
		return nil, false
	}
	return o.SubType, true
}

// HasSubType returns a boolean if a field has been set.
func (o *AgentType) HasSubType() bool {
	if o != nil && !IsNil(o.SubType) {
		return true
	}

	return false
}

// SetSubType gets a reference to the given string and assigns it to the SubType field.
func (o *AgentType) SetSubType(v string) {
	o.SubType = &v
}

func (o AgentType) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentType) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.SubType) {
		toSerialize["subType"] = o.SubType
	}
	return toSerialize, nil
}

type NullableAgentType struct {
	value *AgentType
	isSet bool
}

func (v NullableAgentType) Get() *AgentType {
	return v.value
}

func (v *NullableAgentType) Set(val *AgentType) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentType) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentType(val *AgentType) *NullableAgentType {
	return &NullableAgentType{value: val, isSet: true}
}

func (v NullableAgentType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
