/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the TargetEnvironmentRef type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TargetEnvironmentRef{}

// TargetEnvironmentRef struct for TargetEnvironmentRef
type TargetEnvironmentRef struct {
	// Name of the target environment
	Name string `json:"name"`
}

// NewTargetEnvironmentRef instantiates a new TargetEnvironmentRef object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTargetEnvironmentRef(name string) *TargetEnvironmentRef {
	this := TargetEnvironmentRef{}
	this.Name = name
	return &this
}

// NewTargetEnvironmentRefWithDefaults instantiates a new TargetEnvironmentRef object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTargetEnvironmentRefWithDefaults() *TargetEnvironmentRef {
	this := TargetEnvironmentRef{}
	return &this
}

// GetName returns the Name field value
func (o *TargetEnvironmentRef) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TargetEnvironmentRef) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TargetEnvironmentRef) SetName(v string) {
	o.Name = v
}

func (o TargetEnvironmentRef) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TargetEnvironmentRef) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

type NullableTargetEnvironmentRef struct {
	value *TargetEnvironmentRef
	isSet bool
}

func (v NullableTargetEnvironmentRef) Get() *TargetEnvironmentRef {
	return v.value
}

func (v *NullableTargetEnvironmentRef) Set(val *TargetEnvironmentRef) {
	v.value = val
	v.isSet = true
}

func (v NullableTargetEnvironmentRef) IsSet() bool {
	return v.isSet
}

func (v *NullableTargetEnvironmentRef) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTargetEnvironmentRef(val *TargetEnvironmentRef) *NullableTargetEnvironmentRef {
	return &NullableTargetEnvironmentRef{value: val, isSet: true}
}

func (v NullableTargetEnvironmentRef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTargetEnvironmentRef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
