/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
	"time"
)

// checks if the AgentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentResponse{}

// AgentResponse struct for AgentResponse
type AgentResponse struct {
	Uuid        string    `json:"uuid"`
	Name        string    `json:"name"`
	DisplayName string    `json:"displayName"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
	ProjectName string    `json:"projectName"`
	// Current status of the agent
	Status         *string               `json:"status,omitempty"`
	Provisioning   Provisioning          `json:"provisioning"`
	AgentType      AgentType             `json:"agentType"`
	RuntimeConfigs *RuntimeConfiguration `json:"runtimeConfigs,omitempty"`
}

// NewAgentResponse instantiates a new AgentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentResponse(uuid string, name string, displayName string, description string, createdAt time.Time, projectName string, provisioning Provisioning, agentType AgentType) *AgentResponse {
	this := AgentResponse{}
	this.Uuid = uuid
	this.Name = name
	this.DisplayName = displayName
	this.Description = description
	this.CreatedAt = createdAt
	this.ProjectName = projectName
	this.Provisioning = provisioning
	this.AgentType = agentType
	return &this
}

// NewAgentResponseWithDefaults instantiates a new AgentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentResponseWithDefaults() *AgentResponse {
	this := AgentResponse{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *AgentResponse) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *AgentResponse) SetUuid(v string) {
	o.Uuid = v
}

// GetName returns the Name field value
func (o *AgentResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AgentResponse) SetName(v string) {
	o.Name = v
}

// GetDisplayName returns the DisplayName field value
func (o *AgentResponse) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *AgentResponse) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetDescription returns the Description field value
func (o *AgentResponse) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *AgentResponse) SetDescription(v string) {
	o.Description = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *AgentResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *AgentResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetProjectName returns the ProjectName field value
func (o *AgentResponse) GetProjectName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectName
}

// GetProjectNameOk returns a tuple with the ProjectName field value
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetProjectNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectName, true
}

// SetProjectName sets field value
func (o *AgentResponse) SetProjectName(v string) {
	o.ProjectName = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *AgentResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *AgentResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *AgentResponse) SetStatus(v string) {
	o.Status = &v
}

// GetProvisioning returns the Provisioning field value
func (o *AgentResponse) GetProvisioning() Provisioning {
	if o == nil {
		var ret Provisioning
		return ret
	}

	return o.Provisioning
}

// GetProvisioningOk returns a tuple with the Provisioning field value
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetProvisioningOk() (*Provisioning, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provisioning, true
}

// SetProvisioning sets field value
func (o *AgentResponse) SetProvisioning(v Provisioning) {
	o.Provisioning = v
}

// GetAgentType returns the AgentType field value
func (o *AgentResponse) GetAgentType() AgentType {
	if o == nil {
		var ret AgentType
		return ret
	}

	return o.AgentType
}

// GetAgentTypeOk returns a tuple with the AgentType field value
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetAgentTypeOk() (*AgentType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentType, true
}

// SetAgentType sets field value
func (o *AgentResponse) SetAgentType(v AgentType) {
	o.AgentType = v
}

// GetRuntimeConfigs returns the RuntimeConfigs field value if set, zero value otherwise.
func (o *AgentResponse) GetRuntimeConfigs() RuntimeConfiguration {
	if o == nil || IsNil(o.RuntimeConfigs) {
		var ret RuntimeConfiguration
		return ret
	}
	return *o.RuntimeConfigs
}

// GetRuntimeConfigsOk returns a tuple with the RuntimeConfigs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetRuntimeConfigsOk() (*RuntimeConfiguration, bool) {
	if o == nil || IsNil(o.RuntimeConfigs) {
		return nil, false
	}
	return o.RuntimeConfigs, true
}

// HasRuntimeConfigs returns a boolean if a field has been set.
func (o *AgentResponse) HasRuntimeConfigs() bool {
	if o != nil && !IsNil(o.RuntimeConfigs) {
		return true
	}

	return false
}

// SetRuntimeConfigs gets a reference to the given RuntimeConfiguration and assigns it to the RuntimeConfigs field.
func (o *AgentResponse) SetRuntimeConfigs(v RuntimeConfiguration) {
	o.RuntimeConfigs = &v
}

func (o AgentResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	toSerialize["name"] = o.Name
	toSerialize["displayName"] = o.DisplayName
	toSerialize["description"] = o.Description
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["projectName"] = o.ProjectName
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	toSerialize["provisioning"] = o.Provisioning
	toSerialize["agentType"] = o.AgentType
	if !IsNil(o.RuntimeConfigs) {
		toSerialize["runtimeConfigs"] = o.RuntimeConfigs
	}
	return toSerialize, nil
}

type NullableAgentResponse struct {
	value *AgentResponse
	isSet bool
}

func (v NullableAgentResponse) Get() *AgentResponse {
	return v.value
}

func (v *NullableAgentResponse) Set(val *AgentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentResponse(val *AgentResponse) *NullableAgentResponse {
	return &NullableAgentResponse{value: val, isSet: true}
}

func (v NullableAgentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
