/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
	"time"
)

// checks if the ProjectResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectResponse{}

// ProjectResponse struct for ProjectResponse
type ProjectResponse struct {
	// Name of the project
	Name string `json:"name"`
	// Name of the organization
	OrgName string `json:"orgName"`
	// Display name of the project
	DisplayName string `json:"displayName"`
	// Description of the project
	Description string `json:"description"`
	// Deployment pipeline associated with the project
	DeploymentPipeline string `json:"deploymentPipeline"`
	// Timestamp when the project was created
	CreatedAt time.Time `json:"createdAt"`
}

// NewProjectResponse instantiates a new ProjectResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectResponse(name string, orgName string, displayName string, description string, deploymentPipeline string, createdAt time.Time) *ProjectResponse {
	this := ProjectResponse{}
	this.Name = name
	this.OrgName = orgName
	this.DisplayName = displayName
	this.Description = description
	this.DeploymentPipeline = deploymentPipeline
	this.CreatedAt = createdAt
	return &this
}

// NewProjectResponseWithDefaults instantiates a new ProjectResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectResponseWithDefaults() *ProjectResponse {
	this := ProjectResponse{}
	return &this
}

// GetName returns the Name field value
func (o *ProjectResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ProjectResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ProjectResponse) SetName(v string) {
	o.Name = v
}

// GetOrgName returns the OrgName field value
func (o *ProjectResponse) GetOrgName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgName
}

// GetOrgNameOk returns a tuple with the OrgName field value
// and a boolean to check if the value has been set.
func (o *ProjectResponse) GetOrgNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgName, true
}

// SetOrgName sets field value
func (o *ProjectResponse) SetOrgName(v string) {
	o.OrgName = v
}

// GetDisplayName returns the DisplayName field value
func (o *ProjectResponse) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *ProjectResponse) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *ProjectResponse) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetDescription returns the Description field value
func (o *ProjectResponse) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *ProjectResponse) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *ProjectResponse) SetDescription(v string) {
	o.Description = v
}

// GetDeploymentPipeline returns the DeploymentPipeline field value
func (o *ProjectResponse) GetDeploymentPipeline() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeploymentPipeline
}

// GetDeploymentPipelineOk returns a tuple with the DeploymentPipeline field value
// and a boolean to check if the value has been set.
func (o *ProjectResponse) GetDeploymentPipelineOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeploymentPipeline, true
}

// SetDeploymentPipeline sets field value
func (o *ProjectResponse) SetDeploymentPipeline(v string) {
	o.DeploymentPipeline = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ProjectResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ProjectResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ProjectResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o ProjectResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["orgName"] = o.OrgName
	toSerialize["displayName"] = o.DisplayName
	toSerialize["description"] = o.Description
	toSerialize["deploymentPipeline"] = o.DeploymentPipeline
	toSerialize["createdAt"] = o.CreatedAt
	return toSerialize, nil
}

type NullableProjectResponse struct {
	value *ProjectResponse
	isSet bool
}

func (v NullableProjectResponse) Get() *ProjectResponse {
	return v.value
}

func (v *NullableProjectResponse) Set(val *ProjectResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectResponse(val *ProjectResponse) *NullableProjectResponse {
	return &NullableProjectResponse{value: val, isSet: true}
}

func (v NullableProjectResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
