/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the DeploymentPipelineListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeploymentPipelineListResponse{}

// DeploymentPipelineListResponse struct for DeploymentPipelineListResponse
type DeploymentPipelineListResponse struct {
	DeploymentPipelines []DeploymentPipelineResponse `json:"deploymentPipelines"`
	// Total number of deployment pipelines matching the query
	Total  int32 `json:"total"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// NewDeploymentPipelineListResponse instantiates a new DeploymentPipelineListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeploymentPipelineListResponse(deploymentPipelines []DeploymentPipelineResponse, total int32, limit int32, offset int32) *DeploymentPipelineListResponse {
	this := DeploymentPipelineListResponse{}
	this.DeploymentPipelines = deploymentPipelines
	this.Total = total
	this.Limit = limit
	this.Offset = offset
	return &this
}

// NewDeploymentPipelineListResponseWithDefaults instantiates a new DeploymentPipelineListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeploymentPipelineListResponseWithDefaults() *DeploymentPipelineListResponse {
	this := DeploymentPipelineListResponse{}
	return &this
}

// GetDeploymentPipelines returns the DeploymentPipelines field value
func (o *DeploymentPipelineListResponse) GetDeploymentPipelines() []DeploymentPipelineResponse {
	if o == nil {
		var ret []DeploymentPipelineResponse
		return ret
	}

	return o.DeploymentPipelines
}

// GetDeploymentPipelinesOk returns a tuple with the DeploymentPipelines field value
// and a boolean to check if the value has been set.
func (o *DeploymentPipelineListResponse) GetDeploymentPipelinesOk() ([]DeploymentPipelineResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeploymentPipelines, true
}

// SetDeploymentPipelines sets field value
func (o *DeploymentPipelineListResponse) SetDeploymentPipelines(v []DeploymentPipelineResponse) {
	o.DeploymentPipelines = v
}

// GetTotal returns the Total field value
func (o *DeploymentPipelineListResponse) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *DeploymentPipelineListResponse) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *DeploymentPipelineListResponse) SetTotal(v int32) {
	o.Total = v
}

// GetLimit returns the Limit field value
func (o *DeploymentPipelineListResponse) GetLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *DeploymentPipelineListResponse) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *DeploymentPipelineListResponse) SetLimit(v int32) {
	o.Limit = v
}

// GetOffset returns the Offset field value
func (o *DeploymentPipelineListResponse) GetOffset() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value
// and a boolean to check if the value has been set.
func (o *DeploymentPipelineListResponse) GetOffsetOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Offset, true
}

// SetOffset sets field value
func (o *DeploymentPipelineListResponse) SetOffset(v int32) {
	o.Offset = v
}

func (o DeploymentPipelineListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeploymentPipelineListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["deploymentPipelines"] = o.DeploymentPipelines
	toSerialize["total"] = o.Total
	toSerialize["limit"] = o.Limit
	toSerialize["offset"] = o.Offset
	return toSerialize, nil
}

type NullableDeploymentPipelineListResponse struct {
	value *DeploymentPipelineListResponse
	isSet bool
}

func (v NullableDeploymentPipelineListResponse) Get() *DeploymentPipelineListResponse {
	return v.value
}

func (v *NullableDeploymentPipelineListResponse) Set(val *DeploymentPipelineListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentPipelineListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentPipelineListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentPipelineListResponse(val *DeploymentPipelineListResponse) *NullableDeploymentPipelineListResponse {
	return &NullableDeploymentPipelineListResponse{value: val, isSet: true}
}

func (v NullableDeploymentPipelineListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentPipelineListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
