/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the BuildLogsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BuildLogsResponse{}

// BuildLogsResponse struct for BuildLogsResponse
type BuildLogsResponse struct {
	Logs       []LogEntry `json:"logs"`
	TotalCount int32      `json:"totalCount"`
	TookMs     float32    `json:"tookMs"`
}

// NewBuildLogsResponse instantiates a new BuildLogsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBuildLogsResponse(logs []LogEntry, totalCount int32, tookMs float32) *BuildLogsResponse {
	this := BuildLogsResponse{}
	this.Logs = logs
	this.TotalCount = totalCount
	this.TookMs = tookMs
	return &this
}

// NewBuildLogsResponseWithDefaults instantiates a new BuildLogsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBuildLogsResponseWithDefaults() *BuildLogsResponse {
	this := BuildLogsResponse{}
	return &this
}

// GetLogs returns the Logs field value
func (o *BuildLogsResponse) GetLogs() []LogEntry {
	if o == nil {
		var ret []LogEntry
		return ret
	}

	return o.Logs
}

// GetLogsOk returns a tuple with the Logs field value
// and a boolean to check if the value has been set.
func (o *BuildLogsResponse) GetLogsOk() ([]LogEntry, bool) {
	if o == nil {
		return nil, false
	}
	return o.Logs, true
}

// SetLogs sets field value
func (o *BuildLogsResponse) SetLogs(v []LogEntry) {
	o.Logs = v
}

// GetTotalCount returns the TotalCount field value
func (o *BuildLogsResponse) GetTotalCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value
// and a boolean to check if the value has been set.
func (o *BuildLogsResponse) GetTotalCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCount, true
}

// SetTotalCount sets field value
func (o *BuildLogsResponse) SetTotalCount(v int32) {
	o.TotalCount = v
}

// GetTookMs returns the TookMs field value
func (o *BuildLogsResponse) GetTookMs() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TookMs
}

// GetTookMsOk returns a tuple with the TookMs field value
// and a boolean to check if the value has been set.
func (o *BuildLogsResponse) GetTookMsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TookMs, true
}

// SetTookMs sets field value
func (o *BuildLogsResponse) SetTookMs(v float32) {
	o.TookMs = v
}

func (o BuildLogsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BuildLogsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["logs"] = o.Logs
	toSerialize["totalCount"] = o.TotalCount
	toSerialize["tookMs"] = o.TookMs
	return toSerialize, nil
}

type NullableBuildLogsResponse struct {
	value *BuildLogsResponse
	isSet bool
}

func (v NullableBuildLogsResponse) Get() *BuildLogsResponse {
	return v.value
}

func (v *NullableBuildLogsResponse) Set(val *BuildLogsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBuildLogsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBuildLogsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBuildLogsResponse(val *BuildLogsResponse) *NullableBuildLogsResponse {
	return &NullableBuildLogsResponse{value: val, isSet: true}
}

func (v NullableBuildLogsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBuildLogsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
