/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the EndpointSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EndpointSchema{}

// EndpointSchema struct for EndpointSchema
type EndpointSchema struct {
	// Schema content
	Content string `json:"content"`
}

// NewEndpointSchema instantiates a new EndpointSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEndpointSchema(content string) *EndpointSchema {
	this := EndpointSchema{}
	this.Content = content
	return &this
}

// NewEndpointSchemaWithDefaults instantiates a new EndpointSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEndpointSchemaWithDefaults() *EndpointSchema {
	this := EndpointSchema{}
	return &this
}

// GetContent returns the Content field value
func (o *EndpointSchema) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *EndpointSchema) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *EndpointSchema) SetContent(v string) {
	o.Content = v
}

func (o EndpointSchema) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EndpointSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["content"] = o.Content
	return toSerialize, nil
}

type NullableEndpointSchema struct {
	value *EndpointSchema
	isSet bool
}

func (v NullableEndpointSchema) Get() *EndpointSchema {
	return v.value
}

func (v *NullableEndpointSchema) Set(val *EndpointSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableEndpointSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableEndpointSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndpointSchema(val *EndpointSchema) *NullableEndpointSchema {
	return &NullableEndpointSchema{value: val, isSet: true}
}

func (v NullableEndpointSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndpointSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
