/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the AgentTypeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentTypeResponse{}

// AgentTypeResponse struct for AgentTypeResponse
type AgentTypeResponse struct {
	// Name of the agent type
	Name string `json:"name"`
	// Display name of the agent type
	DisplayName string `json:"displayName"`
	// Description of the agent type
	Description string `json:"description"`
	// List of subtypes for this agent type
	Subtypes []AgentTypeSubtype `json:"subtypes"`
}

// NewAgentTypeResponse instantiates a new AgentTypeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentTypeResponse(name string, displayName string, description string, subtypes []AgentTypeSubtype) *AgentTypeResponse {
	this := AgentTypeResponse{}
	this.Name = name
	this.DisplayName = displayName
	this.Description = description
	this.Subtypes = subtypes
	return &this
}

// NewAgentTypeResponseWithDefaults instantiates a new AgentTypeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentTypeResponseWithDefaults() *AgentTypeResponse {
	this := AgentTypeResponse{}
	return &this
}

// GetName returns the Name field value
func (o *AgentTypeResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AgentTypeResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AgentTypeResponse) SetName(v string) {
	o.Name = v
}

// GetDisplayName returns the DisplayName field value
func (o *AgentTypeResponse) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *AgentTypeResponse) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *AgentTypeResponse) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetDescription returns the Description field value
func (o *AgentTypeResponse) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *AgentTypeResponse) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *AgentTypeResponse) SetDescription(v string) {
	o.Description = v
}

// GetSubtypes returns the Subtypes field value
func (o *AgentTypeResponse) GetSubtypes() []AgentTypeSubtype {
	if o == nil {
		var ret []AgentTypeSubtype
		return ret
	}

	return o.Subtypes
}

// GetSubtypesOk returns a tuple with the Subtypes field value
// and a boolean to check if the value has been set.
func (o *AgentTypeResponse) GetSubtypesOk() ([]AgentTypeSubtype, bool) {
	if o == nil {
		return nil, false
	}
	return o.Subtypes, true
}

// SetSubtypes sets field value
func (o *AgentTypeResponse) SetSubtypes(v []AgentTypeSubtype) {
	o.Subtypes = v
}

func (o AgentTypeResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentTypeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["displayName"] = o.DisplayName
	toSerialize["description"] = o.Description
	toSerialize["subtypes"] = o.Subtypes
	return toSerialize, nil
}

type NullableAgentTypeResponse struct {
	value *AgentTypeResponse
	isSet bool
}

func (v NullableAgentTypeResponse) Get() *AgentTypeResponse {
	return v.value
}

func (v *NullableAgentTypeResponse) Set(val *AgentTypeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentTypeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentTypeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentTypeResponse(val *AgentTypeResponse) *NullableAgentTypeResponse {
	return &NullableAgentTypeResponse{value: val, isSet: true}
}

func (v NullableAgentTypeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentTypeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
