/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the OrganizationListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationListResponse{}

// OrganizationListResponse struct for OrganizationListResponse
type OrganizationListResponse struct {
	Organizations []OrganizationListItem `json:"organizations"`
	// Total number of organizations matching the query
	Total  int32 `json:"total"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// NewOrganizationListResponse instantiates a new OrganizationListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationListResponse(organizations []OrganizationListItem, total int32, limit int32, offset int32) *OrganizationListResponse {
	this := OrganizationListResponse{}
	this.Organizations = organizations
	this.Total = total
	this.Limit = limit
	this.Offset = offset
	return &this
}

// NewOrganizationListResponseWithDefaults instantiates a new OrganizationListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationListResponseWithDefaults() *OrganizationListResponse {
	this := OrganizationListResponse{}
	return &this
}

// GetOrganizations returns the Organizations field value
func (o *OrganizationListResponse) GetOrganizations() []OrganizationListItem {
	if o == nil {
		var ret []OrganizationListItem
		return ret
	}

	return o.Organizations
}

// GetOrganizationsOk returns a tuple with the Organizations field value
// and a boolean to check if the value has been set.
func (o *OrganizationListResponse) GetOrganizationsOk() ([]OrganizationListItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Organizations, true
}

// SetOrganizations sets field value
func (o *OrganizationListResponse) SetOrganizations(v []OrganizationListItem) {
	o.Organizations = v
}

// GetTotal returns the Total field value
func (o *OrganizationListResponse) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *OrganizationListResponse) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *OrganizationListResponse) SetTotal(v int32) {
	o.Total = v
}

// GetLimit returns the Limit field value
func (o *OrganizationListResponse) GetLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *OrganizationListResponse) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *OrganizationListResponse) SetLimit(v int32) {
	o.Limit = v
}

// GetOffset returns the Offset field value
func (o *OrganizationListResponse) GetOffset() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value
// and a boolean to check if the value has been set.
func (o *OrganizationListResponse) GetOffsetOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Offset, true
}

// SetOffset sets field value
func (o *OrganizationListResponse) SetOffset(v int32) {
	o.Offset = v
}

func (o OrganizationListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["organizations"] = o.Organizations
	toSerialize["total"] = o.Total
	toSerialize["limit"] = o.Limit
	toSerialize["offset"] = o.Offset
	return toSerialize, nil
}

type NullableOrganizationListResponse struct {
	value *OrganizationListResponse
	isSet bool
}

func (v NullableOrganizationListResponse) Get() *OrganizationListResponse {
	return v.value
}

func (v *NullableOrganizationListResponse) Set(val *OrganizationListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationListResponse(val *OrganizationListResponse) *NullableOrganizationListResponse {
	return &NullableOrganizationListResponse{value: val, isSet: true}
}

func (v NullableOrganizationListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
