/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
	"time"
)

// checks if the BuildStep type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BuildStep{}

// BuildStep struct for BuildStep
type BuildStep struct {
	// Type of build step
	Type string `json:"type"`
	// Status of the build step
	Status string `json:"status"`
	// Human-readable message about the step
	Message string `json:"message"`
	// Timestamp when the step occurred
	At time.Time `json:"at"`
}

// NewBuildStep instantiates a new BuildStep object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBuildStep(type_ string, status string, message string, at time.Time) *BuildStep {
	this := BuildStep{}
	this.Type = type_
	this.Status = status
	this.Message = message
	this.At = at
	return &this
}

// NewBuildStepWithDefaults instantiates a new BuildStep object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBuildStepWithDefaults() *BuildStep {
	this := BuildStep{}
	return &this
}

// GetType returns the Type field value
func (o *BuildStep) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *BuildStep) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *BuildStep) SetType(v string) {
	o.Type = v
}

// GetStatus returns the Status field value
func (o *BuildStep) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *BuildStep) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *BuildStep) SetStatus(v string) {
	o.Status = v
}

// GetMessage returns the Message field value
func (o *BuildStep) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *BuildStep) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *BuildStep) SetMessage(v string) {
	o.Message = v
}

// GetAt returns the At field value
func (o *BuildStep) GetAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.At
}

// GetAtOk returns a tuple with the At field value
// and a boolean to check if the value has been set.
func (o *BuildStep) GetAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.At, true
}

// SetAt sets field value
func (o *BuildStep) SetAt(v time.Time) {
	o.At = v
}

func (o BuildStep) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BuildStep) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["status"] = o.Status
	toSerialize["message"] = o.Message
	toSerialize["at"] = o.At
	return toSerialize, nil
}

type NullableBuildStep struct {
	value *BuildStep
	isSet bool
}

func (v NullableBuildStep) Get() *BuildStep {
	return v.value
}

func (v *NullableBuildStep) Set(val *BuildStep) {
	v.value = val
	v.isSet = true
}

func (v NullableBuildStep) IsSet() bool {
	return v.isSet
}

func (v *NullableBuildStep) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBuildStep(val *BuildStep) *NullableBuildStep {
	return &NullableBuildStep{value: val, isSet: true}
}

func (v NullableBuildStep) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBuildStep) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
