/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the EnvironmentObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnvironmentObject{}

// EnvironmentObject struct for EnvironmentObject
type EnvironmentObject struct {
	// Environment name
	Name string `json:"name"`
	// Human-readable display name of the environment
	DisplayName string `json:"displayName"`
}

// NewEnvironmentObject instantiates a new EnvironmentObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironmentObject(name string, displayName string) *EnvironmentObject {
	this := EnvironmentObject{}
	this.Name = name
	this.DisplayName = displayName
	return &this
}

// NewEnvironmentObjectWithDefaults instantiates a new EnvironmentObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvironmentObjectWithDefaults() *EnvironmentObject {
	this := EnvironmentObject{}
	return &this
}

// GetName returns the Name field value
func (o *EnvironmentObject) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *EnvironmentObject) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *EnvironmentObject) SetName(v string) {
	o.Name = v
}

// GetDisplayName returns the DisplayName field value
func (o *EnvironmentObject) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *EnvironmentObject) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *EnvironmentObject) SetDisplayName(v string) {
	o.DisplayName = v
}

func (o EnvironmentObject) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnvironmentObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["displayName"] = o.DisplayName
	return toSerialize, nil
}

type NullableEnvironmentObject struct {
	value *EnvironmentObject
	isSet bool
}

func (v NullableEnvironmentObject) Get() *EnvironmentObject {
	return v.value
}

func (v *NullableEnvironmentObject) Set(val *EnvironmentObject) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironmentObject) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironmentObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironmentObject(val *EnvironmentObject) *NullableEnvironmentObject {
	return &NullableEnvironmentObject{value: val, isSet: true}
}

func (v NullableEnvironmentObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironmentObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
