/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the CreateAgentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAgentRequest{}

// CreateAgentRequest struct for CreateAgentRequest
type CreateAgentRequest struct {
	Provisioning Provisioning `json:"provisioning"`
	// Unique name of the agent
	Name string `json:"name"`
	// Display name of the agent
	DisplayName string `json:"displayName"`
	// Description of the agent
	Description    *string               `json:"description,omitempty"`
	RuntimeConfigs *RuntimeConfiguration `json:"runtimeConfigs,omitempty"`
	InputInterface *InputInterface       `json:"inputInterface,omitempty"`
}

// NewCreateAgentRequest instantiates a new CreateAgentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAgentRequest(provisioning Provisioning, name string, displayName string) *CreateAgentRequest {
	this := CreateAgentRequest{}
	this.Provisioning = provisioning
	this.Name = name
	this.DisplayName = displayName
	return &this
}

// NewCreateAgentRequestWithDefaults instantiates a new CreateAgentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAgentRequestWithDefaults() *CreateAgentRequest {
	this := CreateAgentRequest{}
	return &this
}

// GetProvisioning returns the Provisioning field value
func (o *CreateAgentRequest) GetProvisioning() Provisioning {
	if o == nil {
		var ret Provisioning
		return ret
	}

	return o.Provisioning
}

// GetProvisioningOk returns a tuple with the Provisioning field value
// and a boolean to check if the value has been set.
func (o *CreateAgentRequest) GetProvisioningOk() (*Provisioning, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provisioning, true
}

// SetProvisioning sets field value
func (o *CreateAgentRequest) SetProvisioning(v Provisioning) {
	o.Provisioning = v
}

// GetName returns the Name field value
func (o *CreateAgentRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateAgentRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateAgentRequest) SetName(v string) {
	o.Name = v
}

// GetDisplayName returns the DisplayName field value
func (o *CreateAgentRequest) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *CreateAgentRequest) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *CreateAgentRequest) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateAgentRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAgentRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateAgentRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateAgentRequest) SetDescription(v string) {
	o.Description = &v
}

// GetRuntimeConfigs returns the RuntimeConfigs field value if set, zero value otherwise.
func (o *CreateAgentRequest) GetRuntimeConfigs() RuntimeConfiguration {
	if o == nil || IsNil(o.RuntimeConfigs) {
		var ret RuntimeConfiguration
		return ret
	}
	return *o.RuntimeConfigs
}

// GetRuntimeConfigsOk returns a tuple with the RuntimeConfigs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAgentRequest) GetRuntimeConfigsOk() (*RuntimeConfiguration, bool) {
	if o == nil || IsNil(o.RuntimeConfigs) {
		return nil, false
	}
	return o.RuntimeConfigs, true
}

// HasRuntimeConfigs returns a boolean if a field has been set.
func (o *CreateAgentRequest) HasRuntimeConfigs() bool {
	if o != nil && !IsNil(o.RuntimeConfigs) {
		return true
	}

	return false
}

// SetRuntimeConfigs gets a reference to the given RuntimeConfiguration and assigns it to the RuntimeConfigs field.
func (o *CreateAgentRequest) SetRuntimeConfigs(v RuntimeConfiguration) {
	o.RuntimeConfigs = &v
}

// GetInputInterface returns the InputInterface field value if set, zero value otherwise.
func (o *CreateAgentRequest) GetInputInterface() InputInterface {
	if o == nil || IsNil(o.InputInterface) {
		var ret InputInterface
		return ret
	}
	return *o.InputInterface
}

// GetInputInterfaceOk returns a tuple with the InputInterface field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAgentRequest) GetInputInterfaceOk() (*InputInterface, bool) {
	if o == nil || IsNil(o.InputInterface) {
		return nil, false
	}
	return o.InputInterface, true
}

// HasInputInterface returns a boolean if a field has been set.
func (o *CreateAgentRequest) HasInputInterface() bool {
	if o != nil && !IsNil(o.InputInterface) {
		return true
	}

	return false
}

// SetInputInterface gets a reference to the given InputInterface and assigns it to the InputInterface field.
func (o *CreateAgentRequest) SetInputInterface(v InputInterface) {
	o.InputInterface = &v
}

func (o CreateAgentRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAgentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["provisioning"] = o.Provisioning
	toSerialize["name"] = o.Name
	toSerialize["displayName"] = o.DisplayName
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.RuntimeConfigs) {
		toSerialize["runtimeConfigs"] = o.RuntimeConfigs
	}
	if !IsNil(o.InputInterface) {
		toSerialize["inputInterface"] = o.InputInterface
	}
	return toSerialize, nil
}

type NullableCreateAgentRequest struct {
	value *CreateAgentRequest
	isSet bool
}

func (v NullableCreateAgentRequest) Get() *CreateAgentRequest {
	return v.value
}

func (v *NullableCreateAgentRequest) Set(val *CreateAgentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAgentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAgentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAgentRequest(val *CreateAgentRequest) *NullableCreateAgentRequest {
	return &NullableCreateAgentRequest{value: val, isSet: true}
}

func (v NullableCreateAgentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAgentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
