/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
	"time"
)

// checks if the Environment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Environment{}

// Environment struct for Environment
type Environment struct {
	// Unique identifier of the environment
	Uuid string `json:"uuid"`
	// Name of the environment
	Name string `json:"name"`
	// Reference to the data plane for the environment
	DataplaneRef string `json:"dataplaneRef"`
	// Human-readable display name
	DisplayName *string `json:"displayName,omitempty"`
	// Whether this is a production environment
	IsProduction bool `json:"isProduction"`
	// DNS prefix for the environment
	DnsPrefix *string `json:"dnsPrefix,omitempty"`
	// Timestamp when the environment was created
	CreatedAt time.Time `json:"createdAt"`
}

// NewEnvironment instantiates a new Environment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironment(uuid string, name string, dataplaneRef string, isProduction bool, createdAt time.Time) *Environment {
	this := Environment{}
	this.Uuid = uuid
	this.Name = name
	this.DataplaneRef = dataplaneRef
	this.IsProduction = isProduction
	this.CreatedAt = createdAt
	return &this
}

// NewEnvironmentWithDefaults instantiates a new Environment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvironmentWithDefaults() *Environment {
	this := Environment{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *Environment) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *Environment) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *Environment) SetUuid(v string) {
	o.Uuid = v
}

// GetName returns the Name field value
func (o *Environment) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Environment) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Environment) SetName(v string) {
	o.Name = v
}

// GetDataplaneRef returns the DataplaneRef field value
func (o *Environment) GetDataplaneRef() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DataplaneRef
}

// GetDataplaneRefOk returns a tuple with the DataplaneRef field value
// and a boolean to check if the value has been set.
func (o *Environment) GetDataplaneRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DataplaneRef, true
}

// SetDataplaneRef sets field value
func (o *Environment) SetDataplaneRef(v string) {
	o.DataplaneRef = v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *Environment) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Environment) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *Environment) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *Environment) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetIsProduction returns the IsProduction field value
func (o *Environment) GetIsProduction() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsProduction
}

// GetIsProductionOk returns a tuple with the IsProduction field value
// and a boolean to check if the value has been set.
func (o *Environment) GetIsProductionOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsProduction, true
}

// SetIsProduction sets field value
func (o *Environment) SetIsProduction(v bool) {
	o.IsProduction = v
}

// GetDnsPrefix returns the DnsPrefix field value if set, zero value otherwise.
func (o *Environment) GetDnsPrefix() string {
	if o == nil || IsNil(o.DnsPrefix) {
		var ret string
		return ret
	}
	return *o.DnsPrefix
}

// GetDnsPrefixOk returns a tuple with the DnsPrefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Environment) GetDnsPrefixOk() (*string, bool) {
	if o == nil || IsNil(o.DnsPrefix) {
		return nil, false
	}
	return o.DnsPrefix, true
}

// HasDnsPrefix returns a boolean if a field has been set.
func (o *Environment) HasDnsPrefix() bool {
	if o != nil && !IsNil(o.DnsPrefix) {
		return true
	}

	return false
}

// SetDnsPrefix gets a reference to the given string and assigns it to the DnsPrefix field.
func (o *Environment) SetDnsPrefix(v string) {
	o.DnsPrefix = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Environment) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Environment) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Environment) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o Environment) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Environment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	toSerialize["name"] = o.Name
	toSerialize["dataplaneRef"] = o.DataplaneRef
	if !IsNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	toSerialize["isProduction"] = o.IsProduction
	if !IsNil(o.DnsPrefix) {
		toSerialize["dnsPrefix"] = o.DnsPrefix
	}
	toSerialize["createdAt"] = o.CreatedAt
	return toSerialize, nil
}

type NullableEnvironment struct {
	value *Environment
	isSet bool
}

func (v NullableEnvironment) Get() *Environment {
	return v.value
}

func (v *NullableEnvironment) Set(val *Environment) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironment) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironment(val *Environment) *NullableEnvironment {
	return &NullableEnvironment{value: val, isSet: true}
}

func (v NullableEnvironment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
