/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the AgentTypeSubtype type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentTypeSubtype{}

// AgentTypeSubtype struct for AgentTypeSubtype
type AgentTypeSubtype struct {
	// Name of the agent subtype
	Name string `json:"name"`
	// Display name of the agent subtype
	DisplayName string `json:"displayName"`
	// Description of the agent subtype
	Description string `json:"description"`
}

// NewAgentTypeSubtype instantiates a new AgentTypeSubtype object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentTypeSubtype(name string, displayName string, description string) *AgentTypeSubtype {
	this := AgentTypeSubtype{}
	this.Name = name
	this.DisplayName = displayName
	this.Description = description
	return &this
}

// NewAgentTypeSubtypeWithDefaults instantiates a new AgentTypeSubtype object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentTypeSubtypeWithDefaults() *AgentTypeSubtype {
	this := AgentTypeSubtype{}
	return &this
}

// GetName returns the Name field value
func (o *AgentTypeSubtype) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AgentTypeSubtype) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AgentTypeSubtype) SetName(v string) {
	o.Name = v
}

// GetDisplayName returns the DisplayName field value
func (o *AgentTypeSubtype) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *AgentTypeSubtype) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *AgentTypeSubtype) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetDescription returns the Description field value
func (o *AgentTypeSubtype) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *AgentTypeSubtype) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *AgentTypeSubtype) SetDescription(v string) {
	o.Description = v
}

func (o AgentTypeSubtype) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentTypeSubtype) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["displayName"] = o.DisplayName
	toSerialize["description"] = o.Description
	return toSerialize, nil
}

type NullableAgentTypeSubtype struct {
	value *AgentTypeSubtype
	isSet bool
}

func (v NullableAgentTypeSubtype) Get() *AgentTypeSubtype {
	return v.value
}

func (v *NullableAgentTypeSubtype) Set(val *AgentTypeSubtype) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentTypeSubtype) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentTypeSubtype) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentTypeSubtype(val *AgentTypeSubtype) *NullableAgentTypeSubtype {
	return &NullableAgentTypeSubtype{value: val, isSet: true}
}

func (v NullableAgentTypeSubtype) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentTypeSubtype) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
