/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the InputInterface type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InputInterface{}

// InputInterface Endpoint configurations
type InputInterface struct {
	// Port number
	Port   int32                `json:"port"`
	Schema InputInterfaceSchema `json:"schema"`
	// Base path for the endpoint
	BasePath string `json:"basePath"`
}

// NewInputInterface instantiates a new InputInterface object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInputInterface(port int32, schema InputInterfaceSchema, basePath string) *InputInterface {
	this := InputInterface{}
	this.Port = port
	this.Schema = schema
	this.BasePath = basePath
	return &this
}

// NewInputInterfaceWithDefaults instantiates a new InputInterface object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInputInterfaceWithDefaults() *InputInterface {
	this := InputInterface{}
	return &this
}

// GetPort returns the Port field value
func (o *InputInterface) GetPort() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Port
}

// GetPortOk returns a tuple with the Port field value
// and a boolean to check if the value has been set.
func (o *InputInterface) GetPortOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Port, true
}

// SetPort sets field value
func (o *InputInterface) SetPort(v int32) {
	o.Port = v
}

// GetSchema returns the Schema field value
func (o *InputInterface) GetSchema() InputInterfaceSchema {
	if o == nil {
		var ret InputInterfaceSchema
		return ret
	}

	return o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value
// and a boolean to check if the value has been set.
func (o *InputInterface) GetSchemaOk() (*InputInterfaceSchema, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Schema, true
}

// SetSchema sets field value
func (o *InputInterface) SetSchema(v InputInterfaceSchema) {
	o.Schema = v
}

// GetBasePath returns the BasePath field value
func (o *InputInterface) GetBasePath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BasePath
}

// GetBasePathOk returns a tuple with the BasePath field value
// and a boolean to check if the value has been set.
func (o *InputInterface) GetBasePathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BasePath, true
}

// SetBasePath sets field value
func (o *InputInterface) SetBasePath(v string) {
	o.BasePath = v
}

func (o InputInterface) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InputInterface) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["port"] = o.Port
	toSerialize["schema"] = o.Schema
	toSerialize["basePath"] = o.BasePath
	return toSerialize, nil
}

type NullableInputInterface struct {
	value *InputInterface
	isSet bool
}

func (v NullableInputInterface) Get() *InputInterface {
	return v.value
}

func (v *NullableInputInterface) Set(val *InputInterface) {
	v.value = val
	v.isSet = true
}

func (v NullableInputInterface) IsSet() bool {
	return v.isSet
}

func (v *NullableInputInterface) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputInterface(val *InputInterface) *NullableInputInterface {
	return &NullableInputInterface{value: val, isSet: true}
}

func (v NullableInputInterface) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputInterface) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
