/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
	"time"
)

// checks if the DeploymentDetailsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeploymentDetailsResponse{}

// DeploymentDetailsResponse struct for DeploymentDetailsResponse
type DeploymentDetailsResponse struct {
	// Container image ID
	ImageId string `json:"imageId"`
	// Deployment status
	Status string `json:"status"`
	// Timestamp of last deployment
	LastDeployed time.Time `json:"lastDeployed"`
	// List of deployment endpoints
	Endpoints         []DeploymentEndpoint `json:"endpoints"`
	SourceEnvironment EnvironmentObject    `json:"sourceEnvironment"`
	// Environment display name
	EnvironmentDisplayName     *string                                              `json:"environmentDisplayName,omitempty"`
	PromotionTargetEnvironment *DeploymentDetailsResponsePromotionTargetEnvironment `json:"promotionTargetEnvironment,omitempty"`
}

// NewDeploymentDetailsResponse instantiates a new DeploymentDetailsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeploymentDetailsResponse(imageId string, status string, lastDeployed time.Time, endpoints []DeploymentEndpoint, sourceEnvironment EnvironmentObject) *DeploymentDetailsResponse {
	this := DeploymentDetailsResponse{}
	this.ImageId = imageId
	this.Status = status
	this.LastDeployed = lastDeployed
	this.Endpoints = endpoints
	this.SourceEnvironment = sourceEnvironment
	return &this
}

// NewDeploymentDetailsResponseWithDefaults instantiates a new DeploymentDetailsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeploymentDetailsResponseWithDefaults() *DeploymentDetailsResponse {
	this := DeploymentDetailsResponse{}
	return &this
}

// GetImageId returns the ImageId field value
func (o *DeploymentDetailsResponse) GetImageId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ImageId
}

// GetImageIdOk returns a tuple with the ImageId field value
// and a boolean to check if the value has been set.
func (o *DeploymentDetailsResponse) GetImageIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImageId, true
}

// SetImageId sets field value
func (o *DeploymentDetailsResponse) SetImageId(v string) {
	o.ImageId = v
}

// GetStatus returns the Status field value
func (o *DeploymentDetailsResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *DeploymentDetailsResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *DeploymentDetailsResponse) SetStatus(v string) {
	o.Status = v
}

// GetLastDeployed returns the LastDeployed field value
func (o *DeploymentDetailsResponse) GetLastDeployed() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastDeployed
}

// GetLastDeployedOk returns a tuple with the LastDeployed field value
// and a boolean to check if the value has been set.
func (o *DeploymentDetailsResponse) GetLastDeployedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastDeployed, true
}

// SetLastDeployed sets field value
func (o *DeploymentDetailsResponse) SetLastDeployed(v time.Time) {
	o.LastDeployed = v
}

// GetEndpoints returns the Endpoints field value
func (o *DeploymentDetailsResponse) GetEndpoints() []DeploymentEndpoint {
	if o == nil {
		var ret []DeploymentEndpoint
		return ret
	}

	return o.Endpoints
}

// GetEndpointsOk returns a tuple with the Endpoints field value
// and a boolean to check if the value has been set.
func (o *DeploymentDetailsResponse) GetEndpointsOk() ([]DeploymentEndpoint, bool) {
	if o == nil {
		return nil, false
	}
	return o.Endpoints, true
}

// SetEndpoints sets field value
func (o *DeploymentDetailsResponse) SetEndpoints(v []DeploymentEndpoint) {
	o.Endpoints = v
}

// GetSourceEnvironment returns the SourceEnvironment field value
func (o *DeploymentDetailsResponse) GetSourceEnvironment() EnvironmentObject {
	if o == nil {
		var ret EnvironmentObject
		return ret
	}

	return o.SourceEnvironment
}

// GetSourceEnvironmentOk returns a tuple with the SourceEnvironment field value
// and a boolean to check if the value has been set.
func (o *DeploymentDetailsResponse) GetSourceEnvironmentOk() (*EnvironmentObject, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceEnvironment, true
}

// SetSourceEnvironment sets field value
func (o *DeploymentDetailsResponse) SetSourceEnvironment(v EnvironmentObject) {
	o.SourceEnvironment = v
}

// GetEnvironmentDisplayName returns the EnvironmentDisplayName field value if set, zero value otherwise.
func (o *DeploymentDetailsResponse) GetEnvironmentDisplayName() string {
	if o == nil || IsNil(o.EnvironmentDisplayName) {
		var ret string
		return ret
	}
	return *o.EnvironmentDisplayName
}

// GetEnvironmentDisplayNameOk returns a tuple with the EnvironmentDisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentDetailsResponse) GetEnvironmentDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.EnvironmentDisplayName) {
		return nil, false
	}
	return o.EnvironmentDisplayName, true
}

// HasEnvironmentDisplayName returns a boolean if a field has been set.
func (o *DeploymentDetailsResponse) HasEnvironmentDisplayName() bool {
	if o != nil && !IsNil(o.EnvironmentDisplayName) {
		return true
	}

	return false
}

// SetEnvironmentDisplayName gets a reference to the given string and assigns it to the EnvironmentDisplayName field.
func (o *DeploymentDetailsResponse) SetEnvironmentDisplayName(v string) {
	o.EnvironmentDisplayName = &v
}

// GetPromotionTargetEnvironment returns the PromotionTargetEnvironment field value if set, zero value otherwise.
func (o *DeploymentDetailsResponse) GetPromotionTargetEnvironment() DeploymentDetailsResponsePromotionTargetEnvironment {
	if o == nil || IsNil(o.PromotionTargetEnvironment) {
		var ret DeploymentDetailsResponsePromotionTargetEnvironment
		return ret
	}
	return *o.PromotionTargetEnvironment
}

// GetPromotionTargetEnvironmentOk returns a tuple with the PromotionTargetEnvironment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentDetailsResponse) GetPromotionTargetEnvironmentOk() (*DeploymentDetailsResponsePromotionTargetEnvironment, bool) {
	if o == nil || IsNil(o.PromotionTargetEnvironment) {
		return nil, false
	}
	return o.PromotionTargetEnvironment, true
}

// HasPromotionTargetEnvironment returns a boolean if a field has been set.
func (o *DeploymentDetailsResponse) HasPromotionTargetEnvironment() bool {
	if o != nil && !IsNil(o.PromotionTargetEnvironment) {
		return true
	}

	return false
}

// SetPromotionTargetEnvironment gets a reference to the given DeploymentDetailsResponsePromotionTargetEnvironment and assigns it to the PromotionTargetEnvironment field.
func (o *DeploymentDetailsResponse) SetPromotionTargetEnvironment(v DeploymentDetailsResponsePromotionTargetEnvironment) {
	o.PromotionTargetEnvironment = &v
}

func (o DeploymentDetailsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeploymentDetailsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["imageId"] = o.ImageId
	toSerialize["status"] = o.Status
	toSerialize["lastDeployed"] = o.LastDeployed
	toSerialize["endpoints"] = o.Endpoints
	toSerialize["sourceEnvironment"] = o.SourceEnvironment
	if !IsNil(o.EnvironmentDisplayName) {
		toSerialize["environmentDisplayName"] = o.EnvironmentDisplayName
	}
	if !IsNil(o.PromotionTargetEnvironment) {
		toSerialize["promotionTargetEnvironment"] = o.PromotionTargetEnvironment
	}
	return toSerialize, nil
}

type NullableDeploymentDetailsResponse struct {
	value *DeploymentDetailsResponse
	isSet bool
}

func (v NullableDeploymentDetailsResponse) Get() *DeploymentDetailsResponse {
	return v.value
}

func (v *NullableDeploymentDetailsResponse) Set(val *DeploymentDetailsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentDetailsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentDetailsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentDetailsResponse(val *DeploymentDetailsResponse) *NullableDeploymentDetailsResponse {
	return &NullableDeploymentDetailsResponse{value: val, isSet: true}
}

func (v NullableDeploymentDetailsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentDetailsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
