/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the EndpointSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EndpointSpec{}

// EndpointSpec struct for EndpointSpec
type EndpointSpec struct {
	// Port number
	Port   int32          `json:"port"`
	Schema EndpointSchema `json:"schema"`
	// Base path for the endpoint
	BasePath string `json:"basePath"`
}

// NewEndpointSpec instantiates a new EndpointSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEndpointSpec(port int32, schema EndpointSchema, basePath string) *EndpointSpec {
	this := EndpointSpec{}
	this.Port = port
	this.Schema = schema
	this.BasePath = basePath
	return &this
}

// NewEndpointSpecWithDefaults instantiates a new EndpointSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEndpointSpecWithDefaults() *EndpointSpec {
	this := EndpointSpec{}
	return &this
}

// GetPort returns the Port field value
func (o *EndpointSpec) GetPort() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Port
}

// GetPortOk returns a tuple with the Port field value
// and a boolean to check if the value has been set.
func (o *EndpointSpec) GetPortOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Port, true
}

// SetPort sets field value
func (o *EndpointSpec) SetPort(v int32) {
	o.Port = v
}

// GetSchema returns the Schema field value
func (o *EndpointSpec) GetSchema() EndpointSchema {
	if o == nil {
		var ret EndpointSchema
		return ret
	}

	return o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value
// and a boolean to check if the value has been set.
func (o *EndpointSpec) GetSchemaOk() (*EndpointSchema, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Schema, true
}

// SetSchema sets field value
func (o *EndpointSpec) SetSchema(v EndpointSchema) {
	o.Schema = v
}

// GetBasePath returns the BasePath field value
func (o *EndpointSpec) GetBasePath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BasePath
}

// GetBasePathOk returns a tuple with the BasePath field value
// and a boolean to check if the value has been set.
func (o *EndpointSpec) GetBasePathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BasePath, true
}

// SetBasePath sets field value
func (o *EndpointSpec) SetBasePath(v string) {
	o.BasePath = v
}

func (o EndpointSpec) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EndpointSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["port"] = o.Port
	toSerialize["schema"] = o.Schema
	toSerialize["basePath"] = o.BasePath
	return toSerialize, nil
}

type NullableEndpointSpec struct {
	value *EndpointSpec
	isSet bool
}

func (v NullableEndpointSpec) Get() *EndpointSpec {
	return v.value
}

func (v *NullableEndpointSpec) Set(val *EndpointSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableEndpointSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableEndpointSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndpointSpec(val *EndpointSpec) *NullableEndpointSpec {
	return &NullableEndpointSpec{value: val, isSet: true}
}

func (v NullableEndpointSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndpointSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
