/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
	"time"
)

// checks if the DeploymentPipelineResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeploymentPipelineResponse{}

// DeploymentPipelineResponse struct for DeploymentPipelineResponse
type DeploymentPipelineResponse struct {
	// Name of the deployment pipeline
	Name string `json:"name"`
	// Human-readable display name
	DisplayName string `json:"displayName"`
	// Description of the deployment pipeline
	Description string `json:"description"`
	// Organization name
	OrgName string `json:"orgName"`
	// Timestamp when the pipeline was created
	CreatedAt time.Time `json:"createdAt"`
	// List of promotion paths in the pipeline
	PromotionPaths []PromotionPath `json:"promotionPaths"`
}

// NewDeploymentPipelineResponse instantiates a new DeploymentPipelineResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeploymentPipelineResponse(name string, displayName string, description string, orgName string, createdAt time.Time, promotionPaths []PromotionPath) *DeploymentPipelineResponse {
	this := DeploymentPipelineResponse{}
	this.Name = name
	this.DisplayName = displayName
	this.Description = description
	this.OrgName = orgName
	this.CreatedAt = createdAt
	this.PromotionPaths = promotionPaths
	return &this
}

// NewDeploymentPipelineResponseWithDefaults instantiates a new DeploymentPipelineResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeploymentPipelineResponseWithDefaults() *DeploymentPipelineResponse {
	this := DeploymentPipelineResponse{}
	return &this
}

// GetName returns the Name field value
func (o *DeploymentPipelineResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DeploymentPipelineResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DeploymentPipelineResponse) SetName(v string) {
	o.Name = v
}

// GetDisplayName returns the DisplayName field value
func (o *DeploymentPipelineResponse) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *DeploymentPipelineResponse) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *DeploymentPipelineResponse) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetDescription returns the Description field value
func (o *DeploymentPipelineResponse) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *DeploymentPipelineResponse) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *DeploymentPipelineResponse) SetDescription(v string) {
	o.Description = v
}

// GetOrgName returns the OrgName field value
func (o *DeploymentPipelineResponse) GetOrgName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgName
}

// GetOrgNameOk returns a tuple with the OrgName field value
// and a boolean to check if the value has been set.
func (o *DeploymentPipelineResponse) GetOrgNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgName, true
}

// SetOrgName sets field value
func (o *DeploymentPipelineResponse) SetOrgName(v string) {
	o.OrgName = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *DeploymentPipelineResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *DeploymentPipelineResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *DeploymentPipelineResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetPromotionPaths returns the PromotionPaths field value
func (o *DeploymentPipelineResponse) GetPromotionPaths() []PromotionPath {
	if o == nil {
		var ret []PromotionPath
		return ret
	}

	return o.PromotionPaths
}

// GetPromotionPathsOk returns a tuple with the PromotionPaths field value
// and a boolean to check if the value has been set.
func (o *DeploymentPipelineResponse) GetPromotionPathsOk() ([]PromotionPath, bool) {
	if o == nil {
		return nil, false
	}
	return o.PromotionPaths, true
}

// SetPromotionPaths sets field value
func (o *DeploymentPipelineResponse) SetPromotionPaths(v []PromotionPath) {
	o.PromotionPaths = v
}

func (o DeploymentPipelineResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeploymentPipelineResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["displayName"] = o.DisplayName
	toSerialize["description"] = o.Description
	toSerialize["orgName"] = o.OrgName
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["promotionPaths"] = o.PromotionPaths
	return toSerialize, nil
}

type NullableDeploymentPipelineResponse struct {
	value *DeploymentPipelineResponse
	isSet bool
}

func (v NullableDeploymentPipelineResponse) Get() *DeploymentPipelineResponse {
	return v.value
}

func (v *NullableDeploymentPipelineResponse) Set(val *DeploymentPipelineResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentPipelineResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentPipelineResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentPipelineResponse(val *DeploymentPipelineResponse) *NullableDeploymentPipelineResponse {
	return &NullableDeploymentPipelineResponse{value: val, isSet: true}
}

func (v NullableDeploymentPipelineResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentPipelineResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
