/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the RuntimeConfiguration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RuntimeConfiguration{}

// RuntimeConfiguration struct for RuntimeConfiguration
type RuntimeConfiguration struct {
	// Environment variables
	Env             []EnvironmentVariable `json:"env,omitempty"`
	RunCommand      *string               `json:"runCommand,omitempty"`
	LanguageVersion *string               `json:"languageVersion,omitempty"`
	Language        string                `json:"language"`
}

// NewRuntimeConfiguration instantiates a new RuntimeConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRuntimeConfiguration(language string) *RuntimeConfiguration {
	this := RuntimeConfiguration{}
	this.Language = language
	return &this
}

// NewRuntimeConfigurationWithDefaults instantiates a new RuntimeConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRuntimeConfigurationWithDefaults() *RuntimeConfiguration {
	this := RuntimeConfiguration{}
	return &this
}

// GetEnv returns the Env field value if set, zero value otherwise.
func (o *RuntimeConfiguration) GetEnv() []EnvironmentVariable {
	if o == nil || IsNil(o.Env) {
		var ret []EnvironmentVariable
		return ret
	}
	return o.Env
}

// GetEnvOk returns a tuple with the Env field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RuntimeConfiguration) GetEnvOk() ([]EnvironmentVariable, bool) {
	if o == nil || IsNil(o.Env) {
		return nil, false
	}
	return o.Env, true
}

// HasEnv returns a boolean if a field has been set.
func (o *RuntimeConfiguration) HasEnv() bool {
	if o != nil && !IsNil(o.Env) {
		return true
	}

	return false
}

// SetEnv gets a reference to the given []EnvironmentVariable and assigns it to the Env field.
func (o *RuntimeConfiguration) SetEnv(v []EnvironmentVariable) {
	o.Env = v
}

// GetRunCommand returns the RunCommand field value if set, zero value otherwise.
func (o *RuntimeConfiguration) GetRunCommand() string {
	if o == nil || IsNil(o.RunCommand) {
		var ret string
		return ret
	}
	return *o.RunCommand
}

// GetRunCommandOk returns a tuple with the RunCommand field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RuntimeConfiguration) GetRunCommandOk() (*string, bool) {
	if o == nil || IsNil(o.RunCommand) {
		return nil, false
	}
	return o.RunCommand, true
}

// HasRunCommand returns a boolean if a field has been set.
func (o *RuntimeConfiguration) HasRunCommand() bool {
	if o != nil && !IsNil(o.RunCommand) {
		return true
	}

	return false
}

// SetRunCommand gets a reference to the given string and assigns it to the RunCommand field.
func (o *RuntimeConfiguration) SetRunCommand(v string) {
	o.RunCommand = &v
}

// GetLanguageVersion returns the LanguageVersion field value if set, zero value otherwise.
func (o *RuntimeConfiguration) GetLanguageVersion() string {
	if o == nil || IsNil(o.LanguageVersion) {
		var ret string
		return ret
	}
	return *o.LanguageVersion
}

// GetLanguageVersionOk returns a tuple with the LanguageVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RuntimeConfiguration) GetLanguageVersionOk() (*string, bool) {
	if o == nil || IsNil(o.LanguageVersion) {
		return nil, false
	}
	return o.LanguageVersion, true
}

// HasLanguageVersion returns a boolean if a field has been set.
func (o *RuntimeConfiguration) HasLanguageVersion() bool {
	if o != nil && !IsNil(o.LanguageVersion) {
		return true
	}

	return false
}

// SetLanguageVersion gets a reference to the given string and assigns it to the LanguageVersion field.
func (o *RuntimeConfiguration) SetLanguageVersion(v string) {
	o.LanguageVersion = &v
}

// GetLanguage returns the Language field value
func (o *RuntimeConfiguration) GetLanguage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Language
}

// GetLanguageOk returns a tuple with the Language field value
// and a boolean to check if the value has been set.
func (o *RuntimeConfiguration) GetLanguageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Language, true
}

// SetLanguage sets field value
func (o *RuntimeConfiguration) SetLanguage(v string) {
	o.Language = v
}

func (o RuntimeConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RuntimeConfiguration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Env) {
		toSerialize["env"] = o.Env
	}
	if !IsNil(o.RunCommand) {
		toSerialize["runCommand"] = o.RunCommand
	}
	if !IsNil(o.LanguageVersion) {
		toSerialize["languageVersion"] = o.LanguageVersion
	}
	toSerialize["language"] = o.Language
	return toSerialize, nil
}

type NullableRuntimeConfiguration struct {
	value *RuntimeConfiguration
	isSet bool
}

func (v NullableRuntimeConfiguration) Get() *RuntimeConfiguration {
	return v.value
}

func (v *NullableRuntimeConfiguration) Set(val *RuntimeConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableRuntimeConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableRuntimeConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRuntimeConfiguration(val *RuntimeConfiguration) *NullableRuntimeConfiguration {
	return &NullableRuntimeConfiguration{value: val, isSet: true}
}

func (v NullableRuntimeConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRuntimeConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
