/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
	"time"
)

// checks if the OrganizationListItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationListItem{}

// OrganizationListItem struct for OrganizationListItem
type OrganizationListItem struct {
	// Name of the organization
	Name string `json:"name"`
	// Timestamp when the organization was created
	CreatedAt time.Time `json:"createdAt"`
}

// NewOrganizationListItem instantiates a new OrganizationListItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationListItem(name string, createdAt time.Time) *OrganizationListItem {
	this := OrganizationListItem{}
	this.Name = name
	this.CreatedAt = createdAt
	return &this
}

// NewOrganizationListItemWithDefaults instantiates a new OrganizationListItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationListItemWithDefaults() *OrganizationListItem {
	this := OrganizationListItem{}
	return &this
}

// GetName returns the Name field value
func (o *OrganizationListItem) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *OrganizationListItem) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *OrganizationListItem) SetName(v string) {
	o.Name = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *OrganizationListItem) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *OrganizationListItem) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *OrganizationListItem) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o OrganizationListItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationListItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["createdAt"] = o.CreatedAt
	return toSerialize, nil
}

type NullableOrganizationListItem struct {
	value *OrganizationListItem
	isSet bool
}

func (v NullableOrganizationListItem) Get() *OrganizationListItem {
	return v.value
}

func (v *NullableOrganizationListItem) Set(val *OrganizationListItem) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationListItem) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationListItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationListItem(val *OrganizationListItem) *NullableOrganizationListItem {
	return &NullableOrganizationListItem{value: val, isSet: true}
}

func (v NullableOrganizationListItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationListItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
