/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the DeploymentEndpoint type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeploymentEndpoint{}

// DeploymentEndpoint struct for DeploymentEndpoint
type DeploymentEndpoint struct {
	// Name of the endpoint
	Name string `json:"name"`
	// URL of the endpoint
	Url string `json:"url"`
	// Visibility level of the endpoint
	Visibility string `json:"visibility"`
}

// NewDeploymentEndpoint instantiates a new DeploymentEndpoint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeploymentEndpoint(name string, url string, visibility string) *DeploymentEndpoint {
	this := DeploymentEndpoint{}
	this.Name = name
	this.Url = url
	this.Visibility = visibility
	return &this
}

// NewDeploymentEndpointWithDefaults instantiates a new DeploymentEndpoint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeploymentEndpointWithDefaults() *DeploymentEndpoint {
	this := DeploymentEndpoint{}
	return &this
}

// GetName returns the Name field value
func (o *DeploymentEndpoint) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DeploymentEndpoint) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DeploymentEndpoint) SetName(v string) {
	o.Name = v
}

// GetUrl returns the Url field value
func (o *DeploymentEndpoint) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *DeploymentEndpoint) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *DeploymentEndpoint) SetUrl(v string) {
	o.Url = v
}

// GetVisibility returns the Visibility field value
func (o *DeploymentEndpoint) GetVisibility() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Visibility
}

// GetVisibilityOk returns a tuple with the Visibility field value
// and a boolean to check if the value has been set.
func (o *DeploymentEndpoint) GetVisibilityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Visibility, true
}

// SetVisibility sets field value
func (o *DeploymentEndpoint) SetVisibility(v string) {
	o.Visibility = v
}

func (o DeploymentEndpoint) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeploymentEndpoint) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["url"] = o.Url
	toSerialize["visibility"] = o.Visibility
	return toSerialize, nil
}

type NullableDeploymentEndpoint struct {
	value *DeploymentEndpoint
	isSet bool
}

func (v NullableDeploymentEndpoint) Get() *DeploymentEndpoint {
	return v.value
}

func (v *NullableDeploymentEndpoint) Set(val *DeploymentEndpoint) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentEndpoint) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentEndpoint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentEndpoint(val *DeploymentEndpoint) *NullableDeploymentEndpoint {
	return &NullableDeploymentEndpoint{value: val, isSet: true}
}

func (v NullableDeploymentEndpoint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentEndpoint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
