/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the EndpointConfiguration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EndpointConfiguration{}

// EndpointConfiguration struct for EndpointConfiguration
type EndpointConfiguration struct {
	// URL of the endpoint
	Url string `json:"url"`
	// Name of the endpoint
	EndpointName string         `json:"endpointName"`
	Schema       EndpointSchema `json:"schema"`
	// Visibility level of the endpoint
	Visibility string `json:"visibility"`
}

// NewEndpointConfiguration instantiates a new EndpointConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEndpointConfiguration(url string, endpointName string, schema EndpointSchema, visibility string) *EndpointConfiguration {
	this := EndpointConfiguration{}
	this.Url = url
	this.EndpointName = endpointName
	this.Schema = schema
	this.Visibility = visibility
	return &this
}

// NewEndpointConfigurationWithDefaults instantiates a new EndpointConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEndpointConfigurationWithDefaults() *EndpointConfiguration {
	this := EndpointConfiguration{}
	return &this
}

// GetUrl returns the Url field value
func (o *EndpointConfiguration) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *EndpointConfiguration) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *EndpointConfiguration) SetUrl(v string) {
	o.Url = v
}

// GetEndpointName returns the EndpointName field value
func (o *EndpointConfiguration) GetEndpointName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EndpointName
}

// GetEndpointNameOk returns a tuple with the EndpointName field value
// and a boolean to check if the value has been set.
func (o *EndpointConfiguration) GetEndpointNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndpointName, true
}

// SetEndpointName sets field value
func (o *EndpointConfiguration) SetEndpointName(v string) {
	o.EndpointName = v
}

// GetSchema returns the Schema field value
func (o *EndpointConfiguration) GetSchema() EndpointSchema {
	if o == nil {
		var ret EndpointSchema
		return ret
	}

	return o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value
// and a boolean to check if the value has been set.
func (o *EndpointConfiguration) GetSchemaOk() (*EndpointSchema, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Schema, true
}

// SetSchema sets field value
func (o *EndpointConfiguration) SetSchema(v EndpointSchema) {
	o.Schema = v
}

// GetVisibility returns the Visibility field value
func (o *EndpointConfiguration) GetVisibility() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Visibility
}

// GetVisibilityOk returns a tuple with the Visibility field value
// and a boolean to check if the value has been set.
func (o *EndpointConfiguration) GetVisibilityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Visibility, true
}

// SetVisibility sets field value
func (o *EndpointConfiguration) SetVisibility(v string) {
	o.Visibility = v
}

func (o EndpointConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EndpointConfiguration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	toSerialize["endpointName"] = o.EndpointName
	toSerialize["schema"] = o.Schema
	toSerialize["visibility"] = o.Visibility
	return toSerialize, nil
}

type NullableEndpointConfiguration struct {
	value *EndpointConfiguration
	isSet bool
}

func (v NullableEndpointConfiguration) Get() *EndpointConfiguration {
	return v.value
}

func (v *NullableEndpointConfiguration) Set(val *EndpointConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableEndpointConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableEndpointConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndpointConfiguration(val *EndpointConfiguration) *NullableEndpointConfiguration {
	return &NullableEndpointConfiguration{value: val, isSet: true}
}

func (v NullableEndpointConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndpointConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
