/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the ResourceNameRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceNameRequest{}

// ResourceNameRequest struct for ResourceNameRequest
type ResourceNameRequest struct {
	// Display name of the agent
	DisplayName string `json:"displayName"`
	// Type of resource (e.g., agent, project)
	ResourceType string `json:"resourceType"`
	// Name of the project (required if resourceType is agent)
	ProjectName *string `json:"projectName,omitempty"`
}

// NewResourceNameRequest instantiates a new ResourceNameRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceNameRequest(displayName string, resourceType string) *ResourceNameRequest {
	this := ResourceNameRequest{}
	this.DisplayName = displayName
	this.ResourceType = resourceType
	return &this
}

// NewResourceNameRequestWithDefaults instantiates a new ResourceNameRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceNameRequestWithDefaults() *ResourceNameRequest {
	this := ResourceNameRequest{}
	return &this
}

// GetDisplayName returns the DisplayName field value
func (o *ResourceNameRequest) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *ResourceNameRequest) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *ResourceNameRequest) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetResourceType returns the ResourceType field value
func (o *ResourceNameRequest) GetResourceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceType
}

// GetResourceTypeOk returns a tuple with the ResourceType field value
// and a boolean to check if the value has been set.
func (o *ResourceNameRequest) GetResourceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceType, true
}

// SetResourceType sets field value
func (o *ResourceNameRequest) SetResourceType(v string) {
	o.ResourceType = v
}

// GetProjectName returns the ProjectName field value if set, zero value otherwise.
func (o *ResourceNameRequest) GetProjectName() string {
	if o == nil || IsNil(o.ProjectName) {
		var ret string
		return ret
	}
	return *o.ProjectName
}

// GetProjectNameOk returns a tuple with the ProjectName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceNameRequest) GetProjectNameOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectName) {
		return nil, false
	}
	return o.ProjectName, true
}

// HasProjectName returns a boolean if a field has been set.
func (o *ResourceNameRequest) HasProjectName() bool {
	if o != nil && !IsNil(o.ProjectName) {
		return true
	}

	return false
}

// SetProjectName gets a reference to the given string and assigns it to the ProjectName field.
func (o *ResourceNameRequest) SetProjectName(v string) {
	o.ProjectName = &v
}

func (o ResourceNameRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourceNameRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["displayName"] = o.DisplayName
	toSerialize["resourceType"] = o.ResourceType
	if !IsNil(o.ProjectName) {
		toSerialize["projectName"] = o.ProjectName
	}
	return toSerialize, nil
}

type NullableResourceNameRequest struct {
	value *ResourceNameRequest
	isSet bool
}

func (v NullableResourceNameRequest) Get() *ResourceNameRequest {
	return v.value
}

func (v *NullableResourceNameRequest) Set(val *ResourceNameRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceNameRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceNameRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceNameRequest(val *ResourceNameRequest) *NullableResourceNameRequest {
	return &NullableResourceNameRequest{value: val, isSet: true}
}

func (v NullableResourceNameRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceNameRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
