/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the AgentListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentListResponse{}

// AgentListResponse struct for AgentListResponse
type AgentListResponse struct {
	Agents []AgentResponse `json:"agents"`
	// Total number of agents matching the query
	Total  int32 `json:"total"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// NewAgentListResponse instantiates a new AgentListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentListResponse(agents []AgentResponse, total int32, limit int32, offset int32) *AgentListResponse {
	this := AgentListResponse{}
	this.Agents = agents
	this.Total = total
	this.Limit = limit
	this.Offset = offset
	return &this
}

// NewAgentListResponseWithDefaults instantiates a new AgentListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentListResponseWithDefaults() *AgentListResponse {
	this := AgentListResponse{}
	return &this
}

// GetAgents returns the Agents field value
func (o *AgentListResponse) GetAgents() []AgentResponse {
	if o == nil {
		var ret []AgentResponse
		return ret
	}

	return o.Agents
}

// GetAgentsOk returns a tuple with the Agents field value
// and a boolean to check if the value has been set.
func (o *AgentListResponse) GetAgentsOk() ([]AgentResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Agents, true
}

// SetAgents sets field value
func (o *AgentListResponse) SetAgents(v []AgentResponse) {
	o.Agents = v
}

// GetTotal returns the Total field value
func (o *AgentListResponse) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *AgentListResponse) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *AgentListResponse) SetTotal(v int32) {
	o.Total = v
}

// GetLimit returns the Limit field value
func (o *AgentListResponse) GetLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *AgentListResponse) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *AgentListResponse) SetLimit(v int32) {
	o.Limit = v
}

// GetOffset returns the Offset field value
func (o *AgentListResponse) GetOffset() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value
// and a boolean to check if the value has been set.
func (o *AgentListResponse) GetOffsetOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Offset, true
}

// SetOffset sets field value
func (o *AgentListResponse) SetOffset(v int32) {
	o.Offset = v
}

func (o AgentListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["agents"] = o.Agents
	toSerialize["total"] = o.Total
	toSerialize["limit"] = o.Limit
	toSerialize["offset"] = o.Offset
	return toSerialize, nil
}

type NullableAgentListResponse struct {
	value *AgentListResponse
	isSet bool
}

func (v NullableAgentListResponse) Get() *AgentListResponse {
	return v.value
}

func (v *NullableAgentListResponse) Set(val *AgentListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentListResponse(val *AgentListResponse) *NullableAgentListResponse {
	return &NullableAgentListResponse{value: val, isSet: true}
}

func (v NullableAgentListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
