/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the BuildsListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BuildsListResponse{}

// BuildsListResponse struct for BuildsListResponse
type BuildsListResponse struct {
	Builds []BuildResponse `json:"builds"`
	// Total number of agents matching the query
	Total  int32 `json:"total"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// NewBuildsListResponse instantiates a new BuildsListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBuildsListResponse(builds []BuildResponse, total int32, limit int32, offset int32) *BuildsListResponse {
	this := BuildsListResponse{}
	this.Builds = builds
	this.Total = total
	this.Limit = limit
	this.Offset = offset
	return &this
}

// NewBuildsListResponseWithDefaults instantiates a new BuildsListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBuildsListResponseWithDefaults() *BuildsListResponse {
	this := BuildsListResponse{}
	return &this
}

// GetBuilds returns the Builds field value
func (o *BuildsListResponse) GetBuilds() []BuildResponse {
	if o == nil {
		var ret []BuildResponse
		return ret
	}

	return o.Builds
}

// GetBuildsOk returns a tuple with the Builds field value
// and a boolean to check if the value has been set.
func (o *BuildsListResponse) GetBuildsOk() ([]BuildResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Builds, true
}

// SetBuilds sets field value
func (o *BuildsListResponse) SetBuilds(v []BuildResponse) {
	o.Builds = v
}

// GetTotal returns the Total field value
func (o *BuildsListResponse) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *BuildsListResponse) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *BuildsListResponse) SetTotal(v int32) {
	o.Total = v
}

// GetLimit returns the Limit field value
func (o *BuildsListResponse) GetLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *BuildsListResponse) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *BuildsListResponse) SetLimit(v int32) {
	o.Limit = v
}

// GetOffset returns the Offset field value
func (o *BuildsListResponse) GetOffset() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value
// and a boolean to check if the value has been set.
func (o *BuildsListResponse) GetOffsetOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Offset, true
}

// SetOffset sets field value
func (o *BuildsListResponse) SetOffset(v int32) {
	o.Offset = v
}

func (o BuildsListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BuildsListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["builds"] = o.Builds
	toSerialize["total"] = o.Total
	toSerialize["limit"] = o.Limit
	toSerialize["offset"] = o.Offset
	return toSerialize, nil
}

type NullableBuildsListResponse struct {
	value *BuildsListResponse
	isSet bool
}

func (v NullableBuildsListResponse) Get() *BuildsListResponse {
	return v.value
}

func (v *NullableBuildsListResponse) Set(val *BuildsListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBuildsListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBuildsListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBuildsListResponse(val *BuildsListResponse) *NullableBuildsListResponse {
	return &NullableBuildsListResponse{value: val, isSet: true}
}

func (v NullableBuildsListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBuildsListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
