/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
	"time"
)

// checks if the ProjectListItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectListItem{}

// ProjectListItem struct for ProjectListItem
type ProjectListItem struct {
	// Name of the project
	Name string `json:"name"`
	// Name of the organization
	OrgName string `json:"orgName"`
	// Display name of the project
	DisplayName string `json:"displayName"`
	// Timestamp when the project was created
	CreatedAt time.Time `json:"createdAt"`
}

// NewProjectListItem instantiates a new ProjectListItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectListItem(name string, orgName string, displayName string, createdAt time.Time) *ProjectListItem {
	this := ProjectListItem{}
	this.Name = name
	this.OrgName = orgName
	this.DisplayName = displayName
	this.CreatedAt = createdAt
	return &this
}

// NewProjectListItemWithDefaults instantiates a new ProjectListItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectListItemWithDefaults() *ProjectListItem {
	this := ProjectListItem{}
	return &this
}

// GetName returns the Name field value
func (o *ProjectListItem) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ProjectListItem) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ProjectListItem) SetName(v string) {
	o.Name = v
}

// GetOrgName returns the OrgName field value
func (o *ProjectListItem) GetOrgName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgName
}

// GetOrgNameOk returns a tuple with the OrgName field value
// and a boolean to check if the value has been set.
func (o *ProjectListItem) GetOrgNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgName, true
}

// SetOrgName sets field value
func (o *ProjectListItem) SetOrgName(v string) {
	o.OrgName = v
}

// GetDisplayName returns the DisplayName field value
func (o *ProjectListItem) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *ProjectListItem) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *ProjectListItem) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ProjectListItem) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ProjectListItem) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ProjectListItem) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o ProjectListItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectListItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["orgName"] = o.OrgName
	toSerialize["displayName"] = o.DisplayName
	toSerialize["createdAt"] = o.CreatedAt
	return toSerialize, nil
}

type NullableProjectListItem struct {
	value *ProjectListItem
	isSet bool
}

func (v NullableProjectListItem) Get() *ProjectListItem {
	return v.value
}

func (v *NullableProjectListItem) Set(val *ProjectListItem) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectListItem) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectListItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectListItem(val *ProjectListItem) *NullableProjectListItem {
	return &NullableProjectListItem{value: val, isSet: true}
}

func (v NullableProjectListItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectListItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
