/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the DeployAgentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeployAgentRequest{}

// DeployAgentRequest struct for DeployAgentRequest
type DeployAgentRequest struct {
	// Container image ID to deploy
	ImageId string `json:"imageId"`
	// Environment variables
	Env []EnvironmentVariable `json:"env,omitempty"`
}

// NewDeployAgentRequest instantiates a new DeployAgentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeployAgentRequest(imageId string) *DeployAgentRequest {
	this := DeployAgentRequest{}
	this.ImageId = imageId
	return &this
}

// NewDeployAgentRequestWithDefaults instantiates a new DeployAgentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeployAgentRequestWithDefaults() *DeployAgentRequest {
	this := DeployAgentRequest{}
	return &this
}

// GetImageId returns the ImageId field value
func (o *DeployAgentRequest) GetImageId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ImageId
}

// GetImageIdOk returns a tuple with the ImageId field value
// and a boolean to check if the value has been set.
func (o *DeployAgentRequest) GetImageIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImageId, true
}

// SetImageId sets field value
func (o *DeployAgentRequest) SetImageId(v string) {
	o.ImageId = v
}

// GetEnv returns the Env field value if set, zero value otherwise.
func (o *DeployAgentRequest) GetEnv() []EnvironmentVariable {
	if o == nil || IsNil(o.Env) {
		var ret []EnvironmentVariable
		return ret
	}
	return o.Env
}

// GetEnvOk returns a tuple with the Env field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeployAgentRequest) GetEnvOk() ([]EnvironmentVariable, bool) {
	if o == nil || IsNil(o.Env) {
		return nil, false
	}
	return o.Env, true
}

// HasEnv returns a boolean if a field has been set.
func (o *DeployAgentRequest) HasEnv() bool {
	if o != nil && !IsNil(o.Env) {
		return true
	}

	return false
}

// SetEnv gets a reference to the given []EnvironmentVariable and assigns it to the Env field.
func (o *DeployAgentRequest) SetEnv(v []EnvironmentVariable) {
	o.Env = v
}

func (o DeployAgentRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeployAgentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["imageId"] = o.ImageId
	if !IsNil(o.Env) {
		toSerialize["env"] = o.Env
	}
	return toSerialize, nil
}

type NullableDeployAgentRequest struct {
	value *DeployAgentRequest
	isSet bool
}

func (v NullableDeployAgentRequest) Get() *DeployAgentRequest {
	return v.value
}

func (v *NullableDeployAgentRequest) Set(val *DeployAgentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeployAgentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeployAgentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeployAgentRequest(val *DeployAgentRequest) *NullableDeployAgentRequest {
	return &NullableDeployAgentRequest{value: val, isSet: true}
}

func (v NullableDeployAgentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeployAgentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
