/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the PromotionPath type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PromotionPath{}

// PromotionPath struct for PromotionPath
type PromotionPath struct {
	// Reference to the source environment
	SourceEnvironmentRef string `json:"sourceEnvironmentRef"`
	// List of target environment references
	TargetEnvironmentRefs []TargetEnvironmentRef `json:"targetEnvironmentRefs"`
}

// NewPromotionPath instantiates a new PromotionPath object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPromotionPath(sourceEnvironmentRef string, targetEnvironmentRefs []TargetEnvironmentRef) *PromotionPath {
	this := PromotionPath{}
	this.SourceEnvironmentRef = sourceEnvironmentRef
	this.TargetEnvironmentRefs = targetEnvironmentRefs
	return &this
}

// NewPromotionPathWithDefaults instantiates a new PromotionPath object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPromotionPathWithDefaults() *PromotionPath {
	this := PromotionPath{}
	return &this
}

// GetSourceEnvironmentRef returns the SourceEnvironmentRef field value
func (o *PromotionPath) GetSourceEnvironmentRef() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceEnvironmentRef
}

// GetSourceEnvironmentRefOk returns a tuple with the SourceEnvironmentRef field value
// and a boolean to check if the value has been set.
func (o *PromotionPath) GetSourceEnvironmentRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceEnvironmentRef, true
}

// SetSourceEnvironmentRef sets field value
func (o *PromotionPath) SetSourceEnvironmentRef(v string) {
	o.SourceEnvironmentRef = v
}

// GetTargetEnvironmentRefs returns the TargetEnvironmentRefs field value
func (o *PromotionPath) GetTargetEnvironmentRefs() []TargetEnvironmentRef {
	if o == nil {
		var ret []TargetEnvironmentRef
		return ret
	}

	return o.TargetEnvironmentRefs
}

// GetTargetEnvironmentRefsOk returns a tuple with the TargetEnvironmentRefs field value
// and a boolean to check if the value has been set.
func (o *PromotionPath) GetTargetEnvironmentRefsOk() ([]TargetEnvironmentRef, bool) {
	if o == nil {
		return nil, false
	}
	return o.TargetEnvironmentRefs, true
}

// SetTargetEnvironmentRefs sets field value
func (o *PromotionPath) SetTargetEnvironmentRefs(v []TargetEnvironmentRef) {
	o.TargetEnvironmentRefs = v
}

func (o PromotionPath) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PromotionPath) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sourceEnvironmentRef"] = o.SourceEnvironmentRef
	toSerialize["targetEnvironmentRefs"] = o.TargetEnvironmentRefs
	return toSerialize, nil
}

type NullablePromotionPath struct {
	value *PromotionPath
	isSet bool
}

func (v NullablePromotionPath) Get() *PromotionPath {
	return v.value
}

func (v *NullablePromotionPath) Set(val *PromotionPath) {
	v.value = val
	v.isSet = true
}

func (v NullablePromotionPath) IsSet() bool {
	return v.isSet
}

func (v *NullablePromotionPath) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePromotionPath(val *PromotionPath) *NullablePromotionPath {
	return &NullablePromotionPath{value: val, isSet: true}
}

func (v NullablePromotionPath) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePromotionPath) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
