// Code generated by generate_api_client.sh script; DO NOT EDIT.

package spec

// defined type aliases here so that we can specify the custom types in api schema
// without having to add imports in auto-generated code
type MetricDateTime = string
