source ~/.zshrc 2>/dev/null || true # make aliases work

rm -rf spec
mkdir -p spec
cp scripts/.openapi-generator-ignore spec/.openapi-generator-ignore
# Remove tags from the openapi file to prevent changing output based on tags
npx openapi-format docs/api_v1_openapi.yaml -o spec/api_v1_openapi.yaml

USER_ID=$(id -u)
GROUP_ID=$(id -g)

docker run --rm -v "${PWD}:/local" -e GO_POST_PROCESS_FILE="/usr/local/bin/gofmt -w" \
    -u $USER_ID:$GROUP_ID \
    openapitools/openapi-generator-cli:v7.0.0 generate \
    -i /local/spec/api_v1_openapi.yaml \
    -g go \
    -o /local/spec \
    --package-name spec \
    --language-specific-primitives=UUID \
    --import-mappings db_types.UUID=github.com/wso2-enterprise/agent-manager-service/db_types \
    --type-mappings UUID=db_types.UUID \
    --schema-mappings MetricDateTime=string

rm spec/.openapi-generator-ignore
rm spec/api_v1_openapi.yaml
rm -rf spec/.openapi-generator
rm -rf spec/api
rm -rf spec/README.md
rm -rf spec/test
rm -f spec/**/*_test.go

cat <<EOF >spec/type_aliases.go
// Code generated by generate_api_client.sh script; DO NOT EDIT.

package spec

// defined type aliases here so that we can specify the custom types in api schema
// without having to add imports in auto-generated code
type MetricDateTime = string
EOF
