apiVersion: v2
name: wso2-ai-agent-management-platform
description: Helm chart for WSO2 Agent Management Platform - Deploy, manage, and govern AI agents at scale
type: application
version: v0.0.1
appVersion: "v0.0.1"

keywords:
  - wso2
  - ai
  - agent-management
  - ai-agents
  - observability

maintainers:
  - name: WSO2
    url: https://wso2.com

dependencies:
  # PostgreSQL Database
  - name: postgresql
    version: 18.1.13
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - database
