apiVersion: v2
name: wso2-ai-agent-management-platform
description: Helm chart for WSO2 Agent Management Platform - Deploy, manage, and govern AI agents at scale
type: application
version: 0.0.0-dev
appVersion: "0.0.0-dev"

keywords:
  - wso2
  - ai
  - agent-management
  - ai-agents
  - observability

maintainers:
  - name: WSO2
    url: https://wso2.com

dependencies:
  # PostgreSQL Database
  - name: postgresql
    version: 18.1.13
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - database

  # Default Resources Extension
  - name: wso2-amp-default-resources-extension
    version: 0.0.0-dev
    repository: file://../wso2-amp-default-resources-extension
    tags:
      - default-resources
