apiVersion: openchoreo.dev/v1alpha1
kind: ComponentType
metadata:
  name: agent-api
  namespace: default
  annotations:
    openchoreo.dev/display-name: Platform Hosted Agent API
    openchoreo.dev/description: Component type for deploying agent APIs in the AI Agent Management Platform.
spec:
  workloadType: deployment

  allowedWorkflows:
    - google-cloud-buildpacks
    - ballerina-buildpack

  schema:
    types:
      ResourceRequirements:
        requests: "ResourceQuantity | default={}"
        limits: "ResourceQuantity | default={}"
      ResourceQuantity:
        cpu: "string | default=100m"
        memory: "string | default=256Mi"

    parameters:
      replicas: "integer | default=1"
      imagePullPolicy: "string | default=IfNotPresent"
      port: "integer | default=80"
      exposed: "boolean | default=false"
      containerName: "string | default=main"
      basePath: "string | default=/"

    envOverrides:
      resources: "ResourceRequirements | default={}"

  resources:
    - id: deployment
      template:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: ${metadata.name}
          namespace: ${metadata.namespace}
          labels: ${metadata.labels}
        spec:
          replicas: ${parameters.replicas}
          selector:
            matchLabels: ${metadata.podSelectors}
          template:
            metadata:
              labels: ${metadata.podSelectors}
            spec:
              containers:
                - name: ${parameters.containerName}
                  image: ${workload.containers[parameters.containerName].image}
                  imagePullPolicy: ${parameters.imagePullPolicy}
                  command: |
                    ${has(workload.containers[parameters.containerName].command) ? workload.containers[parameters.containerName].command : oc_omit()}
                  args: |
                    ${has(workload.containers[parameters.containerName].args) ? workload.containers[parameters.containerName].args : oc_omit()}
                  ports:
                    - name: http
                      containerPort: ${parameters.port}
                      protocol: TCP
                  resources:
                    requests:
                      cpu: ${parameters.resources.requests.cpu}
                      memory: ${parameters.resources.requests.memory}
                    limits:
                      cpu: ${parameters.resources.limits.cpu}
                      memory: ${parameters.resources.limits.memory}
                  envFrom: |
                    ${(has(configurations[parameters.containerName].configs.envs) && configurations[parameters.containerName].configs.envs.size() > 0 ?
                      [{
                        "configMapRef": {
                          "name": oc_generate_name(metadata.name, "env-configs")
                        }
                      }] : []) +
                     (has(configurations[parameters.containerName].secrets.envs) && configurations[parameters.containerName].secrets.envs.size() > 0 ?
                      [{
                        "secretRef": {
                          "name": oc_generate_name(metadata.name, "env-secrets")
                        }
                      }] : [])}
                  volumeMounts: |
                    ${has(configurations[parameters.containerName].configs.files) && configurations[parameters.containerName].configs.files.size() > 0 || has(configurations[parameters.containerName].secrets.files) && configurations[parameters.containerName].secrets.files.size() > 0 ?
                      (has(configurations[parameters.containerName].configs.files) && configurations[parameters.containerName].configs.files.size() > 0 ?
                        configurations[parameters.containerName].configs.files.map(f, {
                          "name": "file-mount-"+oc_hash(f.mountPath+"/"+f.name),
                          "mountPath": f.mountPath+"/"+f.name ,
                          "subPath": f.name
                        }) : []) +
                       (has(configurations[parameters.containerName].secrets.files) && configurations[parameters.containerName].secrets.files.size() > 0 ?
                        configurations[parameters.containerName].secrets.files.map(f, {
                          "name": "file-mount-"+oc_hash(f.mountPath+"/"+f.name),
                          "mountPath": f.mountPath+"/"+f.name,
                          "subPath": f.name
                        }) : [])
                    : oc_omit()}
              volumes: |
                ${has(configurations[parameters.containerName].configs.files) && configurations[parameters.containerName].configs.files.size() > 0 || has(configurations[parameters.containerName].secrets.files) && configurations[parameters.containerName].secrets.files.size() > 0 ?
                  (has(configurations[parameters.containerName].configs.files) && configurations[parameters.containerName].configs.files.size() > 0 ?
                    configurations[parameters.containerName].configs.files.map(f, {
                      "name": "file-mount-"+oc_hash(f.mountPath+"/"+f.name),
                      "configMap": {
                        "name": oc_generate_name(metadata.name, "config", f.name).replace(".", "-")
                      }
                    }) : []) +
                   (has(configurations[parameters.containerName].secrets.files) && configurations[parameters.containerName].secrets.files.size() > 0 ?
                    configurations[parameters.containerName].secrets.files.map(f, {
                      "name": "file-mount-"+oc_hash(f.mountPath+"/"+f.name),
                      "secret": {
                        "secretName": oc_generate_name(metadata.name, "secret", f.name).replace(".", "-")
                      }
                    }) : [])
                : oc_omit()}

    - id: service
      template:
        apiVersion: v1
        kind: Service
        metadata:
          name: ${metadata.componentName}
          namespace: ${metadata.namespace}
          labels: ${metadata.labels}
        spec:
          type: ClusterIP
          selector: ${metadata.podSelectors}
          ports:
            - name: http
              port: 80
              targetPort: ${parameters.port}
              protocol: TCP
    - id: httproute
      includeWhen: ${parameters.exposed == true}
      template:
        apiVersion: gateway.networking.k8s.io/v1
        kind: HTTPRoute
        metadata:
          name: ${metadata.name}
          namespace: ${metadata.namespace}
          labels: ${metadata.labels}
        spec:
          parentRefs:
            - name: gateway-default
              namespace: openchoreo-data-plane
          hostnames:
            - ${metadata.environmentName}.${dataplane.publicVirtualHost}
          rules:
            - matches:
                - path:
                    type: PathPrefix
                    value: /${metadata.componentName}
              filters:
                - type: URLRewrite
                  urlRewrite:
                    path:
                      type: ReplacePrefixMatch
                      replacePrefixMatch: ${parameters.basePath}
                - type: CORS
                  cors:
                    allowOrigins:
                      - "*"
                    allowMethods:
                      - "*"
                    allowHeaders:
                      - "*"
              backendRefs:
                - name: ${metadata.componentName}
                  port: 80
    - id: env-config
      includeWhen: ${has(configurations[parameters.containerName].configs.envs) && configurations[parameters.containerName].configs.envs.size() > 0}
      template:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: ${oc_generate_name(metadata.name, "env-configs")}
          namespace: ${metadata.namespace}
        data: |
          ${has(configurations[parameters.containerName].configs.envs) ? configurations[parameters.containerName].configs.envs.transformMapEntry(index, env, {env.name: env.value}) : oc_omit()}
