// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wiring

import (
	"log/slog"

	"github.com/google/wire"

	"github.com/wso2/ai-agent-management-platform/agent-manager-service/clients/observabilitysvc"
	"github.com/wso2/ai-agent-management-platform/agent-manager-service/clients/openchoreosvc"
	"github.com/wso2/ai-agent-management-platform/agent-manager-service/config"
	"github.com/wso2/ai-agent-management-platform/agent-manager-service/controllers"
	"github.com/wso2/ai-agent-management-platform/agent-manager-service/middleware/jwtassertion"
	"github.com/wso2/ai-agent-management-platform/agent-manager-service/repositories"
	"github.com/wso2/ai-agent-management-platform/agent-manager-service/services"
)

// Injectors from wire.go:

func InitializeAppParams(cfg *config.Config) (*AppParams, error) {
	configConfig := ProvideConfigFromPtr(cfg)
	middleware := ProvideAuthMiddleware(configConfig)
	organizationRepository := repositories.NewOrganizationRepository()
	projectRepository := repositories.NewProjectRepository()
	agentRepository := repositories.NewAgentRepository()
	internalAgentRepository := repositories.NewInternalAgentRepository()
	openChoreoSvcClient, err := openchoreosvc.NewOpenChoreoSvcClient()
	if err != nil {
		return nil, err
	}
	observabilitySvcClient := observabilitysvc.NewObservabilitySvcClient()
	logger := ProvideLogger()
	agentManagerService := services.NewAgentManagerService(organizationRepository, projectRepository, agentRepository, internalAgentRepository, openChoreoSvcClient, observabilitySvcClient, logger)
	agentController := controllers.NewAgentController(agentManagerService)
	infraResourceManager := services.NewInfraResourceManager(organizationRepository, projectRepository, agentRepository, openChoreoSvcClient, logger)
	infraResourceController := controllers.NewInfraResourceController(infraResourceManager)
	buildCIManagerService := services.NewBuildCIManager(openChoreoSvcClient, logger)
	buildCIController := controllers.NewBuildCIController(buildCIManagerService)
	appParams := &AppParams{
		AuthMiddleware:          middleware,
		AgentController:         agentController,
		InfraResourceController: infraResourceController,
		BuildCIController:       buildCIController,
	}
	return appParams, nil
}

func InitializeTestAppParamsWithClientMocks(cfg *config.Config, authMiddleware jwtassertion.Middleware, testClients TestClients) (*AppParams, error) {
	organizationRepository := repositories.NewOrganizationRepository()
	projectRepository := repositories.NewProjectRepository()
	agentRepository := repositories.NewAgentRepository()
	internalAgentRepository := repositories.NewInternalAgentRepository()
	openChoreoSvcClient := ProvideTestOpenChoreoSvcClient(testClients)
	observabilitySvcClient := ProvideTestObservabilitySvcClient(testClients)
	logger := ProvideLogger()
	agentManagerService := services.NewAgentManagerService(organizationRepository, projectRepository, agentRepository, internalAgentRepository, openChoreoSvcClient, observabilitySvcClient, logger)
	agentController := controllers.NewAgentController(agentManagerService)
	infraResourceManager := services.NewInfraResourceManager(organizationRepository, projectRepository, agentRepository, openChoreoSvcClient, logger)
	infraResourceController := controllers.NewInfraResourceController(infraResourceManager)
	buildCIManagerService := services.NewBuildCIManager(openChoreoSvcClient, logger)
	buildCIController := controllers.NewBuildCIController(buildCIManagerService)
	appParams := &AppParams{
		AuthMiddleware:          authMiddleware,
		AgentController:         agentController,
		InfraResourceController: infraResourceController,
		BuildCIController:       buildCIController,
	}
	return appParams, nil
}

// wire.go:

var configProviderSet = wire.NewSet(
	ProvideConfigFromPtr,
)

var repositoryProviderSet = wire.NewSet(repositories.NewOrganizationRepository, repositories.NewAgentRepository, repositories.NewProjectRepository, repositories.NewInternalAgentRepository)

var clientProviderSet = wire.NewSet(openchoreosvc.NewOpenChoreoSvcClient, observabilitysvc.NewObservabilitySvcClient)

var serviceProviderSet = wire.NewSet(services.NewAgentManagerService, services.NewBuildCIManager, services.NewInfraResourceManager)

var controllerProviderSet = wire.NewSet(controllers.NewAgentController, controllers.NewBuildCIController, controllers.NewInfraResourceController)

var testClientProviderSet = wire.NewSet(
	ProvideTestOpenChoreoSvcClient,
	ProvideTestObservabilitySvcClient,
)

// ProvideLogger provides the configured slog.Logger instance
func ProvideLogger() *slog.Logger {
	return slog.Default()
}

var loggerProviderSet = wire.NewSet(
	ProvideLogger,
)

// ProvideTestOpenChoreoSvcClient extracts the OpenChoreoSvcClient from TestClients
func ProvideTestOpenChoreoSvcClient(testClients TestClients) openchoreosvc.OpenChoreoSvcClient {
	return testClients.OpenChoreoSvcClient
}

// ProvideTestObservabilitySvcClient extracts the ObservabilitySvcClient from TestClients
func ProvideTestObservabilitySvcClient(testClients TestClients) observabilitysvc.ObservabilitySvcClient {
	return testClients.ObservabilitySvcClient
}
