apiVersion: openchoreo.dev/v1alpha1
kind: ComponentWorkflow
metadata:
  name: google-cloud-buildpacks-default
  namespace: default
  annotations:
    openchoreo.dev/description: "Google Cloud Buildpacks workflow for containerized builds"
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "7"
spec:
  # Schema definition for component workflows
  schema:
    # System parameters - Required structured parameters for component builds
    # These fields are necessary for build-specific platform features (webhooks, auto-build, UI actions)
    # Platform Engineers can customize defaults, enums, and descriptions, but must maintain the field structure
    # Note: All systemParameters fields must be of type string to ensure compatibility with build automation
    systemParameters:
      repository:
        url: string | description="Git repository URL"
        revision:
          branch: string | default=main description="Git branch to checkout"
          commit: string | description="Git commit SHA or reference (optional, defaults to latest)"
        appPath: string | default=. description="Path to the application directory within the repository"

    # Developer-configurable parameters - PE-defined schema for additional build configuration
    parameters: {}

  # Rendered workflow resource for ComponentWorkflowRun executions
  runTemplate:
    apiVersion: argoproj.io/v1alpha1
    kind: Workflow
    metadata:
      name: ${ctx.componentWorkflowRunName}
      namespace: openchoreo-ci-${ctx.orgName}
    spec:
      arguments:
        parameters:
          - name: component-name
            value: ${ctx.componentName}
          - name: project-name
            value: ${ctx.projectName}
          # Parameters from system parameters (developer-facing)
          - name: git-repo
            value: ${systemParameters.repository.url}
          - name: branch
            value: ${systemParameters.repository.revision.branch}
          - name: commit
            value: ${systemParameters.repository.revision.commit}
          - name: app-path
            value: ${systemParameters.repository.appPath}
          # PE-controlled hardcoded parameters
          - name: image-name
            value: ${ctx.projectName}-${ctx.componentName}-image
          - name: image-tag
            value: v1
      serviceAccountName: workflow-sa
      workflowTemplateRef:
        clusterScope: true
        name: google-cloud-buildpacks
