apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: opentelemetry-collector
  ports:
    - name: otlp-http
      port: 21893
      targetPort: 4318
      protocol: TCP
